In [7]:
import sys

import numpy as np
import pandas as pd


import plotly.offline as py

py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.tools as tls
import seaborn as sns
import matplotlib.pyplot as plt


from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, log_loss
from imblearn.over_sampling import SMOTE
import xgboost as xgb
from sklearn.model_selection import train_test_split

# Import and suppress warnings
import warnings

warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv("../data/HR-Employee-Attrition.csv")

In [6]:
df.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7

In [9]:
df.isna().sum().any()

np.False_

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [11]:
categorical = df.select_dtypes(include=["object"])

In [12]:
categorical.head(10)

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,Yes,Travel_Rarely,Sales,Life Sciences,Female,Sales Executive,Single,Y,Yes
1,No,Travel_Frequently,Research & Development,Life Sciences,Male,Research Scientist,Married,Y,No
2,Yes,Travel_Rarely,Research & Development,Other,Male,Laboratory Technician,Single,Y,Yes
3,No,Travel_Frequently,Research & Development,Life Sciences,Female,Research Scientist,Married,Y,Yes
4,No,Travel_Rarely,Research & Development,Medical,Male,Laboratory Technician,Married,Y,No
5,No,Travel_Frequently,Research & Development,Life Sciences,Male,Laboratory Technician,Single,Y,No
6,No,Travel_Rarely,Research & Development,Medical,Female,Laboratory Technician,Married,Y,Yes
7,No,Travel_Rarely,Research & Development,Life Sciences,Male,Laboratory Technician,Divorced,Y,No
8,No,Travel_Frequently,Research & Development,Life Sciences,Male,Manufacturing Director,Single,Y,No
9,No,Travel_Rarely,Research & Development,Medical,Male,Healthcare Representative,Married,Y,No

In [39]:
categorical = pd.get_dummies(categorical, drop_first=True, dtype=int)

## GBM Classifier

#### 1.n_estimators - No of Trees in the Model

###### 2.max_features - The number of features to consider while searching for a best split.Thumb Rule to have Square root of no of Columns

##### 3.max_depth - Maximum Depth of Tree and can be used to control overfiting

##### 4.min_samples_leaf - Minimum samples (or observations) required in a terminal node or leaf.In general we need to have lower values  for it for Imbalanced problems

##### 5.subsample- The fraction of samples to be used for fitting the individual base learners

##### 6.learning_rate - Learning rate shrinks the contribution of each tree by learning_rate. There is a trade-off between learning_rate and n_estimators

In [14]:
help(GradientBoostingClassifier)

Help on class GradientBoostingClassifier in module sklearn.ensemble._gb:

class GradientBoostingClassifier(sklearn.base.ClassifierMixin, BaseGradientBoosting)
 |  GradientBoostingClassifier(*, loss='log_loss', learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0, init=None, random_state=None, max_features=None, verbose=0, max_leaf_nodes=None, warm_start=False, validation_fraction=0.1, n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0)
 |
 |  Gradient Boosting for classification.
 |
 |  This algorithm builds an additive model in a forward stage-wise fashion; it
 |  allows for the optimization of arbitrary differentiable loss functions. In
 |  each stage ``n_classes_`` regression trees are fit on the negative gradient
 |  of the loss function, e.g. binary or multiclass log loss. Binary
 |  classification is a special case where only a single regression tree is
 |  induced.
 |
 |  :class:`~sklearn.ensemble.HistGradientBoostingClassifier` is a much faster variant
 |  of this algorithm for intermediate and large datasets (`n_samples >= 10_000`) and
 |  supports monotonic constraints.
 |
 |  Read more in the :ref:`User Guide <gradient_boosting>`.
 |
 |  Parameters
 |  ----------
 |  loss : {'log_loss', 'exponential'}, default='log_loss'
 |      The loss function to be optimized. 'log_loss' refers to binomial and
 |      multinomial deviance, the same as used in logistic regression.
 |      It is a good choice for classification with probabilistic outputs.
 |      For loss 'exponential', gradient boosting recovers the AdaBoost algorithm.
 |
 |  learning_rate : float, default=0.1
 |      Learning rate shrinks the contribution of each tree by `learning_rate`.
 |      There is a trade-off between learning_rate and n_estimators.
 |      Values must be in the range `[0.0, inf)`.
 |
 |  n_estimators : int, default=100
 |      The number of boosting stages to perform. Gradient boosting
 |      is fairly robust to over-fitting so a large number usually
 |      results in better performance.
 |      Values must be in the range `[1, inf)`.
 |
 |  subsample : float, default=1.0
 |      The fraction of samples to be used for fitting the individual base
 |      learners. If smaller than 1.0 this results in Stochastic Gradient
 |      Boosting. `subsample` interacts with the parameter `n_estimators`.
 |      Choosing `subsample < 1.0` leads to a reduction of variance
 |      and an increase in bias.
 |      Values must be in the range `(0.0, 1.0]`.
 |
 |  criterion : {'friedman_mse', 'squared_error'}, default='friedman_mse'
 |      The function to measure the quality of a split. Supported criteria are
 |      'friedman_mse' for the mean squared error with improvement score by
 |      Friedman, 'squared_error' for mean squared error. The default value of
 |      'friedman_mse' is generally the best as it can provide a better
 |      approximation in some cases.
 |
 |      .. versionadded:: 0.18
 |
 |  min_samples_split : int or float, default=2
 |      The minimum number of samples required to split an internal node:
 |
 |      - If int, values must be in the range `[2, inf)`.
 |      - If float, values must be in the range `(0.0, 1.0]` and `min_samples_split`
 |        will be `ceil(min_samples_split * n_samples)`.
 |
 |      .. versionchanged:: 0.18
 |         Added float values for fractions.
 |
 |  min_samples_leaf : int or float, default=1
 |      The minimum number of samples required to be at a leaf node.
 |      A split point at any depth will only be considered if it leaves at
 |      least ``min_samples_leaf`` training samples in each of the left and
 |      right branches.  This may have the effect of smoothing the model,
 |      especially in regression.
 |
 |      - If int, values must be in the range `[1, inf)`.
 |      - If float, values must be in the range `(0.0, 1.0)` and `min_samples_leaf`
 |        will be `ceil(min_samples_leaf * n_samples)`.
 |
 |      .. versionchanged:: 0.18
 |         Added float values for fractions.
 |
 |  min_weight_fraction_leaf : float, default=0.0
 |      The minimum weighted fraction of the sum total of weights (of all
 |      the input samples) required to be at a leaf node. Samples have
 |      equal weight when sample_weight is not provided.
 |      Values must be in the range `[0.0, 0.5]`.
 |
 |  max_depth : int or None, default=3
 |      Maximum depth of the individual regression estimators. The maximum
 |      depth limits the number of nodes in the tree. Tune this parameter
 |      for best performance; the best value depends on the interaction
 |      of the input variables. If None, then nodes are expanded until
 |      all leaves are pure or until all leaves contain less than
 |      min_samples_split samples.
 |      If int, values must be in the range `[1, inf)`.
 |
 |  min_impurity_decrease : float, default=0.0
 |      A node will be split if this split induces a decrease of the impurity
 |      greater than or equal to this value.
 |      Values must be in the range `[0.0, inf)`.
 |
 |      The weighted impurity decrease equation is the following::
 |
 |          N_t / N * (impurity - N_t_R / N_t * right_impurity
 |                              - N_t_L / N_t * left_impurity)
 |
 |      where ``N`` is the total number of samples, ``N_t`` is the number of
 |      samples at the current node, ``N_t_L`` is the number of samples in the
 |      left child, and ``N_t_R`` is the number of samples in the right child.
 |
 |      ``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,
 |      if ``sample_weight`` is passed.
 |
 |      .. versionadded:: 0.19
 |
 |  init : estimator or 'zero', default=None
 |      An estimator object that is used to compute the initial predictions.
 |      ``init`` has to provide :term:`fit` and :term:`predict_proba`. If
 |      'zero', the initial raw predictions are set to zero. By default, a
 |      ``DummyEstimator`` predicting the classes priors is used.
 |
 |  random_state : int, RandomState instance or None, default=None
 |      Controls the random seed given to each Tree estimator at each
 |      boosting iteration.
 |      In addition, it controls the random permutation of the features at
 |      each split (see Notes for more details).
 |      It also controls the random splitting of the training data to obtain a
 |      validation set if `n_iter_no_change` is not None.
 |      Pass an int for reproducible output across multiple function calls.
 |      See :term:`Glossary <random_state>`.
 |
 |  max_features : {'sqrt', 'log2'}, int or float, default=None
 |      The number of features to consider when looking for the best split:
 |
 |      - If int, values must be in the range `[1, inf)`.
 |      - If float, values must be in the range `(0.0, 1.0]` and the features
 |        considered at each split will be `max(1, int(max_features * n_features_in_))`.
 |      - If 'sqrt', then `max_features=sqrt(n_features)`.
 |      - If 'log2', then `max_features=log2(n_features)`.
 |      - If None, then `max_features=n_features`.
 |
 |      Choosing `max_features < n_features` leads to a reduction of variance
 |      and an increase in bias.
 |
 |      Note: the search for a split does not stop until at least one
 |      valid partition of the node samples is found, even if it requires to
 |      effectively inspect more than ``max_features`` features.
 |
 |  verbose : int, default=0
 |      Enable verbose output. If 1 then it prints progress and performance
 |      once in a while (the more trees the lower the frequency). If greater
 |      than 1 then it prints progress and performance for every tree.
 |      Values must be in the range `[0, inf)`.
 |
 |  max_leaf_nodes : int, default=None
 |      Grow trees with ``max_leaf_nodes`` in best-first fashion.
 |      Best nodes are defined as relative reduction in impurity.
 |      Values must be in the range `[2, inf)`.
 |      If `None`, then unlimited number of leaf nodes.
 |
 |  warm_start : bool, default=False
 |      When set to ``True``, reuse the solution of the previous call to fit
 |      and add more estimators to the ensemble, otherwise, just erase the
 |      previous solution. See :term:`the Glossary <warm_start>`.
 |
 |  validation_fraction : float, default=0.1
 |      The proportion of training data to set aside as validation set for
 |      early stopping. Values must be in the range `(0.0, 1.0)`.
 |      Only used if ``n_iter_no_change`` is set to an integer.
 |
 |      .. versionadded:: 0.20
 |
 |  n_iter_no_change : int, default=None
 |      ``n_iter_no_change`` is used to decide if early stopping will be used
 |      to terminate training when validation score is not improving. By
 |      default it is set to None to disable early stopping. If set to a
 |      number, it will set aside ``validation_fraction`` size of the training
 |      data as validation and terminate training when validation score is not
 |      improving in all of the previous ``n_iter_no_change`` numbers of
 |      iterations. The split is stratified.
 |      Values must be in the range `[1, inf)`.
 |      See
 |      :ref:`sphx_glr_auto_examples_ensemble_plot_gradient_boosting_early_stopping.py`.
 |
 |      .. versionadded:: 0.20
 |
 |  tol : float, default=1e-4
 |      Tolerance for the early stopping. When the loss is not improving
 |      by at least tol for ``n_iter_no_change`` iterations (if set to a
 |      number), the training stops.
 |      Values must be in the range `[0.0, inf)`.
 |
 |      .. versionadded:: 0.20
 |
 |  ccp_alpha : non-negative float, default=0.0
 |      Complexity parameter used for Minimal Cost-Complexity Pruning. The
 |      subtree with the largest cost complexity that is smaller than
 |      ``ccp_alpha`` will be chosen. By default, no pruning is performed.
 |      Values must be in the range `[0.0, inf)`.
 |      See :ref:`minimal_cost_complexity_pruning` for details. See
 |      :ref:`sphx_glr_auto_examples_tree_plot_cost_complexity_pruning.py`
 |      for an example of such pruning.
 |
 |      .. versionadded:: 0.22
 |
 |  Attributes
 |  ----------
 |  n_estimators_ : int
 |      The number of estimators as selected by early stopping (if
 |      ``n_iter_no_change`` is specified). Otherwise it is set to
 |      ``n_estimators``.
 |
 |      .. versionadded:: 0.20
 |
 |  n_trees_per_iteration_ : int
 |      The number of trees that are built at each iteration. For binary classifiers,
 |      this is always 1.
 |
 |      .. versionadded:: 1.4.0
 |
 |  feature_importances_ : ndarray of shape (n_features,)
 |      The impurity-based feature importances.
 |      The higher, the more important the feature.
 |      The importance of a feature is computed as the (normalized)
 |      total reduction of the criterion brought by that feature.  It is also
 |      known as the Gini importance.
 |
 |      Warning: impurity-based feature importances can be misleading for
 |      high cardinality features (many unique values). See
 |      :func:`sklearn.inspection.permutation_importance` as an alternative.
 |
 |  oob_improvement_ : ndarray of shape (n_estimators,)
 |      The improvement in loss on the out-of-bag samples
 |      relative to the previous iteration.
 |      ``oob_improvement_[0]`` is the improvement in
 |      loss of the first stage over the ``init`` estimator.
 |      Only available if ``subsample < 1.0``.
 |
 |  oob_scores_ : ndarray of shape (n_estimators,)
 |      The full history of the loss values on the out-of-bag
 |      samples. Only available if `subsample < 1.0`.
 |
 |      .. versionadded:: 1.3
 |
 |  oob_score_ : float
 |      The last value of the loss on the out-of-bag samples. It is
 |      the same as `oob_scores_[-1]`. Only available if `subsample < 1.0`.
 |
 |      .. versionadded:: 1.3
 |
 |  train_score_ : ndarray of shape (n_estimators,)
 |      The i-th score ``train_score_[i]`` is the loss of the
 |      model at iteration ``i`` on the in-bag sample.
 |      If ``subsample == 1`` this is the loss on the training data.
 |
 |  init_ : estimator
 |      The estimator that provides the initial predictions. Set via the ``init``
 |      argument.
 |
 |  estimators_ : ndarray of DecisionTreeRegressor of             shape (n_estimators, ``n_trees_per_iteration_``)
 |      The collection of fitted sub-estimators. ``n_trees_per_iteration_`` is 1 for
 |      binary classification, otherwise ``n_classes``.
 |
 |  classes_ : ndarray of shape (n_classes,)
 |      The classes labels.
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  n_classes_ : int
 |      The number of classes.
 |
 |  max_features_ : int
 |      The inferred value of max_features.
 |
 |  See Also
 |  --------
 |  HistGradientBoostingClassifier : Histogram-based Gradient Boosting
 |      Classification Tree.
 |  sklearn.tree.DecisionTreeClassifier : A decision tree classifier.
 |  RandomForestClassifier : A meta-estimator that fits a number of decision
 |      tree classifiers on various sub-samples of the dataset and uses
 |      averaging to improve the predictive accuracy and control over-fitting.
 |  AdaBoostClassifier : A meta-estimator that begins by fitting a classifier
 |      on the original dataset and then fits additional copies of the
 |      classifier on the same dataset where the weights of incorrectly
 |      classified instances are adjusted such that subsequent classifiers
 |      focus more on difficult cases.
 |
 |  Notes
 |  -----
 |  The features are always randomly permuted at each split. Therefore,
 |  the best found split may vary, even with the same training data and
 |  ``max_features=n_features``, if the improvement of the criterion is
 |  identical for several splits enumerated during the search of the best
 |  split. To obtain a deterministic behaviour during fitting,
 |  ``random_state`` has to be fixed.
 |
 |  References
 |  ----------
 |  J. Friedman, Greedy Function Approximation: A Gradient Boosting
 |  Machine, The Annals of Statistics, Vol. 29, No. 5, 2001.
 |
 |  J. Friedman, Stochastic Gradient Boosting, 1999
 |
 |  T. Hastie, R. Tibshirani and J. Friedman.
 |  Elements of Statistical Learning Ed. 2, Springer, 2009.
 |
 |  Examples
 |  --------
 |  The following example shows how to fit a gradient boosting classifier with
 |  100 decision stumps as weak learners.
 |
 |  >>> from sklearn.datasets import make_hastie_10_2
 |  >>> from sklearn.ensemble import GradientBoostingClassifier
 |
 |  >>> X, y = make_hastie_10_2(random_state=0)
 |  >>> X_train, X_test = X[:2000], X[2000:]
 |  >>> y_train, y_test = y[:2000], y[2000:]
 |
 |  >>> clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
 |  ...     max_depth=1, random_state=0).fit(X_train, y_train)
 |  >>> clf.score(X_test, y_test)
 |  0.913...
 |
 |  Method resolution order:
 |      GradientBoostingClassifier
 |      sklearn.base.ClassifierMixin
 |      BaseGradientBoosting
 |      sklearn.ensemble._base.BaseEnsemble
 |      sklearn.base.MetaEstimatorMixin
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._estimator_html_repr._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *, loss='log_loss', learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0, init=None, random_state=None, max_features=None, verbose=0, max_leaf_nodes=None, warm_start=False, validation_fraction=0.1, n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  decision_function(self, X)
 |      Compute the decision function of ``X``.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input samples. Internally, it will be converted to
 |          ``dtype=np.float32`` and if a sparse matrix is provided
 |          to a sparse ``csr_matrix``.
 |
 |      Returns
 |      -------
 |      score : ndarray of shape (n_samples, n_classes) or (n_samples,)
 |          The decision function of the input samples, which corresponds to
 |          the raw values predicted from the trees of the ensemble . The
 |          order of the classes corresponds to that in the attribute
 |          :term:`classes_`. Regression and binary classification produce an
 |          array of shape (n_samples,).
 |
 |  predict(self, X)
 |      Predict class for X.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input samples. Internally, it will be converted to
 |          ``dtype=np.float32`` and if a sparse matrix is provided
 |          to a sparse ``csr_matrix``.
 |
 |      Returns
 |      -------
 |      y : ndarray of shape (n_samples,)
 |          The predicted values.
 |
 |  predict_log_proba(self, X)
 |      Predict class log-probabilities for X.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input samples. Internally, it will be converted to
 |          ``dtype=np.float32`` and if a sparse matrix is provided
 |          to a sparse ``csr_matrix``.
 |
 |      Returns
 |      -------
 |      p : ndarray of shape (n_samples, n_classes)
 |          The class log-probabilities of the input samples. The order of the
 |          classes corresponds to that in the attribute :term:`classes_`.
 |
 |      Raises
 |      ------
 |      AttributeError
 |          If the ``loss`` does not support probabilities.
 |
 |  predict_proba(self, X)
 |      Predict class probabilities for X.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The input samples. Internally, it will be converted to
 |          ``dtype=np.float32`` and if a sparse matrix is provided
 |          to a sparse ``csr_matrix``.
 |
 |      Returns
 |      -------
 |      p : ndarray of shape (n_samples, n_classes)
 |          The class probabilities of the input samples. The order of the
 |          classes corresponds to that in the attribute :term:`classes_`.
 |
 |      Raises
 |      ------
 |      AttributeError
 |          If the ``loss`` does not support probabilities.
 |
 |  set_fit_request(self: sklearn.ensemble._gb.GradientBoostingClassifier, *, monitor: Union[bool, NoneType, str] = '$UNCHANGED$', sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.ensemble._gb.GradientBoostingClassifier from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Request metadata passed to the ``fit`` method.
 |
 |      Note that this method is only relevant if
 |      ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please see :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``fit`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``fit``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |

In [16]:
import importlib
from utilties.utils import unique_values_percentage

help(unique_values_percentage)

Help on function unique_values_percentage in module utilties.utils:

unique_values_percentage(df, columns)
    A function to calculate the summary of categorical columns of a dataframe
        @param: df -> DataFrame
        @param columns: list of categorical columns in the dataframe
        @returns: dictionary of summary of unique value counts and their percentages
    >>> x = pd.DataFrame({'temp':['hot','hot','cool']})

In [19]:
import sys
from utilties import utils

importlib.reload(utils)

In [22]:
gb = GradientBoostingClassifier(random_state=0)

list(gb.get_params().items())

[('ccp_alpha', 0.0),
 ('criterion', 'friedman_mse'),
 ('init', None),
 ('learning_rate', 0.1),
 ('loss', 'log_loss'),
 ('max_depth', 3),
 ('max_features', None),
 ('max_leaf_nodes', None),
 ('min_impurity_decrease', 0.0),
 ('min_samples_leaf', 1),
 ('min_samples_split', 2),
 ('min_weight_fraction_leaf', 0.0),
 ('n_estimators', 100),
 ('n_iter_no_change', None),
 ('random_state', 0),
 ('subsample', 1.0),
 ('tol', 0.0001),
 ('validation_fraction', 0.1),
 ('verbose', 0),
 ('warm_start', False)]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [41]:
df_num = df.select_dtypes(include=["int64"])

In [42]:
df_num.head(10)

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,1,1,2,94,3,2,...,1,80,0,8,0,1,6,4,0,5
1,49,279,8,1,1,2,3,61,2,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1373,2,2,1,4,4,92,2,1,...,2,80,0,7,3,3,0,0,0,0
3,33,1392,3,4,1,5,4,56,3,1,...,3,80,0,8,3,3,8,7,3,0
4,27,591,2,1,1,7,1,40,3,1,...,4,80,1,6,3,3,2,2,2,2
5,32,1005,2,2,1,8,4,79,3,1,...,3,80,0,8,2,2,7,7,3,6
6,59,1324,3,3,1,10,3,81,4,1,...,1,80,3,12,3,2,1,0,0,0
7,30,1358,24,1,1,11,4,67,3,1,...,2,80,1,1,2,3,1,0,0,0
8,38,216,23,3,1,12,4,44,2,3,...,2,80,0,10,2,3,9,7,1,8
9,36,1299,27,3,1,13,3,94,3,2,...,2,80,2,17,3,2,7,7,7,7

In [28]:
categorical.drop("Attrition", axis=1, inplace=True)

In [29]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
help(le)

Help on LabelEncoder in module sklearn.preprocessing._label object:

class LabelEncoder(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
 |  Encode target labels with value between 0 and n_classes-1.
 |
 |  This transformer should be used to encode target values, *i.e.* `y`, and
 |  not the input `X`.
 |
 |  Read more in the :ref:`User Guide <preprocessing_targets>`.
 |
 |  .. versionadded:: 0.12
 |
 |  Attributes
 |  ----------
 |  classes_ : ndarray of shape (n_classes,)
 |      Holds the label for each class.
 |
 |  See Also
 |  --------
 |  OrdinalEncoder : Encode categorical features using an ordinal encoding
 |      scheme.
 |  OneHotEncoder : Encode categorical features as a one-hot numeric array.
 |
 |  Examples
 |  --------
 |  `LabelEncoder` can be used to normalize labels.
 |
 |  >>> from sklearn.preprocessing import LabelEncoder
 |  >>> le = LabelEncoder()
 |  >>> le.fit([1, 2, 2, 6])
 |  LabelEncoder()
 |  >>> le.classes_
 |  array([1, 2, 6])
 |  >>> le.transform([1, 1, 2, 6])
 |  array([0, 0, 1, 2]...)
 |  >>> le.inverse_transform([0, 0, 1, 2])
 |  array([1, 1, 2, 6])
 |
 |  It can also be used to transform non-numerical labels (as long as they are
 |  hashable and comparable) to numerical labels.
 |
 |  >>> le = LabelEncoder()
 |  >>> le.fit(["paris", "paris", "tokyo", "amsterdam"])
 |  LabelEncoder()
 |  >>> list(le.classes_)
 |  [np.str_('amsterdam'), np.str_('paris'), np.str_('tokyo')]
 |  >>> le.transform(["tokyo", "tokyo", "paris"])
 |  array([2, 2, 1]...)
 |  >>> list(le.inverse_transform([2, 2, 1]))
 |  [np.str_('tokyo'), np.str_('tokyo'), np.str_('paris')]
 |
 |  Method resolution order:
 |      LabelEncoder
 |      sklearn.base.TransformerMixin
 |      sklearn.utils._set_output._SetOutputMixin
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._estimator_html_repr._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __sklearn_tags__(self)
 |
 |  fit(self, y)
 |      Fit label encoder.
 |
 |      Parameters
 |      ----------
 |      y : array-like of shape (n_samples,)
 |          Target values.
 |
 |      Returns
 |      -------
 |      self : returns an instance of self.
 |          Fitted label encoder.
 |
 |  fit_transform(self, y)
 |      Fit label encoder and return encoded labels.
 |
 |      Parameters
 |      ----------
 |      y : array-like of shape (n_samples,)
 |          Target values.
 |
 |      Returns
 |      -------
 |      y : array-like of shape (n_samples,)
 |          Encoded labels.
 |
 |  inverse_transform(self, y)
 |      Transform labels back to original encoding.
 |
 |      Parameters
 |      ----------
 |      y : array-like of shape (n_samples,)
 |          Target values.
 |
 |      Returns
 |      -------
 |      y : ndarray of shape (n_samples,)
 |          Original encoding.
 |
 |  transform(self, y)
 |      Transform labels to normalized encoding.
 |
 |      Parameters
 |      ----------
 |      y : array-like of shape (n_samples,)
 |          Target values.
 |
 |      Returns
 |      -------
 |      y : array-like of shape (n_samples,)
 |          Labels as normalized encodings.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.utils._set_output._SetOutputMixin:
 |
 |  set_output(self, *, transform=None)
 |      Set output container.
 |
 |      See :ref:`sphx_glr_auto_examples_miscellaneous_plot_set_output.py`
 |      for an example on how to use the API.
 |
 |      Parameters
 |      ----------
 |      transform : {"default", "pandas", "polars"}, default=None
 |          Configure output of `transform` and `fit_transform`.
 |
 |          - `"default"`: Default output format of a transformer
 |          - `"pandas"`: DataFrame output
 |          - `"polars"`: Polars output
 |          - `None`: Transform configuration is unchanged
 |
 |          .. versionadded:: 1.4
 |              `"polars"` option was added.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from sklearn.utils._set_output._SetOutputMixin:
 |
 |  __init_subclass__(auto_wrap_output_keys=('transform',), **kwargs)
 |      Set the ``set_{method}_request`` methods.
 |
 |      This uses PEP-487 [1]_ to set the ``set_{method}_request`` methods. It
 |      looks for the information available in the set default values which are
 |      set using ``__metadata_request__*`` class attributes, or inferred
 |      from method signatures.
 |
 |      The ``__metadata_request__*`` class attributes are used when a method
 |      does not explicitly accept a metadata through its arguments or if the
 |      developer would like to specify a request value for those metadata
 |      which are different from the default ``None``.
 |
 |      References
 |      ----------
 |      .. [1] https://www.python.org/dev/peps/pep-0487
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.utils._set_output._SetOutputMixin:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |      Helper for pickle.
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  __sklearn_clone__(self)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : dict
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
 |      parameters of the form ``<component>__<parameter>`` so that it's
 |      possible to update each component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
 |
 |  get_metadata_routing(self)
 |      Get metadata routing of this object.
 |
 |      Please check :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      Returns
 |      -------
 |      routing : MetadataRequest
 |          A :class:`~sklearn.utils.metadata_routing.MetadataRequest` encapsulating
 |          routing information.

In [35]:
le.fit_transform(["deven", "paris"])

array([0, 1])

In [31]:
le.fit_transform(cat)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
le.transform(["paris"])

array([1])

In [44]:
y = df["Attrition"]
y = y.apply(lambda x: 1 if x == "Yes" else 0)

In [45]:
df_final = pd.concat([categorical, df_num], axis=1)
df_final.head(10)

,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Research & Development,Department_Sales,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,Gender_Male,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0,1,0,1,1,0,0,0,0,0,...,1,80,0,8,0,1,6,4,0,5
1,1,0,1,0,1,0,0,0,0,1,...,4,80,1,10,3,3,10,7,1,7
2,0,1,1,0,0,0,0,1,0,1,...,2,80,0,7,3,3,0,0,0,0
3,1,0,1,0,1,0,0,0,0,0,...,3,80,0,8,3,3,8,7,3,0
4,0,1,1,0,0,0,1,0,0,1,...,4,80,1,6,3,3,2,2,2,2
5,1,0,1,0,1,0,0,0,0,1,...,3,80,0,8,2,2,7,7,3,6
6,0,1,1,0,0,0,1,0,0,0,...,1,80,3,12,3,2,1,0,0,0
7,0,1,1,0,1,0,0,0,0,1,...,2,80,1,1,2,3,1,0,0,0
8,1,0,1,0,1,0,0,0,0,1,...,2,80,0,10,2,3,9,7,1,8
9,0,1,1,0,0,0,1,0,0,1,...,2,80,2,17,3,2,7,7,7,7

In [46]:
train, test, target_train, target_test = train_test_split(
    df_final, y, train_size=0.75, random_state=0
);

In [48]:
train.shape

(1102, 47)

In [49]:
test.shape

(368, 47)

In [50]:
target_train.shape

(1102,)

In [51]:
gb.fit(train, target_train)

GradientBoostingClassifier(random_state=0)

In [53]:
gb_pred = gb.predict(test)

In [54]:
gb.score(train, target_train)

0.9627949183303085

In [55]:
gb.score(test, target_test)

0.8858695652173914

In [56]:
gb_prob = gb.predict_proba(test)

In [57]:
gb_prob

array([[0.93565701, 0.06434299],
       [0.96798638, 0.03201362],
       [0.8747258 , 0.1252742 ],
       [0.95525024, 0.04474976],
       [0.10720351, 0.89279649],
       [0.67487367, 0.32512633],
       [0.59570909, 0.40429091],
       [0.91183264, 0.08816736],
       [0.96662071, 0.03337929],
       [0.90249265, 0.09750735],
       [0.93460885, 0.06539115],
       [0.90269076, 0.09730924],
       [0.9732961 , 0.0267039 ],
       [0.26854533, 0.73145467],
       [0.94012005, 0.05987995],
       [0.98792486, 0.01207514],
       [0.94597233, 0.05402767],
       [0.93071641, 0.06928359],
       [0.93537954, 0.06462046],
       [0.92440318, 0.07559682],
       [0.60995072, 0.39004928],
       [0.95078893, 0.04921107],
       [0.96838558, 0.03161442],
       [0.97980593, 0.02019407],
       [0.41611433, 0.58388567],
       [0.74410279, 0.25589721],
       [0.95968266, 0.04031734],
       [0.97096781, 0.02903219],
       [0.28238165, 0.71761835],
       [0.96050297, 0.03949703],
       [0.96788918, 0.03211082],
       [0.97179163, 0.02820837],
       [0.84067426, 0.15932574],
       [0.94544868, 0.05455132],
       [0.90226687, 0.09773313],
       [0.95400726, 0.04599274],
       [0.94074953, 0.05925047],
       [0.96976661, 0.03023339],
       [0.96377331, 0.03622669],
       [0.89663379, 0.10336621],
       [0.93536679, 0.06463321],
       [0.98332106, 0.01667894],
       [0.98410881, 0.01589119],
       [0.95350657, 0.04649343],
       [0.97974206, 0.02025794],
       [0.34730286, 0.65269714],
       [0.734326  , 0.265674  ],
       [0.98679715, 0.01320285],
       [0.06906253, 0.93093747],
       [0.55981352, 0.44018648],
       [0.89640601, 0.10359399],
       [0.38123614, 0.61876386],
       [0.89958212, 0.10041788],
       [0.94235559, 0.05764441],
       [0.34754774, 0.65245226],
       [0.90899903, 0.09100097],
       [0.98738149, 0.01261851],
       [0.91375204, 0.08624796],
       [0.98264537, 0.01735463],
       [0.52230632, 0.47769368],
       [0.98328889, 0.01671111],
       [0.89068306, 0.10931694],
       [0.7939958 , 0.2060042 ],
       [0.96160037, 0.03839963],
       [0.52431858, 0.47568142],
       [0.9503015 , 0.0496985 ],
       [0.83937298, 0.16062702],
       [0.92139347, 0.07860653],
       [0.93901462, 0.06098538],
       [0.96053499, 0.03946501],
       [0.94615183, 0.05384817],
       [0.64679842, 0.35320158],
       [0.87105711, 0.12894289],
       [0.97454904, 0.02545096],
       [0.92738959, 0.07261041],
       [0.95838134, 0.04161866],
       [0.97174608, 0.02825392],
       [0.95133715, 0.04866285],
       [0.39024856, 0.60975144],
       [0.9904903 , 0.0095097 ],
       [0.98936656, 0.01063344],
       [0.98239587, 0.01760413],
       [0.92623985, 0.07376015],
       [0.91732473, 0.08267527],
       [0.95262634, 0.04737366],
       [0.9415688 , 0.0584312 ],
       [0.97534841, 0.02465159],
       [0.73176455, 0.26823545],
       [0.93280941, 0.06719059],
       [0.9641662 , 0.0358338 ],
       [0.36710753, 0.63289247],
       [0.92399661, 0.07600339],
       [0.91536333, 0.08463667],
       [0.72337756, 0.27662244],
       [0.9812496 , 0.0187504 ],
       [0.97427402, 0.02572598],
       [0.91268371, 0.08731629],
       [0.58076508, 0.41923492],
       [0.9750204 , 0.0249796 ],
       [0.94512062, 0.05487938],
       [0.70844125, 0.29155875],
       [0.57864009, 0.42135991],
       [0.39627141, 0.60372859],
       [0.96413762, 0.03586238],
       [0.96762482, 0.03237518],
       [0.97079132, 0.02920868],
       [0.93032305, 0.06967695],
       [0.60862764, 0.39137236],
       [0.79467937, 0.20532063],
       [0.90655189, 0.09344811],
       [0.68049797, 0.31950203],
       [0.83654554, 0.16345446],
       [0.97530366, 0.02469634],
       [0.97583913, 0.02416087],
       [0.95294397, 0.04705603],
       [0.93197515, 0.06802485],
       [0.93041016, 0.06958984],
       [0.90769537, 0.09230463],
       [0.98557938, 0.01442062],
       [0.98362227, 0.01637773],
       [0.96164286, 0.03835714],
       [0.96982133, 0.03017867],
       [0.96385867, 0.03614133],
       [0.0756317 , 0.9243683 ],
       [0.86954363, 0.13045637],
       [0.97879038, 0.02120962],
       [0.9855657 , 0.0144343 ],
       [0.9119507 , 0.0880493 ],
       [0.92456398, 0.07543602],
       [0.94858026, 0.05141974],
       [0.9872703 , 0.0127297 ],
       [0.47404527, 0.52595473],
       [0.38559002, 0.61440998],
       [0.52259566, 0.47740434],
       [0.91229426, 0.08770574],
       [0.54758814, 0.45241186],
       [0.5725848 , 0.4274152 ],
       [0.94456459, 0.05543541],
       [0.89958406, 0.10041594],
       [0.96160709, 0.03839291],
       [0.97416864, 0.02583136],
       [0.90863907, 0.09136093],
       [0.93883612, 0.06116388],
       [0.88314526, 0.11685474],
       [0.86328253, 0.13671747],
       [0.97114495, 0.02885505],
       [0.85196219, 0.14803781],
       [0.96787343, 0.03212657],
       [0.9403826 , 0.0596174 ],
       [0.9763716 , 0.0236284 ],
       [0.95952635, 0.04047365],
       [0.89956293, 0.10043707],
       [0.93535396, 0.06464604],
       [0.49291552, 0.50708448],
       [0.95151238, 0.04848762],
       [0.87336404, 0.12663596],
       [0.98965756, 0.01034244],
       [0.66373239, 0.33626761],
       [0.95835072, 0.04164928],
       [0.97237048, 0.02762952],
       [0.80268202, 0.19731798],
       [0.98874212, 0.01125788],
       [0.73701232, 0.26298768],
       [0.06669672, 0.93330328],
       [0.97304447, 0.02695553],
       [0.88136404, 0.11863596],
       [0.84825765, 0.15174235],
       [0.97589194, 0.02410806],
       [0.97437554, 0.02562446],
       [0.98202917, 0.01797083],
       [0.95854613, 0.04145387],
       [0.94636793, 0.05363207],
       [0.95741313, 0.04258687],
       [0.75088252, 0.24911748],
       [0.97954369, 0.02045631],
       [0.89784585, 0.10215415],
       [0.94707848, 0.05292152],
       [0.67584464, 0.32415536],
       [0.8703449 , 0.1296551 ],
       [0.92119494, 0.07880506],
       [0.9637236 , 0.0362764 ],
       [0.97599002, 0.02400998],
       [0.98832058, 0.01167942],
       [0.40930337, 0.59069663],
       [0.96781548, 0.03218452],
       [0.98375234, 0.01624766],
       [0.67955053, 0.32044947],
       [0.93801489, 0.06198511],
       [0.93466502, 0.06533498],
       [0.89706691, 0.10293309],
       [0.84354345, 0.15645655],
       [0.43492855, 0.56507145],
       [0.90723306, 0.09276694],
       [0.98643898, 0.01356102],
       [0.96533722, 0.03466278],
       [0.90149835, 0.09850165],
       [0.97055671, 0.02944329],
       [0.96266541, 0.03733459],
       [0.15929505, 0.84070495],
       [0.94441642, 0.05558358],
       [0.79413926, 0.20586074],
       [0.93425195, 0.06574805],
       [0.82814431, 0.17185569],
       [0.97975928, 0.02024072],
       [0.93035   , 0.06965   ],
       [0.87771066, 0.12228934],
       [0.75062483, 0.24937517],
       [0.98257861, 0.01742139],
       [0.93927631, 0.06072369],
       [0.97592144, 0.02407856],
       [0.9458585 , 0.0541415 ],
       [0.96629151, 0.03370849],
       [0.84589703, 0.15410297],
       [0.90637916, 0.09362084],
       [0.96269362, 0.03730638],
       [0.97607113, 0.02392887],
       [0.98028889, 0.01971111],
       [0.89488696, 0.10511304],
       [0.96990472, 0.03009528],
       [0.56555111, 0.43444889],
       [0.67931907, 0.32068093],
       [0.54334932, 0.45665068],
       [0.55543556, 0.44456444],
       [0.47587682, 0.52412318],
       [0.77028917, 0.22971083],
       [0.97308401, 0.02691599],
       [0.9423179 , 0.0576821 ],
       [0.65296202, 0.34703798],
       [0.16542205, 0.83457795],
       [0.92976288, 0.07023712],
       [0.98313253, 0.01686747],
       [0.58095626, 0.41904374],
       [0.96590383, 0.03409617],
       [0.9446239 , 0.0553761 ],
       [0.96543408, 0.03456592],
       [0.61090121, 0.38909879],
       [0.83374997, 0.16625003],
       [0.98739299, 0.01260701],
       [0.88972367, 0.11027633],
       [0.98618656, 0.01381344],
       [0.79412282, 0.20587718],
       [0.80828789, 0.19171211],
       [0.96566286, 0.03433714],
       [0.95749394, 0.04250606],
       [0.90077865, 0.09922135],
       [0.95847997, 0.04152003],
       [0.97360924, 0.02639076],
       [0.70740211, 0.29259789],
       [0.91080278, 0.08919722],
       [0.91445033, 0.08554967],
       [0.90527902, 0.09472098],
       [0.80980869, 0.19019131],
       [0.65201696, 0.34798304],
       [0.95770402, 0.04229598],
       [0.81255845, 0.18744155],
       [0.9094101 , 0.0905899 ],
       [0.9725034 , 0.0274966 ],
       [0.41743531, 0.58256469],
       [0.83519483, 0.16480517],
       [0.47639829, 0.52360171],
       [0.86141498, 0.13858502],
       [0.9637103 , 0.0362897 ],
       [0.91918814, 0.08081186],
       [0.93265125, 0.06734875],
       [0.86471598, 0.13528402],
       [0.77026641, 0.22973359],
       [0.97422721, 0.02577279],
       [0.72280262, 0.27719738],
       [0.88271462, 0.11728538],
       [0.97553946, 0.02446054],
       [0.95224078, 0.04775922],
       [0.9679991 , 0.0320009 ],
       [0.91957768, 0.08042232],
       [0.95500254, 0.04499746],
       [0.97067222, 0.02932778],
       [0.98486846, 0.01513154],
       [0.93458819, 0.06541181],
       [0.77866988, 0.22133012],
       [0.92408587, 0.07591413],
       [0.68265748, 0.31734252],
       [0.77628948, 0.22371052],
       [0.9667577 , 0.0332423 ],
       [0.91257487, 0.08742513],
       [0.80355051, 0.19644949],
       [0.89981858, 0.10018142],
       [0.86615199, 0.13384801],
       [0.9892892 , 0.0107108 ],
       [0.92522834, 0.07477166],
       [0.96782929, 0.03217071],
       [0.97892489, 0.02107511],
       [0.94646886, 0.05353114],
       [0.67063616, 0.32936384],
       [0.96369391, 0.03630609],
       [0.95216665, 0.04783335],
       [0.93055739, 0.06944261],
       [0.97189633, 0.02810367],
       [0.91364384, 0.08635616],
       [0.88100739, 0.11899261],
       [0.02117899, 0.97882101],
       [0.97908154, 0.02091846],
       [0.92115816, 0.07884184],
       [0.90780413, 0.09219587],
       [0.72950427, 0.27049573],
       [0.8951737 , 0.1048263 ],
       [0.97665344, 0.02334656],
       [0.95659654, 0.04340346],
       [0.57242172, 0.42757828],
       [0.91330085, 0.08669915],
       [0.98054014, 0.01945986],
       [0.96919576, 0.03080424],
       [0.81865074, 0.18134926],
       [0.95688637, 0.04311363],
       [0.92797594, 0.07202406],
       [0.95154874, 0.04845126],
       [0.86546377, 0.13453623],
       [0.9248735 , 0.0751265 ],
       [0.87074583, 0.12925417],
       [0.91926061, 0.08073939],
       [0.65740748, 0.34259252],
       [0.95915564, 0.04084436],
       [0.46976691, 0.53023309],
       [0.96773721, 0.03226279],
       [0.8891206 , 0.1108794 ],
       [0.80946892, 0.19053108],
       [0.95917778, 0.04082222],
       [0.97471494, 0.02528506],
       [0.75506241, 0.24493759],
       [0.77249679, 0.22750321],
       [0.98942762, 0.01057238],
       [0.96029681, 0.03970319],
       [0.9613668 , 0.0386332 ],
       [0.84705065, 0.15294935],
       [0.88180324, 0.11819676],
       [0.1788453 , 0.8211547 ],
       [0.7830227 , 0.2169773 ],
       [0.88373558, 0.11626442],
       [0.94148827, 0.05851173],
       [0.97666987, 0.02333013],
       [0.9729796 , 0.0270204 ],
       [0.93972698, 0.06027302],
       [0.8799975 , 0.1200025 ],
       [0.5158928 , 0.4841072 ],
       [0.93015874, 0.06984126],
       [0.92408396, 0.07591604],
       [0.92874476, 0.07125524],
       [0.94676555, 0.05323445],
       [0.95032097, 0.04967903],
       [0.62347815, 0.37652185],
       [0.96256745, 0.03743255],
       [0.73724028, 0.26275972],
       [0.98616628, 0.01383372],
       [0.87827909, 0.12172091],
       [0.95115068, 0.04884932],
       [0.93096409, 0.06903591],
       [0.94330826, 0.05669174],
       [0.96493713, 0.03506287],
       [0.97654677, 0.02345323],
       [0.95164362, 0.04835638],
       [0.97444394, 0.02555606],
       [0.55539781, 0.44460219],
       [0.98697199, 0.01302801],
       [0.97270227, 0.02729773],
       [0.95231731, 0.04768269],
       [0.93926764, 0.06073236],
       [0.95959262, 0.04040738],
       [0.89693904, 0.10306096],
       [0.96830878, 0.03169122],
       [0.71768736, 0.28231264]])

In [58]:
accuracy_score(gb_pred, target_test)

0.8858695652173914

In [63]:
trace = go.Scatter(
    y=gb.feature_importances_,
    x=df_final.columns.values,
    mode="markers",
    marker=dict(
        sizemode="diameter",
        sizeref=1.3,
        size=12,
        color=gb.feature_importances_,
        colorscale="Portland",
        showscale=True,
    ),
    text=df_final.columns.values,
)
data = [trace]

layout = go.Layout(
    autosize=True,
    title="GBM Model Feature Importance",
    hovermode="closest",
    xaxis=dict(ticklen=5, showgrid=False, zeroline=False, showline=False),
    yaxis=dict(
        title="Feature Importance",
        showgrid=False,
        zeroline=False,
        ticklen=5,
        gridwidth=2,
    ),
    showlegend=False,
)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename="scatter")

np.int64(0)