In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# print()

In [4]:
from ucimlrepo import fetch_ucirepo

online_news_popularity = fetch_ucirepo(id=332)
X = online_news_popularity.data.features
y = online_news_popularity.data.targets

# metadata
online_news_popularity.metadata.variable_info

# variable information

In [6]:
type(online_news_popularity)

ucimlrepo.dotdict.dotdict

In [7]:
for key, value in online_news_popularity.data.items():
    print(key, type(value))

ids <class 'pandas.core.frame.DataFrame'>
features <class 'pandas.core.frame.DataFrame'>
targets <class 'pandas.core.frame.DataFrame'>
original <class 'pandas.core.frame.DataFrame'>
headers <class 'pandas.core.indexes.base.Index'>

In [8]:
online_news_popularity.data.features[:20]

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,avg_positive_polarity,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity
0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,0.0,4.680365,...,0.378636,0.100000,0.7,-0.350000,-0.6000,-0.200000,0.500000,-0.187500,0.000000,0.187500
1,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,0.0,4.913725,...,0.286915,0.033333,0.7,-0.118750,-0.1250,-0.100000,0.000000,0.000000,0.500000,0.000000
2,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,0.0,4.393365,...,0.495833,0.100000,1.0,-0.466667,-0.8000,-0.133333,0.000000,0.000000,0.500000,0.000000
3,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,0.0,4.404896,...,0.385965,0.136364,0.8,-0.369697,-0.6000,-0.166667,0.000000,0.000000,0.500000,0.000000
4,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,0.0,4.682836,...,0.411127,0.033333,1.0,-0.220192,-0.5000,-0.050000,0.454545,0.136364,0.045455,0.136364
5,10.0,370.0,0.559889,1.0,0.698198,2.0,2.0,0.0,0.0,4.359459,...,0.350610,0.136364,0.6,-0.195000,-0.4000,-0.100000,0.642857,0.214286,0.142857,0.214286
6,8.0,960.0,0.418163,1.0,0.549834,21.0,20.0,20.0,0.0,4.654167,...,0.402039,0.100000,1.0,-0.224479,-0.5000,-0.050000,0.000000,0.000000,0.500000,0.000000
7,12.0,989.0,0.433574,1.0,0.572108,20.0,20.0,20.0,0.0,4.617796,...,0.427720,0.100000,1.0,-0.242778,-0.5000,-0.050000,1.000000,0.500000,0.500000,0.500000
8,11.0,97.0,0.670103,1.0,0.836735,2.0,0.0,0.0,0.0,4.855670,...,0.566667,0.400000,0.8,-0.125000,-0.1250,-0.125000,0.125000,0.000000,0.375000,0.000000
9,10.0,231.0,0.636364,1.0,0.797101,4.0,1.0,1.0,1.0,5.090909,...,0.298413,0.100000,0.5,-0.238095,-0.5000,-0.100000,0.000000,0.000000,0.500000,0.000000
10,9.0,1248.0,0.490050,1.0,0.731638,11.0,0.0,1.0,0.0,4.617788,...,0.404480,0.100000,1.0,-0.415064,-1.0000,-0.100000,0.000000,0.000000,0.500000,0.000000
11,10.0,187.0,0.666667,1.0,0.800000,7.0,0.0,1.0,0.0,4.657754,...,0.435000,0.200000,0.7,-0.262500,-0.4000,-0.125000,0.000000,0.000000,0.500000,0.000000
12,9.0,274.0,0.609195,1.0,0.707602,18.0,2.0,11.0,0.0,4.233577,...,0.375510,0.200000,0.7,-0.310417,-0.6000,-0.050000,1.000000,-1.000000,0.500000,1.000000
13,9.0,285.0,0.744186,1.0,0.841530,4.0,2.0,0.0,21.0,4.343860,...,0.457500,0.160000,1.0,-0.337889,-0.7000,-0.100000,1.000000,-1.000000,0.500000,1.000000
14,8.0,259.0,0.562753,1.0,0.644444,19.0,3.0,9.0,0.0,5.023166,...,0.249091,0.136364,0.5,-0.138690,-0.1875,-0.050000,0.750000,0.550000,0.250000,0.550000
15,12.0,682.0,0.459542,1.0,0.634961,10.0,0.0,1.0,0.0,4.620235,...,0.343070,0.050000,0.6,-0.220150,-0.6000,-0.050000,0.750000,-0.250000,0.250000,0.250000
16,8.0,1118.0,0.512397,1.0,0.709770,26.0,18.0,12.0,1.0,4.703936,...,0.504529,0.100000,1.0,-0.401437,-1.0000,-0.050000,0.566667,-0.100000,0.066667,0.100000
17,8.0,397.0,0.624679,1.0,0.805668,11.0,0.0,1.0,0.0,5.445844,...,0.381847,0.033333,1.0,-0.144643,-0.2000,-0.100000,0.000000,0.000000,0.500000,0.000000
18,11.0,103.0,0.689320,1.0,0.806452,3.0,1.0,1.0,0.0,4.844660,...,0.277778,0.033333,0.5,-0.125000,-0.1250,-0.125000,0.857143,-0.714286,0.357143,0.714286
19,8.0,1207.0,0.410579,1.0,0.548969,24.0,24.0,42.0,0.0,4.716653,...,0.426568,0.100000,1.0,-0.226786,-0.5000,-0.050000,0.500000,0.000000,0.000000,0.000000

In [9]:
online_news_popularity.data.targets[:20]

    shares
0      593
1      711
2     1500
3     1200
4      505
5      855
6      556
7      891
8     3600
9      710
10    2200
11    1900
12     823
13   10000
14     761
15    1600
16   13600
17    3100
18    5700
19   17100

In [10]:
headers = online_news_popularity.data.headers

In [11]:
headers

Index(['url', ' timedelta', ' n_tokens_title', ' n_tokens_content',
       ' n_unique_tokens', ' n_non_stop_words', ' n_non_stop_unique_tokens',
       ' num_hrefs', ' num_self_hrefs', ' num_imgs', ' num_videos',
       ' average_token_length', ' num_keywords', ' data_channel_is_lifestyle',
       ' data_channel_is_entertainment', ' data_channel_is_bus',
       ' data_channel_is_socmed', ' data_channel_is_tech',
       ' data_channel_is_world', ' kw_min_min', ' kw_max_min', ' kw_avg_min',
       ' kw_min_max', ' kw_max_max', ' kw_avg_max', ' kw_min_avg',
       ' kw_max_avg', ' kw_avg_avg', ' self_reference_min_shares',
       ' self_reference_max_shares', ' self_reference_avg_sharess',
       ' weekday_is_monday', ' weekday_is_tuesday', ' weekday_is_wednesday',
       ' weekday_is_thursday', ' weekday_is_friday', ' weekday_is_saturday',
       ' weekday_is_sunday', ' is_weekend', ' LDA_00', ' LDA_01', ' LDA_02',
       ' LDA_03', ' LDA_04', ' global_subjectivity',
       ' global_sentiment_polarity', ' global_rate_positive_words',
       ' global_rate_negative_words', ' rate_positive_words',
       ' rate_negative_words', ' avg_positive_polarity',
       ' min_positive_polarity', ' max_positive_polarity',
       ' avg_negative_polarity', ' min_negative_polarity',
       ' max_negative_polarity', ' title_subjectivity',
       ' title_sentiment_polarity', ' abs_title_subjectivity',
       ' abs_title_sentiment_polarity', ' shares'],
      dtype='object')

In [12]:
print(online_news_popularity.variables["name"])

0                               url
1                         timedelta
2                    n_tokens_title
3                  n_tokens_content
4                   n_unique_tokens
                  ...
56               title_subjectivity
57         title_sentiment_polarity
58           abs_title_subjectivity
59     abs_title_sentiment_polarity
60                           shares
Name: name, Length: 61, dtype: object

In [13]:
popularity = pd.read_csv("../../data/popularity.csv")

In [14]:
popularity

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,...,0.100000,0.70,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,...,0.033333,0.70,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,...,0.100000,1.00,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,...,0.136364,0.80,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,...,0.033333,1.00,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39639,http://mashable.com/2014/12/27/samsung-app-aut...,8.0,11.0,346.0,0.529052,1.0,0.684783,9.0,7.0,1.0,...,0.100000,0.75,-0.260000,-0.500,-0.125000,0.100000,0.000000,0.400000,0.000000,1800
39640,http://mashable.com/2014/12/27/seth-rogen-jame...,8.0,12.0,328.0,0.696296,1.0,0.885057,9.0,7.0,3.0,...,0.136364,0.70,-0.211111,-0.400,-0.100000,0.300000,1.000000,0.200000,1.000000,1900
39641,http://mashable.com/2014/12/27/son-pays-off-mo...,8.0,10.0,442.0,0.516355,1.0,0.644128,24.0,1.0,12.0,...,0.136364,0.50,-0.356439,-0.800,-0.166667,0.454545,0.136364,0.045455,0.136364,1900
39642,http://mashable.com/2014/12/27/ukraine-blasts/,8.0,6.0,682.0,0.539493,1.0,0.692661,10.0,1.0,1.0,...,0.062500,0.50,-0.205246,-0.500,-0.012500,0.000000,0.000000,0.500000,0.000000,1100
39643,http://mashable.com/2014/12/27/youtube-channel...,8.0,10.0,157.0,0.701987,1.0,0.846154,1.0,1.0,0.0,...,0.100000,0.50,-0.200000,-0.200,-0.200000,0.333333,0.250000,0.166667,0.250000,1300

In [ ]:
popularity[" num_keywords"].mode()

0    7.0
Name:  num_keywords, dtype: float64

In [ ]:
np.mean(popularity[" shares"])

3395.3801836343455

In [ ]:
np.median(popularity[" shares"])

1400.0

In [ ]:
# sns.boxplot(popularity,y=' shares',hue='url')

Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x112ab9370>>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ML_AI/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 775, in _clean_thread_parent_frames
    def _clean_thread_parent_frames(

KeyboardInterrupt: