## Housing Tensorflow from scratch

In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.linear_model import LinearRegression

from utilties.utils import display_info

In [7]:
df = pd.read_csv("Housing.csv")

In [8]:
display_info(df)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
542,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
543,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
544,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
545,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

<class 'pandas.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             546 non-null    int64
 1   area              546 non-null    int64
 2   bedrooms          546 non-null    str
 3   bathrooms         546 non-null    int64
 4   stories           546 non-null    int64
 5   mainroad          546 non-null    str
 6   guestroom         546 non-null    str
 7   basement          546 non-null    str
 8   hotwaterheating   546 non-null    str
 9   airconditioning   546 non-null    str
 10  parking           546 non-null    int64
 11  prefarea          546 non-null    str
 12  furnishingstatus  546 non-null    str
dtypes: int64(5), str(8)
memory usage: 55.6 KB

Empty DataFrame
Columns: []
Index: []

In [69]:
import sklearn
from sklearn.model_selection import train_test_split

In [ ]:
df

In [70]:
df_train, df_test = train_test_split(df, test_size=0.3, random_state=42)

In [71]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score

In [72]:
scaler = StandardScaler()

In [79]:
# Apply scaler() to all the columns except the 'yes-no' and 'dummy' variables
num_vars = ["area", "bedrooms", "bathrooms", "price"]


df_train[num_vars].head()

     area  bedrooms  bathrooms    price
126  7160         3          1  5880000
363  3584         2          1  3710000
370  4280         2          1  3640000
31   7000         3          1  8400000
113  9620         3          1  6083000

In [81]:
df_train[num_vars] = scaler.fit_transform(df_train[num_vars])
df_test[num_vars] = scaler.transform(df_test[num_vars])

In [83]:
X_train = df_train[["area", "bedrooms", "bathrooms"]]
y_train = df_train["price"]

In [98]:
X_train

         area  bedrooms  bathrooms
126  0.934301  0.055861  -0.553238
363 -0.710246 -1.274325  -0.553238
370 -0.390167 -1.274325  -0.553238
31   0.860719  0.055861  -0.553238
113  2.065617  0.055861  -0.553238
..        ...       ...        ...
71   0.400835  1.386046   1.554599
106  0.147898  1.386046   1.554599
270 -0.288992  0.055861   1.554599
435 -0.500539 -1.274325  -0.553238
102  0.170892  0.055861   1.554599

[381 rows x 3 columns]

In [225]:
X_test = df_test[["area", "bedrooms", "bathrooms"]]
y_test = df_test["price"]

In [226]:
y_test

316   -0.396292
77     1.064965
360   -0.593759
90     0.946485
493   -1.107174
         ...
395   -0.712240
425   -0.791226
195    0.117123
452   -0.909707
154    0.433070
Name: price, Length: 164, dtype: float64

In [85]:
lm = LinearRegression()

In [101]:
X_test_new = X_test[X_test.columns]

In [102]:
X_test_new

         area  bedrooms  bathrooms
316  0.354846  1.386046   1.554599
77   0.630777  0.055861   1.554599
360 -0.500539 -1.274325  -0.553238
90  -0.059050  0.055861  -0.553238
493 -0.537330  0.055861  -0.553238
..        ...       ...        ...
395 -0.702888  4.046417  -0.553238
425 -0.893740 -1.274325  -0.553238
195 -0.330382  1.386046   3.662437
452  1.780488  0.055861  -0.553238
154 -0.679894  0.055861   1.554599

[164 rows x 3 columns]

In [104]:
lm.fit(X_train, y_train)

LinearRegression()

In [108]:
X_test

         area  bedrooms  bathrooms
316  0.354846  1.386046   1.554599
77   0.630777  0.055861   1.554599
360 -0.500539 -1.274325  -0.553238
90  -0.059050  0.055861  -0.553238
493 -0.537330  0.055861  -0.553238
..        ...       ...        ...
395 -0.702888  4.046417  -0.553238
425 -0.893740 -1.274325  -0.553238
195 -0.330382  1.386046   3.662437
452  1.780488  0.055861  -0.553238
154 -0.679894  0.055861   1.554599

[164 rows x 3 columns]

In [109]:
y_test_class = lm.predict(X_test)

In [113]:
y_test.values.shape

(164,)

In [114]:
y_test_pred.shape

(164,)

In [ ]:
sklearn.metrics.accuracy_score(y_true=y_test, y_pred=y_test_pred)

## Part 4: Forward pass matrix multiplication


This network can be described as follows:

- Input vector = $X = (x1,x2)$
- Weight Matrix (hidden layer) = $$W^1 = \begin{bmatrix}
w^1_{11}&&w^1_{12}\\
w^1_{21}&&w^1_{22}\\
\end{bmatrix}
$$
*note the subscripts are being mapped to weights in the figure

- Bias/offset Matrix (hidden layer) = $$
B^1_0 = \begin{bmatrix}
b^1_{1}\\
b^1_{2}\\
\end{bmatrix}
$$

Now the forward pass for the hidden layer can be described as

$$W^1 \times X^T + B^1_0= Z^1 = \begin{bmatrix}
z^1_{1}\\
z^1_{2}\\
\end{bmatrix}
$$

Applying the activation function $f$ over the matrix $Z$ will complete the forward pass.

$$f(W^1 \times X^T + B^1_0)= f(Z^1) = f(\begin{bmatrix}
z^1_{1}\\
z^1_{2}\\
\end{bmatrix}) =
\begin{bmatrix}
f(z^1_{1})\\
f(z^1_{2})\\
\end{bmatrix}
=
\begin{bmatrix}
h^1_1\\
h^1_2\\
\end{bmatrix}
= H^1
$$

For the output layer:

- The weight matrix is $$W^2 = \begin{bmatrix}
w^2_{11}&&w^2_{12}\\
\end{bmatrix}
$$

- The bias/offset matrix is $$B^2_0 = \begin{bmatrix}
b^2_{1}\\
\end{bmatrix}
$$

Now the forward pass can be written as:


$$ B_0^2+W^2 \times H^1$$

In [117]:
X_train.shape[-1]

3

In [227]:
from tensorflow import keras

In [228]:
norm_layer = keras.layers.Normalization(axis=-1)

In [229]:
model = keras.Sequential()
model.add(keras.layers.Input(shape=(X_train.shape[-1],)))
model.add(keras.layers.Dense(units=64, activation="relu"))
model.add(norm_layer)
model.add(keras.layers.Dense(units=64, activation="relu"))
model.add(keras.layers.Dense(1))

In [230]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ normalization_1 (Normalization) │ (None, 64)             │           129 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,610 (18.01 KB)

 Trainable params: 4,481 (17.50 KB)

 Non-trainable params: 129 (520.00 B)

In [231]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss=tf.losses.MSE,
    metrics=[tf.losses.MAE],
)

In [233]:
history = model.fit(
    X_train.values,
    y_train.values,
    epochs=60,
    batch_size=32,
    validation_data=(X_test_new.values, y_test.values),
    verbose=1,
)

Epoch 1/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0421 - mean_absolute_error: 0.8004 - val_loss: 1.3973 - val_mean_absolute_error: 0.9413
Epoch 2/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9929 - mean_absolute_error: 0.7786 - val_loss: 1.3415 - val_mean_absolute_error: 0.9200
Epoch 3/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9471 - mean_absolute_error: 0.7578 - val_loss: 1.2897 - val_mean_absolute_error: 0.8994
Epoch 4/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9034 - mean_absolute_error: 0.7374 - val_loss: 1.2418 - val_mean_absolute_error: 0.8799
Epoch 5/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.8660 - mean_absolute_error: 0.7187 - val_loss: 1.1956 - val_mean_absolute_error: 0.8605
Epoch 6/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.8285 - mean_absolute_error: 0.7005 - val_loss: 1.1544 - val_mean_absolute_error: 0.8428
Epoch 7/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7948 - mean_absolute_error: 0.6831 - val_loss: 1.1161 - val_mean_absolute_error: 0.8258
Epoch 8/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7651 - mean_absolute_error: 0.6676 - val_loss: 1.0789 - val_mean_absolute_error: 0.8092
Epoch 9/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7341 - mean_absolute_error: 0.6520 - val_loss: 1.0478 - val_mean_absolute_error: 0.7946
Epoch 10/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7089 - mean_absolute_error: 0.6385 - val_loss: 1.0170 - val_mean_absolute_error: 0.7798
Epoch 11/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6853 - mean_absolute_error: 0.6256 - val_loss: 0.9878 - val_mean_absolute_error: 0.7656
Epoch 12/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6629 - mean_absolute_error: 0.6131 - val_loss: 0.9613 - val_mean_absolute_error: 0.7529
Epoch 13/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6434 - mean_absolute_error: 0.6028 - val_loss: 0.9368 - val_mean_absolute_error: 0.7418
Epoch 14/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6237 - mean_absolute_error: 0.5918 - val_loss: 0.9156 - val_mean_absolute_error: 0.7317
Epoch 15/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6072 - mean_absolute_error: 0.5823 - val_loss: 0.8962 - val_mean_absolute_error: 0.7234
Epoch 16/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5926 - mean_absolute_error: 0.5741 - val_loss: 0.8769 - val_mean_absolute_error: 0.7145
Epoch 17/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5777 - mean_absolute_error: 0.5654 - val_loss: 0.8604 - val_mean_absolute_error: 0.7074
Epoch 18/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5651 - mean_absolute_error: 0.5581 - val_loss: 0.8448 - val_mean_absolute_error: 0.7010
Epoch 19/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5526 - mean_absolute_error: 0.5512 - val_loss: 0.8319 - val_mean_absolute_error: 0.6957
Epoch 20/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5427 - mean_absolute_error: 0.5456 - val_loss: 0.8191 - val_mean_absolute_error: 0.6901
Epoch 21/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5332 - mean_absolute_error: 0.5404 - val_loss: 0.8080 - val_mean_absolute_error: 0.6860
Epoch 22/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5247 - mean_absolute_error: 0.5357 - val_loss: 0.7980 - val_mean_absolute_error: 0.6819
Epoch 23/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5174 - mean_absolute_error: 0.5319 - val_loss: 0.7893 - val_mean_absolute_error: 0.6778
Epoch 24/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5104 - mean_absolute_error: 0.5279 - val_loss: 0.7823 - val_mean_absolute_error: 0.6756
Epoch 25/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5048 - mean_absolute_error: 0.5257 - val_loss: 0.7755 - val_mean_absolute_error: 0.6728
Epoch 26/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5000 - mean_absolute_error: 0.5235 - val_loss: 0.7693 - val_mean_absolute_error: 0.6703
Epoch 27/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4950 - mean_absolute_error: 0.5213 - val_loss: 0.7645 - val_mean_absolute_error: 0.6685
Epoch 28/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4906 - mean_absolute_error: 0.5192 - val_loss: 0.7604 - val_mean_absolute_error: 0.6666
Epoch 29/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4873 - mean_absolute_error: 0.5174 - val_loss: 0.7557 - val_mean_absolute_error: 0.6640
Epoch 30/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4832 - mean_absolute_error: 0.5155 - val_loss: 0.7526 - val_mean_absolute_error: 0.6625
Epoch 31/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4804 - mean_absolute_error: 0.5140 - val_loss: 0.7493 - val_mean_absolute_error: 0.6609
Epoch 32/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4774 - mean_absolute_error: 0.5127 - val_loss: 0.7466 - val_mean_absolute_error: 0.6598
Epoch 33/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4746 - mean_absolute_error: 0.5114 - val_loss: 0.7439 - val_mean_absolute_error: 0.6585
Epoch 34/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4721 - mean_absolute_error: 0.5101 - val_loss: 0.7420 - val_mean_absolute_error: 0.6580
Epoch 35/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4699 - mean_absolute_error: 0.5091 - val_loss: 0.7402 - val_mean_absolute_error: 0.6574
Epoch 36/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4675 - mean_absolute_error: 0.5078 - val_loss: 0.7380 - val_mean_absolute_error: 0.6560
Epoch 37/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4653 - mean_absolute_error: 0.5066 - val_loss: 0.7365 - val_mean_absolute_error: 0.6556
Epoch 38/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4633 - mean_absolute_error: 0.5055 - val_loss: 0.7345 - val_mean_absolute_error: 0.6545
Epoch 39/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4614 - mean_absolute_error: 0.5047 - val_loss: 0.7340 - val_mean_absolute_error: 0.6544
Epoch 40/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4591 - mean_absolute_error: 0.5035 - val_loss: 0.7327 - val_mean_absolute_error: 0.6537
Epoch 41/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4574 - mean_absolute_error: 0.5025 - val_loss: 0.7315 - val_mean_absolute_error: 0.6534
Epoch 42/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4557 - mean_absolute_error: 0.5013 - val_loss: 0.7301 - val_mean_absolute_error: 0.6528
Epoch 43/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4539 - mean_absolute_error: 0.5003 - val_loss: 0.7285 - val_mean_absolute_error: 0.6521
Epoch 44/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4523 - mean_absolute_error: 0.4995 - val_loss: 0.7277 - val_mean_absolute_error: 0.6516
Epoch 45/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4510 - mean_absolute_error: 0.4988 - val_loss: 0.7266 - val_mean_absolute_error: 0.6513
Epoch 46/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4491 - mean_absolute_error: 0.4979 - val_loss: 0.7258 - val_mean_absolute_error: 0.6510
Epoch 47/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4480 - mean_absolute_error: 0.4973 - val_loss: 0.7249 - val_mean_absolute_error: 0.6505
Epoch 48/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4466 - mean_absolute_error: 0.4964 - val_loss: 0.7243 - val_mean_absolute_error: 0.6504
Epoch 49/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4455 - mean_absolute_error: 0.4958 - val_loss: 0.7232 - val_mean_absolute_error: 0.6496
Epoch 50/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4443 - mean_absolute_error: 0.4951 - val_loss: 0.7230 - val_mean_absolute_error: 0.6498
Epoch 51/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4431 - mean_absolute_error: 0.4945 - val_loss: 0.7223 - val_mean_absolute_error: 0.6496
Epoch 52/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4420 - mean_absolute_error: 0.4939 - val_loss: 0.7222 - val_mean_absolute_error: 0.6496
Epoch 53/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4410 - mean_absolute_error: 0.4936 - val_loss: 0.7215 - val_mean_absolute_error: 0.6491
Epoch 54/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4397 - mean_absolute_error: 0.4928 - val_loss: 0.7207 - val_mean_absolute_error: 0.6486
Epoch 55/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4390 - mean_absolute_error: 0.4920 - val_loss: 0.7195 - val_mean_absolute_error: 0.6480
Epoch 56/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4381 - mean_absolute_error: 0.4917 - val_loss: 0.7199 - val_mean_absolute_error: 0.6483
Epoch 57/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4370 - mean_absolute_error: 0.4914 - val_loss: 0.7203 - val_mean_absolute_error: 0.6488
Epoch 58/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4358 - mean_absolute_error: 0.4906 - val_loss: 0.7192 - val_mean_absolute_error: 0.6480
Epoch 59/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4353 - mean_absolute_error: 0.4898 - val_loss: 0.7178 - val_mean_absolute_error: 0.6470
Epoch 60/60
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4341 - mean_absolute_error: 0.4893 - val_loss: 0.7180 - val_mean_absolute_error: 0.6470

In [217]:
X_test_new.shape

(164, 3)

In [218]:
y_test.shape

(164, 1)

In [166]:
dir(history)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_api_export_path',
 '_api_export_symbol_id',
 '_model',
 'epoch',
 'history',
 'model',
 'on_batch_begin',
 'on_batch_end',
 'on_epoch_begin',
 'on_epoch_end',
 'on_predict_batch_begin',
 'on_predict_batch_end',
 'on_predict_begin',
 'on_predict_end',
 'on_test_batch_begin',
 'on_test_batch_end',
 'on_test_begin',
 'on_test_end',
 'on_train_batch_begin',
 'on_train_batch_end',
 'on_train_begin',
 'on_train_end',
 'params',
 'set_model',
 'set_params']

In [234]:
out = pd.DataFrame.from_dict(history.history)

In [206]:
out["val_mean_absolute_error"].mean()

np.float64(0.4987283284465472)

In [235]:
out

        loss  mean_absolute_error  val_loss  val_mean_absolute_error
0   1.042117             0.800416  1.397285                 0.941328
1   0.992917             0.778578  1.341547                 0.920006
2   0.947131             0.757817  1.289670                 0.899391
3   0.903373             0.737418  1.241840                 0.879913
4   0.866042             0.718710  1.195567                 0.860487
5   0.828511             0.700450  1.154408                 0.842832
6   0.794799             0.683150  1.116076                 0.825781
7   0.765075             0.667576  1.078860                 0.809195
8   0.734064             0.651951  1.047789                 0.794619
9   0.708922             0.638485  1.017001                 0.779759
10  0.685336             0.625580  0.987786                 0.765623
11  0.662860             0.613121  0.961295                 0.752922
12  0.643399             0.602823  0.936804                 0.741792
13  0.623668             0.591824  0.915581                 0.731741
14  0.607158             0.582283  0.896166                 0.723427
15  0.592559             0.574144  0.876904                 0.714534
16  0.577731             0.565383  0.860396                 0.707432
17  0.565094             0.558055  0.844768                 0.700964
18  0.552590             0.551194  0.831877                 0.695700
19  0.542708             0.545588  0.819114                 0.690125
20  0.533175             0.540442  0.807978                 0.686029
21  0.524678             0.535693  0.798043                 0.681877
22  0.517355             0.531877  0.789262                 0.677818
23  0.510384             0.527914  0.782277                 0.675578
24  0.504813             0.525736  0.775511                 0.672828
25  0.500008             0.523513  0.769290                 0.670315
26  0.495009             0.521287  0.764503                 0.668478
27  0.490583             0.519226  0.760400                 0.666617
28  0.487263             0.517429  0.755675                 0.664048
29  0.483243             0.515505  0.752554                 0.662544
30  0.480415             0.513996  0.749334                 0.660928
31  0.477362             0.512745  0.746600                 0.659800
32  0.474587             0.511353  0.743918                 0.658500
33  0.472097             0.510120  0.742011                 0.658013
34  0.469878             0.509061  0.740250                 0.657377
35  0.467456             0.507769  0.738029                 0.655959
36  0.465278             0.506619  0.736533                 0.655592
37  0.463260             0.505459  0.734498                 0.654473
38  0.461380             0.504708  0.733982                 0.654426
39  0.459077             0.503478  0.732695                 0.653724
40  0.457419             0.502467  0.731504                 0.653413
41  0.455685             0.501309  0.730091                 0.652811
42  0.453864             0.500279  0.728536                 0.652086
43  0.452280             0.499460  0.727701                 0.651626
44  0.451004             0.498806  0.726581                 0.651260
45  0.449129             0.497904  0.725830                 0.651004
46  0.448016             0.497318  0.724948                 0.650531
47  0.446562             0.496382  0.724329                 0.650382
48  0.445532             0.495770  0.723169                 0.649618
49  0.444273             0.495076  0.722995                 0.649825
50  0.443140             0.494509  0.722348                 0.649551
51  0.441985             0.493939  0.722153                 0.649605
52  0.440997             0.493583  0.721487                 0.649144
53  0.439721             0.492828  0.720652                 0.648604
54  0.438998             0.492012  0.719493                 0.647973
55  0.438089             0.491660  0.719930                 0.648268
56  0.437000             0.491440  0.720283                 0.648848
57  0.435840             0.490635  0.719200                 0.648011
58  0.435259             0.489840  0.717793                 0.647010
59  0.434141             0.489285  0.717997                 0.646952

In [174]:
y_test

array([[ 0.9770051 ],
       [ 0.93914497],
       [-0.7194989 ],
       [-0.13092537],
       [-0.4343398 ],
       [ 0.31052932],
       [ 0.5038696 ],
       [ 0.6096349 ],
       [-0.8482541 ],
       [-0.6889451 ],
       [ 2.4220634 ],
       [-0.73625606],
       [-0.77238816],
       [-0.6104919 ],
       [-0.43194908],
       [ 0.85331166],
       [-1.0217829 ],
       [ 0.18552123],
       [ 0.14199977],
       [-0.37767246],
       [-0.12468266],
       [ 0.32151982],
       [-0.7840921 ],
       [-0.4715971 ],
       [ 0.47417417],
       [ 1.3467487 ],
       [-0.8737818 ],
       [-0.0256937 ],
       [ 1.0307394 ],
       [-0.8884761 ],
       [ 0.24734688],
       [-0.6067619 ],
       [ 0.85818875],
       [ 0.2995389 ],
       [-0.15737365],
       [ 0.44958493],
       [-0.250819  ],
       [-0.75189805],
       [-0.5394115 ],
       [-0.16243677],
       [ 0.44447878],
       [-0.78722423],
       [ 0.9266141 ],
       [-0.38246074],
       [-0.25148284],
       [-0.39926055],
       [ 0.85818875],
       [-0.2105913 ],
       [-0.00464676],
       [-0.8884761 ],
       [ 1.0940533 ],
       [-0.8884761 ],
       [-0.05696496],
       [-0.30102727],
       [-0.59427994],
       [-0.64707816],
       [ 0.7930104 ],
       [-0.7506657 ],
       [ 0.51060927],
       [-0.758936  ],
       [-0.1307702 ],
       [-0.23145843],
       [-0.30647895],
       [-0.57536   ],
       [-0.01316394],
       [-0.48082525],
       [ 0.34986913],
       [-0.62983245],
       [ 0.9852987 ],
       [ 0.0951454 ],
       [-0.06076254],
       [ 0.270739  ],
       [ 0.05908418],
       [ 1.3859838 ],
       [-0.930523  ],
       [ 0.31653526],
       [-0.5093462 ],
       [-0.6027515 ],
       [ 0.18552123],
       [-0.03425073],
       [ 1.1456773 ],
       [-0.40565118],
       [ 0.7232551 ],
       [ 0.30529577],
       [-0.8994771 ],
       [ 1.5301346 ],
       [-0.66834176],
       [-0.54506093],
       [ 1.4612657 ],
       [ 1.6605695 ],
       [-1.1541272 ],
       [ 0.4521776 ],
       [-0.475504  ],
       [-0.55259347],
       [ 2.647639  ],
       [-0.57208633],
       [ 0.27984688],
       [ 0.8066669 ],
       [ 0.03104295],
       [ 1.2325766 ],
       [-0.5843489 ],
       [ 0.44958493],
       [-0.63574404],
       [ 0.7478322 ],
       [ 0.3470789 ],
       [ 0.662927  ],
       [ 1.0135356 ],
       [ 0.85818875],
       [ 0.87624115],
       [ 0.85818875],
       [ 1.0527029 ],
       [-0.75621516],
       [-0.7078853 ],
       [-0.48313227],
       [-0.12780236],
       [-0.46011436],
       [-0.10782672],
       [-0.59556484],
       [ 0.19100563],
       [-0.6067619 ],
       [-0.06922494],
       [ 0.3398373 ],
       [-0.5223041 ],
       [-0.8884761 ],
       [ 0.93149656],
       [-0.7506657 ],
       [ 0.738105  ],
       [ 0.38444003],
       [ 1.9617883 ],
       [ 1.0621953 ],
       [-0.62983245],
       [-0.06783192],
       [ 0.49067172],
       [ 0.94277686],
       [-0.5051798 ],
       [-0.78639996],
       [-0.4247769 ],
       [ 0.0426807 ],
       [-0.4421762 ],
       [-0.5318789 ],
       [-1.0449466 ],
       [-0.601167  ],
       [ 0.08889975],
       [-0.8033183 ],
       [ 0.00428611],
       [-0.73690945],
       [ 0.9266141 ],
       [ 0.28931096],
       [ 1.3902528 ],
       [ 1.7218236 ],
       [ 0.2790105 ],
       [ 0.17455234],
       [-0.6526806 ],
       [-0.31955484],
       [-0.5394115 ],
       [ 0.94469994],
       [ 1.2111213 ],
       [-0.6709847 ],
       [ 0.9362396 ],
       [-0.60539573],
       [-0.8568798 ],
       [ 1.0733328 ],
       [ 0.55666155],
       [ 0.14275211]], dtype=float32)

In [210]:
X_test_new

         area  bedrooms  bathrooms
316  0.354846  1.386046   1.554599
77   0.630777  0.055861   1.554599
360 -0.500539 -1.274325  -0.553238
90  -0.059050  0.055861  -0.553238
493 -0.537330  0.055861  -0.553238
..        ...       ...        ...
395 -0.702888  4.046417  -0.553238
425 -0.893740 -1.274325  -0.553238
195 -0.330382  1.386046   3.662437
452  1.780488  0.055861  -0.553238
154 -0.679894  0.055861   1.554599

[164 rows x 3 columns]

In [236]:
print("Evaluate on test data")
results = model.evaluate(X_test_new.values, y_test.values, batch_size=128)

Evaluate on test data
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7180 - mean_absolute_error: 0.6470

In [237]:
print("test loss, test acc:", results)

test loss, test acc: [0.7179970741271973, 0.6469520330429077]

In [238]:
print("Generate predictions for 3 samples")
predictions = model.predict(X_test_new.values)
print("predictions shape:", predictions.shape)

Generate predictions for 3 samples
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
predictions shape: (164, 1)

In [239]:
predictions

array([[ 0.93610007],
       [ 1.1329174 ],
       [-0.72194844],
       [-0.15475793],
       [-0.36246258],
       [ 0.23866563],
       [ 0.42607772],
       [ 0.6562253 ],
       [-0.89095926],
       [-0.68515676],
       [ 2.5103054 ],
       [-0.74637794],
       [-0.79485905],
       [-0.5936167 ],
       [-0.35973912],
       [ 0.9516195 ],
       [-1.0817453 ],
       [ 0.09302532],
       [ 0.04823761],
       [-0.2870868 ],
       [-0.15176536],
       [ 0.25482276],
       [-0.8092662 ],
       [-0.40583336],
       [ 0.4001885 ],
       [ 1.7380418 ],
       [-0.91533905],
       [-0.04058157],
       [ 0.9119663 ],
       [-0.9296963 ],
       [ 0.25318944],
       [-0.5887076 ],
       [ 0.9680117 ],
       [ 0.22154209],
       [-0.11348584],
       [ 0.4708456 ],
       [-0.20720914],
       [-0.4969766 ],
       [-0.4925968 ],
       [ 0.03736814],
       [ 0.3742935 ],
       [-0.8131216 ],
       [ 1.1084317 ],
       [-0.3020022 ],
       [-0.11824305],
       [-0.31224808],
       [ 0.9680117 ],
       [-0.14425798],
       [ 0.10395399],
       [-0.9296963 ],
       [ 1.3785938 ],
       [-0.9296963 ],
       [ 0.06418769],
       [-0.23849334],
       [-0.38926023],
       [-0.6376847 ],
       [ 0.88275397],
       [-0.75289536],
       [ 0.30965468],
       [-0.7772604 ],
       [-0.3121129 ],
       [-0.27264765],
       [-0.18950681],
       [-0.5238238 ],
       [-0.08460817],
       [-0.41628623],
       [ 0.8251565 ],
       [-0.6172985 ],
       [ 0.66299736],
       [ 0.00336882],
       [-0.08355498],
       [ 0.17729062],
       [ 0.15211381],
       [ 1.8003639 ],
       [-0.9773085 ],
       [ 0.43211168],
       [-0.4512972 ],
       [-0.56264913],
       [ 0.09302532],
       [-0.0998275 ],
       [ 1.0497627 ],
       [-0.33060822],
       [ 0.7936233 ],
       [ 0.23055461],
       [-0.9109521 ],
       [ 1.7853358 ],
       [-0.6625772 ],
       [-0.5008311 ],
       [ 1.2363758 ],
       [ 1.772178  ],
       [-0.6555882 ],
       [ 0.38100702],
       [-0.40401602],
       [-0.5117235 ],
       [ 2.4084568 ],
       [-0.37386978],
       [ 0.14873233],
       [ 0.899889  ],
       [-0.05038625],
       [ 1.0964822 ],
       [-0.5577311 ],
       [ 0.4708456 ],
       [-0.6241069 ],
       [ 0.8330703 ],
       [ 0.19334723],
       [ 0.41848773],
       [ 0.9645878 ],
       [ 0.9680117 ],
       [ 1.0018256 ],
       [ 0.9680117 ],
       [ 1.3194052 ],
       [-0.77357304],
       [-0.70547825],
       [-0.41889945],
       [-0.15326165],
       [-0.39242035],
       [-0.14343773],
       [-0.5735971 ],
       [ 0.09899702],
       [-0.5887076 ],
       [ 0.05362448],
       [ 0.2755064 ],
       [-0.46786204],
       [-0.9296963 ],
       [ 1.1180816 ],
       [-0.75289536],
       [ 0.7524533 ],
       [ 0.31801426],
       [ 1.917002  ],
       [ 1.3333641 ],
       [-0.6172985 ],
       [-0.12396792],
       [ 0.41457465],
       [ 1.1400872 ],
       [-0.44577557],
       [-0.8121071 ],
       [-0.35156888],
       [ 0.1789262 ],
       [-0.3627866 ],
       [-0.4816178 ],
       [-1.1101897 ],
       [-0.5811604 ],
       [-0.00268423],
       [-0.8104731 ],
       [ 0.11086692],
       [-0.7472998 ],
       [ 1.1084317 ],
       [ 0.3006557 ],
       [ 0.9771746 ],
       [ 1.56909   ],
       [ 0.41651195],
       [ 0.08108197],
       [-0.6444736 ],
       [-0.20826055],
       [-0.4925968 ],
       [ 0.6240197 ],
       [ 1.0853704 ],
       [-0.6655125 ],
       [ 1.126983  ],
       [-0.03558285],
       [-0.8998985 ],
       [ 1.2538625 ],
       [ 0.4705299 ],
       [ 0.13183375]], dtype=float32)

In [186]:
a = model.get_state_tree()

In [193]:
[(x, y.keys()) for x, y in zip(a.keys(), a.values())]

[('trainable_variables', dict_keys(['sequential_1'])),
 ('non_trainable_variables', dict_keys([])),
 ('optimizer_variables', dict_keys(['adam'])),
 ('metrics_variables', dict_keys(['loss', 'mean_metric_wrapper_1']))]

In [200]:
(a["optimizer_variables"]["adam"]["learning_rate"])

In [201]:
a["metrics_variables"]["loss"]

{'total': <tf.Variable 'loss/total:0' shape=() dtype=float32, numpy=148.93821716308594>,
 'count': <tf.Variable 'loss/count:0' shape=() dtype=float32, numpy=381.0>}

In [141]:
y_test_predicted = model.predict(tf.math.log(y_test.values))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [144]:
y_test = model.predict(X_test.values)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [145]:
X_test_predicted = model.predict(X_test.values)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [147]:
y_test_predicted =

W0000 00:00:1777760388.829266  995229 local_rendezvous.cc:412] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [32,1], In[1]: [3,64]
	 [[{{node sequential_1_1/dense_1/Relu}}]]

InvalidArgumentError: Graph execution error:

Detected at node sequential_1_1/dense_1/Relu defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 758, in start

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start

  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 645, in run_forever

  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once

  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 621, in shell_main

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 478, in dispatch_shell

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 372, in execute_request

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 834, in execute_request

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 464, in do_execute

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 663, in run_cell

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3169, in run_cell

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3224, in _run_cell

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3446, in run_cell_async

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3687, in run_ast_nodes

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3747, in run_code

  File "/var/folders/nm/n5dsnr416r79805q39p3xf640000gn/T/ipykernel_17331/3768748121.py", line 1, in <module>

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 588, in predict

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 282, in one_step_on_data_distributed

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 125, in wrapper

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 271, in one_step_on_data

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py", line 110, in predict_step

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/layers/layer.py", line 998, in __call__

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/ops/operation.py", line 59, in __call__

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/models/sequential.py", line 239, in call

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/models/functional.py", line 183, in call

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/ops/function.py", line 210, in _run_through_graph

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/models/functional.py", line 695, in call

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/layers/layer.py", line 998, in __call__

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/ops/operation.py", line 59, in __call__

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/layers/core/dense.py", line 221, in call

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/activations/activations.py", line 47, in relu

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/activations/activations.py", line 101, in static_call

  File "/Users/deven/.virtualenvs/ML_AI/lib/python3.12/site-packages/keras/src/backend/tensorflow/nn.py", line 18, in relu

Matrix size-incompatible: In[0]: [32,1], In[1]: [3,64]
	 [[{{node sequential_1_1/dense_1/Relu}}]] [Op:__inference_one_step_on_data_distributed_6418]