In [3]:
"""
The evaluation API requires that you set up a server which will respond to inference requests.
We have already defined the server; you just need write the predict function.
When we evaluate your submission on the hidden test set the client defined in `default_gateway` will run in a different container
with direct access to the hidden test set and hand off the data timestep by timestep.

Your code will always have access to the published copies of the copmetition files.
"""

import os

import pandas as pd
import polars as pl

import kaggle_evaluation.default_inference_server


def predict(test: pl.DataFrame) -> float:
    """Replace this function with your inference code.
    You can return either a Pandas or Polars dataframe, though Polars is recommended for performance.
    Each batch of predictions (except the very first) must be returned within 5 minutes of the batch features being provided.
    """
    return 0.0


# When your notebook is run on the hidden test set, inference_server.serve must be called within 15 minutes of the notebook starting
# or the gateway will throw an error. If you need more than 15 minutes to load your model you can do so during the very
# first `predict` call, which does not have the usual 1 minute response deadline.
inference_server = kaggle_evaluation.default_inference_server.DefaultInferenceServer(
    predict
)
#
# if os.getenv('KAGGLE_IS_COMPETITION_RERUN'):
#     inference_server.serve()
# else:
#     inference_server.run_local_gateway(('/kaggle/input/hull-tactical-market-prediction/',))

In [4]:
os.getcwd()

'/Users/deven/Developer/ML_AI/Kaggle Contests/hull-tactical-market-prediction'

## Data Loading and preparation
Data loading

In [5]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [6]:
from IPython.display import display


def display_info(df):
    print("First 10 rows")
    display(df[:10])
    print("\nAbout")

    display(df.info())
    print("\n\nDescription")
    display(df.describe())

### Train dataset info

In [7]:
display_info(df_train)

First 10 rows

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
0,0,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002421,0.000301,-0.003038
1,1,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008495,0.000303,-0.009114
2,2,0,0,0,1,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.009624,0.000301,-0.010243
3,3,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004662,0.000299,0.004046
4,4,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.011686,0.000299,-0.012301
5,5,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.006449,0.000300,-0.007066
6,6,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003644,0.000298,0.003029
7,7,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.024566,0.000300,-0.025183
8,8,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008492,0.000298,-0.009105
9,9,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.011263,0.000298,0.010649

About
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9021 entries, 0 to 9020
Data columns (total 98 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date_id                        9021 non-null   int64
 1   D1                             9021 non-null   int64
 2   D2                             9021 non-null   int64
 3   D3                             9021 non-null   int64
 4   D4                             9021 non-null   int64
 5   D5                             9021 non-null   int64
 6   D6                             9021 non-null   int64
 7   D7                             9021 non-null   int64
 8   D8                             9021 non-null   int64
 9   D9                             9021 non-null   int64
 10  E1                             7237 non-null   float64
 11  E10                            8015 non-null   float64
 12  E11                            8015 non-null   float64
 13  E12                            8015 non-null   float64
 14  E13                            8015 non-null   float64
 15  E14                            8015 non-null   float64
 16  E15                            8015 non-null   float64
 17  E16                            8015 non-null   float64
 18  E17                            8015 non-null   float64
 19  E18                            8015 non-null   float64
 20  E19                            8015 non-null   float64
 21  E2                             8015 non-null   float64
 22  E20                            7405 non-null   float64
 23  E3                             8015 non-null   float64
 24  E4                             8015 non-null   float64
 25  E5                             8015 non-null   float64
 26  E6                             8015 non-null   float64
 27  E7                             2052 non-null   float64
 28  E8                             8015 non-null   float64
 29  E9                             8015 non-null   float64
 30  I1                             8015 non-null   float64
 31  I2                             8015 non-null   float64
 32  I3                             8015 non-null   float64
 33  I4                             8015 non-null   float64
 34  I5                             8015 non-null   float64
 35  I6                             8015 non-null   float64
 36  I7                             8015 non-null   float64
 37  I8                             8015 non-null   float64
 38  I9                             8015 non-null   float64
 39  M1                             3474 non-null   float64
 40  M10                            8015 non-null   float64
 41  M11                            8015 non-null   float64
 42  M12                            8015 non-null   float64
 43  M13                            3481 non-null   float64
 44  M14                            3481 non-null   float64
 45  M15                            8015 non-null   float64
 46  M16                            8015 non-null   float64
 47  M17                            8015 non-null   float64
 48  M18                            8015 non-null   float64
 49  M2                             5804 non-null   float64
 50  M3                             7003 non-null   float64
 51  M4                             8015 non-null   float64
 52  M5                             5738 non-null   float64
 53  M6                             3978 non-null   float64
 54  M7                             8015 non-null   float64
 55  M8                             8015 non-null   float64
 56  M9                             8015 non-null   float64
 57  P1                             8015 non-null   float64
 58  P10                            8015 non-null   float64
 59  P11                            8015 non-null   float64
 60  P12                            8015 non-null   float64
 61  P13                            8015 non-null   float64
 62  P2                             8015 non-null   float64
 63  P3                             8015 non-null   float64
 64  P4                             8015 non-null   float64
 65  P5                             7447 non-null   float64
 66  P6                             7383 non-null   float64
 67  P7                             7405 non-null   float64
 68  P8                             8015 non-null   float64
 69  P9                             8015 non-null   float64
 70  S1                             8015 non-null   float64
 71  S10                            8015 non-null   float64
 72  S11                            8015 non-null   float64
 73  S12                            5484 non-null   float64
 74  S2                             8015 non-null   float64
 75  S3                             3288 non-null   float64
 76  S4                             8015 non-null   float64
 77  S5                             7510 non-null   float64
 78  S6                             8015 non-null   float64
 79  S7                             8015 non-null   float64
 80  S8                             6012 non-null   float64
 81  S9                             8015 non-null   float64
 82  V1                             8015 non-null   float64
 83  V10                            2972 non-null   float64
 84  V11                            8015 non-null   float64
 85  V12                            8015 non-null   float64
 86  V13                            7510 non-null   float64
 87  V2                             8015 non-null   float64
 88  V3                             8015 non-null   float64
 89  V4                             8015 non-null   float64
 90  V5                             7509 non-null   float64
 91  V6                             8015 non-null   float64
 92  V7                             7510 non-null   float64
 93  V8                             8015 non-null   float64
 94  V9                             4482 non-null   float64
 95  forward_returns                9021 non-null   float64
 96  risk_free_rate                 9021 non-null   float64
 97  market_forward_excess_returns  9021 non-null   float64
dtypes: float64(88), int64(10)
memory usage: 6.7 MB

None

Description

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
count,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,...,8015.000000,8015.000000,7509.000000,8015.000000,7510.000000,8015.000000,4482.000000,9021.000000,9021.000000,9021.000000
mean,4510.000000,0.031593,0.031593,0.047777,0.573994,0.190445,-0.238111,0.045671,0.142667,0.143000,...,0.489076,0.506589,0.373584,0.288874,0.145886,0.303203,0.125155,0.000471,0.000107,0.000053
std,2604.282723,0.174923,0.174923,0.213307,0.494522,0.392674,0.425951,0.208783,0.349752,0.350092,...,0.306060,0.306216,1.151136,0.312905,1.324779,0.350627,1.273912,0.010541,0.000088,0.010558
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000661,0.000661,-2.723527,0.000661,-2.027551,0.000661,-1.497420,-0.039754,-0.000004,-0.040582
25%,2255.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.206680,0.236772,-0.470083,0.000661,-0.795846,0.000661,-0.734003,-0.004319,0.000008,-0.004747
50%,4510.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.491402,0.517857,0.280020,0.182540,-0.100889,0.101852,-0.175851,0.000659,0.000097,0.000255
75%,6765.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.759921,0.771164,1.119295,0.519841,0.791181,0.588790,0.678213,0.005896,0.000193,0.005479
max,9020.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,6.809912,1.000000,12.678264,1.000000,12.997536,0.040661,0.000317,0.040551

### Checking for null values per column

In [8]:
checking_null = {}
for col in df_train.columns:
    if df_train[col].isna().sum().sum() != 0:
        checking_null[col] = df_train[col].isna().sum()

In [9]:
for key, value in checking_null.items():
    print(f"{key}: {value}")

E1: 1784
E10: 1006
E11: 1006
E12: 1006
E13: 1006
E14: 1006
E15: 1006
E16: 1006
E17: 1006
E18: 1006
E19: 1006
E2: 1006
E20: 1616
E3: 1006
E4: 1006
E5: 1006
E6: 1006
E7: 6969
E8: 1006
E9: 1006
I1: 1006
I2: 1006
I3: 1006
I4: 1006
I5: 1006
I6: 1006
I7: 1006
I8: 1006
I9: 1006
M1: 5547
M10: 1006
M11: 1006
M12: 1006
M13: 5540
M14: 5540
M15: 1006
M16: 1006
M17: 1006
M18: 1006
M2: 3217
M3: 2018
M4: 1006
M5: 3283
M6: 5043
M7: 1006
M8: 1006
M9: 1006
P1: 1006
P10: 1006
P11: 1006
P12: 1006
P13: 1006
P2: 1006
P3: 1006
P4: 1006
P5: 1574
P6: 1638
P7: 1616
P8: 1006
P9: 1006
S1: 1006
S10: 1006
S11: 1006
S12: 3537
S2: 1006
S3: 5733
S4: 1006
S5: 1511
S6: 1006
S7: 1006
S8: 3009
S9: 1006
V1: 1006
V10: 6049
V11: 1006
V12: 1006
V13: 1511
V2: 1006
V3: 1006
V4: 1006
V5: 1512
V6: 1006
V7: 1511
V8: 1006
V9: 4539

In [10]:
dict(sorted(checking_null.items(), key=lambda x: x[1], reverse=True))

{'E7': np.int64(6969),
 'V10': np.int64(6049),
 'S3': np.int64(5733),
 'M1': np.int64(5547),
 'M13': np.int64(5540),
 'M14': np.int64(5540),
 'M6': np.int64(5043),
 'V9': np.int64(4539),
 'S12': np.int64(3537),
 'M5': np.int64(3283),
 'M2': np.int64(3217),
 'S8': np.int64(3009),
 'M3': np.int64(2018),
 'E1': np.int64(1784),
 'P6': np.int64(1638),
 'E20': np.int64(1616),
 'P7': np.int64(1616),
 'P5': np.int64(1574),
 'V5': np.int64(1512),
 'S5': np.int64(1511),
 'V13': np.int64(1511),
 'V7': np.int64(1511),
 'E10': np.int64(1006),
 'E11': np.int64(1006),
 'E12': np.int64(1006),
 'E13': np.int64(1006),
 'E14': np.int64(1006),
 'E15': np.int64(1006),
 'E16': np.int64(1006),
 'E17': np.int64(1006),
 'E18': np.int64(1006),
 'E19': np.int64(1006),
 'E2': np.int64(1006),
 'E3': np.int64(1006),
 'E4': np.int64(1006),
 'E5': np.int64(1006),
 'E6': np.int64(1006),
 'E8': np.int64(1006),
 'E9': np.int64(1006),
 'I1': np.int64(1006),
 'I2': np.int64(1006),
 'I3': np.int64(1006),
 'I4': np.int64(1006),
 'I5': np.int64(1006),
 'I6': np.int64(1006),
 'I7': np.int64(1006),
 'I8': np.int64(1006),
 'I9': np.int64(1006),
 'M10': np.int64(1006),
 'M11': np.int64(1006),
 'M12': np.int64(1006),
 'M15': np.int64(1006),
 'M16': np.int64(1006),
 'M17': np.int64(1006),
 'M18': np.int64(1006),
 'M4': np.int64(1006),
 'M7': np.int64(1006),
 'M8': np.int64(1006),
 'M9': np.int64(1006),
 'P1': np.int64(1006),
 'P10': np.int64(1006),
 'P11': np.int64(1006),
 'P12': np.int64(1006),
 'P13': np.int64(1006),
 'P2': np.int64(1006),
 'P3': np.int64(1006),
 'P4': np.int64(1006),
 'P8': np.int64(1006),
 'P9': np.int64(1006),
 'S1': np.int64(1006),
 'S10': np.int64(1006),
 'S11': np.int64(1006),
 'S2': np.int64(1006),
 'S4': np.int64(1006),
 'S6': np.int64(1006),
 'S7': np.int64(1006),
 'S9': np.int64(1006),
 'V1': np.int64(1006),
 'V11': np.int64(1006),
 'V12': np.int64(1006),
 'V2': np.int64(1006),
 'V3': np.int64(1006),
 'V4': np.int64(1006),
 'V6': np.int64(1006),
 'V8': np.int64(1006)}

In [11]:
df_train[df_train["E7"].isna()]

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
0,0,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002421,0.000301,-0.003038
1,1,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008495,0.000303,-0.009114
2,2,0,0,0,1,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.009624,0.000301,-0.010243
3,3,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004662,0.000299,0.004046
4,4,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.011686,0.000299,-0.012301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6964,6964,0,0,0,0,0,0,0,0,0,...,0.998677,0.993386,0.361122,0.830688,-0.562964,0.952381,-0.645116,0.010457,0.000038,0.010111
6965,6965,0,0,0,0,0,-1,0,0,0,...,0.984127,0.992725,0.735807,0.937169,-0.897940,0.972884,-0.917116,-0.003585,0.000039,-0.003932
6966,6966,0,0,0,0,0,-1,0,0,0,...,0.989418,0.993386,1.294909,0.873677,-0.736227,0.974868,-0.777680,-0.002331,0.000039,-0.002678
6967,6967,0,0,0,0,0,-1,0,0,0,...,0.963624,0.995370,0.511534,0.814153,-0.741770,0.953042,-0.766430,0.002336,0.000040,0.001989
6968,6968,0,0,0,0,0,-1,0,0,0,...,0.942460,0.996693,0.506594,0.870370,-0.918045,0.964947,-0.847542,0.000041,0.000039,-0.000306