In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
df = pd.read_parquet("trip_records/2023-1.parquet")

In [29]:
df[df["total_amount"] < 0]["RatecodeID"]

76200      3.0
76507      3.0
76951      2.0
78647      2.0
87765      2.0
          ...
2848627    2.0
2859856    1.0
2897666    1.0
2910265    1.0
2922812    2.0
Name: RatecodeID, Length: 163, dtype: float64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3041714 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), object(1)
memory usage: 464.1+ MB

**Trip Records**



|Field Name       |description |
|:----------------|:-----------|
| VendorID | A code indicating the TPEP provider that provided the record. <br> 1= Creative Mobile Technologies, LLC; <br> 2= VeriFone Inc. |
| tpep_pickup_datetime | The date and time when the meter was engaged.  |
| tpep_dropoff_datetime | The date and time when the meter was disengaged.   |
| Passenger_count | The number of passengers in the vehicle. <br> This is a driver-entered value. |
| Trip_distance | The elapsed trip distance in miles reported by the taximeter. |
| PULocationID | TLC Taxi Zone in which the taximeter was engaged |
| DOLocationID | TLC Taxi Zone in which the taximeter was disengaged |
|RateCodeID |The final rate code in effect at the end of the trip.<br> 1 = Standard rate <br> 2 = JFK <br> 3 = Newark <br>4 = Nassau or Westchester <br>5 = Negotiated fare <br>6 = Group ride |
|Store_and_fwd_flag |This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka “store and forward,” because the vehicle did not have a connection to the server.  <br>Y= store and forward trip <br>N= not a store and forward trip |
|Payment_type| A numeric code signifying how the passenger paid for the trip. <br> 1 = Credit card <br>2 = Cash <br>3 = No charge <br>4 = Dispute <br>5 = Unknown <br>6 = Voided trip |
|Fare_amount| The time-and-distance fare calculated by the meter. <br>Extra Miscellaneous extras and surcharges.  Currently, this only includes the 0.50 and 1 USD rush hour and overnight charges. |
|MTA_tax |0.50 USD MTA tax that is automatically triggered based on the metered rate in use. |
|Improvement_surcharge | 0.30 USD improvement surcharge assessed trips at the flag drop. The improvement surcharge began being levied in 2015. |
|Tip_amount |Tip amount – This field is automatically populated for credit card tips. Cash tips are not included. |
| Tolls_amount | Total amount of all tolls paid in trip.  |
| total_amount | The total amount charged to passengers. Does not include cash tips. |
|Congestion_Surcharge |Total amount collected in trip for NYS congestion surcharge. |
| Airport_fee | 1.25 USD for pick up only at LaGuardia and John F. Kennedy Airports|

Although the amounts of extra charges and taxes applied are specified in the data dictionary, you will see that some cases have different values of these charges in the actual data.

In [8]:
df["total_amount"].describe()

count    3.041714e+06
mean     2.744160e+01
std      2.163570e+01
min     -5.250000e+00
25%      1.548000e+01
50%      2.016000e+01
75%      2.890000e+01
max      1.169400e+03
Name: total_amount, dtype: float64

In [9]:
df["payment_type"].value_counts()

payment_type
1    2411441
2     526550
0      71686
4      18546
3      13491
Name: count, dtype: int64

In [10]:
(
    df["fare_amount"]
    + df["mta_tax"]
    + df["improvement_surcharge"]
    + df["tip_amount"]
    + df["tolls_amount"]
    + df["congestion_surcharge"]
    + df["airport_fee"]
)

0          13.30
1          15.90
2          33.90
3          14.85
4          18.68
           ...
3066761      NaN
3066762      NaN
3066763      NaN
3066764      NaN
3066765      NaN
Length: 3041714, dtype: float64

In [11]:
df["total_amount"]

0          14.30
1          16.90
2          34.90
3          20.85
4          19.68
           ...
3066761    23.76
3066762    29.07
3066763    26.93
3066764    26.58
3066765    21.97
Name: total_amount, Length: 3041714, dtype: float64

In [7]:
os.getcwd()

'/Users/deven/Developer/ML_AI/course1/module7_project/trip_records'

In [6]:
import os

os.getcwd()
os.chdir("trip_records")

In [8]:
file_path = os.path.join(os.getcwd(), "2023-1.parquet")

In [10]:
file_path

'/Users/deven/Developer/ML_AI/course1/module7_project/trip_records/2023-1.parquet'

In [13]:
df1 = pd.read_parquet(file_path)

In [14]:
df1

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-06-01 00:08:48,2023-06-01 00:29:41,1.0,3.40,1.0,N,140,238,1,21.90,3.50,0.5,6.70,0.00,1.0,33.60,2.5,0.00
1,1,2023-06-01 00:15:04,2023-06-01 00:25:18,0.0,3.40,1.0,N,50,151,1,15.60,3.50,0.5,3.00,0.00,1.0,23.60,2.5,0.00
2,1,2023-06-01 00:48:24,2023-06-01 01:07:07,1.0,10.20,1.0,N,138,97,1,40.80,7.75,0.5,10.00,0.00,1.0,60.05,0.0,1.75
3,2,2023-06-01 00:54:03,2023-06-01 01:17:29,3.0,9.83,1.0,N,100,244,1,39.40,1.00,0.5,8.88,0.00,1.0,53.28,2.5,0.00
4,2,2023-06-01 00:18:44,2023-06-01 00:27:18,1.0,1.17,1.0,N,137,234,1,9.30,1.00,0.5,0.72,0.00,1.0,15.02,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3307229,2,2023-06-30 23:30:21,2023-07-01 00:00:46,NaN,9.20,NaN,None,42,148,0,38.53,0.00,0.5,8.51,0.00,1.0,51.04,NaN,NaN
3307230,1,2023-06-30 23:34:22,2023-07-01 00:32:59,NaN,20.20,NaN,None,132,74,0,70.00,1.75,0.5,11.97,6.55,1.0,91.77,NaN,NaN
3307231,2,2023-06-30 23:45:00,2023-07-01 00:10:00,NaN,6.16,NaN,None,256,140,0,28.03,0.00,0.5,6.41,0.00,1.0,38.44,NaN,NaN
3307232,2,2023-06-30 23:13:38,2023-06-30 23:51:19,NaN,11.65,NaN,None,91,246,0,45.74,0.00,0.5,0.00,6.55,1.0,56.29,NaN,NaN
3307233,2,2023-06-30 23:18:00,2023-06-30 23:31:00,NaN,1.40,NaN,None,164,230,0,14.35,0.00,0.5,0.00,0.00,1.0,18.35,NaN,NaN

In [15]:
# Take a small percentage of entries from each hour of every date.
# Iterating through the monthly data:
#   read a month file -> day -> hour: append sampled data -> move to next hour -> move to next day after 24 hours -> move to next month file
# Create a single dataframe for the year combining all the monthly data

# Select the folder having data files
import os

# Select the folder having data files
# os.chdir('/content/Assignments/EDA/data_NYC_Taxi/trip_records')

# Create a list of all the twelve files to read
file_list = os.listdir()

In [21]:
# initialise an empty dataframe
df = pd.DataFrame()


# iterate through the list of files and sample one by one:
for file_name in file_list:
    try:
        # file path for the current file
        file_path = os.path.join(os.getcwd(), file_name)
        if not file_path.endswith("parquet"):
            continue
        # Reading the current file
        sample = pd.read_parquet(file_path)
        sample["date"] = sample["tpep_pickup_datetime"].dt.date
        sample["hour"] = sample["tpep_pickup_datetime"].dt.hour
        print(sample.head())
        for date in range(1, 32):
            if date in sample["date"]:
                for hour in range(24):
                    if hour in sample["hour"]:
                        hour_data = sample[
                            (sample["date"] == date) & (sample["hour"] == hour)
                        ].sample(frac=0.42, random_state=42)
                        df = pd.concat([df, hour_data])

        # We will store the sampled data for the current date in this df by appending the sampled data from each hour to this
        # After completing iteration through each date, we will append this data to the final dataframe.

        # Loop through dates and then loop through every hour of each date

        # Iterate through each hour of the selected date

        # Sample 5% of the hourly data randomly

        # add data of this hour to the dataframe

        # Concatenate the sampled data of all the dates to a single dataframe

    except Exception as e:
        print(f"Error reading file {file_name}: {e}")

   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-12-01 00:06:06   2023-12-01 00:15:47              0.0
1         1  2023-12-01 00:22:26   2023-12-01 00:28:53              0.0
2         1  2023-12-01 00:59:44   2023-12-01 01:13:22              2.0
3         2  2023-12-01 00:22:17   2023-12-01 00:30:59              1.0
4         2  2023-12-01 00:18:16   2023-12-01 00:25:32              2.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           1.10         1.0                  N           230            48
1           1.50         1.0                  N           142           238
2           2.20         1.0                  N           114           186
3           0.66         1.0                  N            79            79
4           2.20         1.0                  N           229           263

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             1  ...    3.5      0.5        1.50           0.0
1             1  ...    3.5      0.5        2.85           0.0
2             1  ...    3.5      0.5        3.00           0.0
3             2  ...    1.0      0.5        0.00           0.0
4             1  ...    1.0      0.5        2.00           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         16.50                   2.5          0.0
1                    1.0         17.15                   2.5          0.0
2                    1.0         21.50                   2.5          0.0
3                    1.0         12.20                   2.5          0.0
4                    1.0         18.40                   2.5          0.0

         date hour
0  2023-12-01    0
1  2023-12-01    0
2  2023-12-01    0
3  2023-12-01    0
4  2023-12-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-04-01 00:14:49   2023-04-01 00:45:01              2.0
1         2  2023-04-01 00:00:24   2023-04-01 00:56:19              1.0
2         1  2023-04-01 00:03:50   2023-04-01 00:14:42              2.0
3         1  2023-04-01 00:53:18   2023-04-01 01:01:28              1.0
4         2  2023-04-01 00:07:00   2023-04-01 00:17:16              2.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           4.90         1.0                  N            48           223
1          21.89         2.0                  N           132            43
2           1.30         1.0                  N           148           113
3           1.50         1.0                  N           249            79
4           1.49         1.0                  N           158           246

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             1  ...    3.5      0.5         6.0          0.00
1             2  ...    0.0      0.5         0.0          6.55
2             1  ...    3.5      0.5         2.0          0.00
3             1  ...    3.5      0.5         1.0          0.00
4             1  ...    1.0      0.5         1.0          0.00

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0          39.9                   2.5         0.00
1                    1.0          81.8                   2.5         1.25
2                    1.0          18.4                   2.5         0.00
3                    1.0          16.0                   2.5         0.00
4                    1.0          17.4                   2.5         0.00

         date hour
0  2023-04-01    0
1  2023-04-01    0
2  2023-04-01    0
3  2023-04-01    0
4  2023-04-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-05-01 00:33:13   2023-05-01 00:53:01              0.0
1         1  2023-05-01 00:42:49   2023-05-01 01:11:18              2.0
2         1  2023-05-01 00:56:34   2023-05-01 01:13:39              2.0
3         2  2023-05-01 00:00:52   2023-05-01 00:20:12              1.0
4         1  2023-05-01 00:05:50   2023-05-01 00:19:41              0.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           7.80         1.0                  N           138            43
1           8.10         1.0                  N           138           262
2           9.10         1.0                  N           138           141
3           8.21         1.0                  N           138           140
4           7.90         1.0                  N           138           263

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             1  ...   7.75      0.5        8.60          0.00
1             1  ...  10.25      0.5        9.50          0.00
2             1  ...  10.25      0.5       10.70          6.55
3             1  ...   6.00      0.5        2.24          0.00
4             1  ...  10.25      0.5        9.85          6.55

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         51.65                   0.0         1.75
1                    1.0         57.15                   2.5         1.75
2                    1.0         64.20                   2.5         1.75
3                    1.0         47.09                   2.5         1.75
4                    1.0         59.15                   2.5         1.75

         date hour
0  2023-05-01    0
1  2023-05-01    0
2  2023-05-01    0
3  2023-05-01    0
4  2023-05-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-02-01 00:32:53   2023-02-01 00:34:34              2.0
2         2  2023-02-01 00:35:16   2023-02-01 00:35:30              1.0
3         1  2023-02-01 00:29:33   2023-02-01 01:01:38              0.0
4         2  2023-02-01 00:12:28   2023-02-01 00:25:46              1.0
5         1  2023-02-01 00:52:40   2023-02-01 01:07:18              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           0.30         1.0                  N           142           163
2           0.00         1.0                  N            71            71
3          18.80         1.0                  N           132            26
4           3.22         1.0                  N           161           145
5           5.10         1.0                  N           148           236

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             2  ...   3.50      0.5        0.00           0.0
2             4  ...   1.00      0.5        0.00           0.0
3             1  ...   2.25      0.5        0.00           0.0
4             1  ...   1.00      0.5        3.30           0.0
5             1  ...   3.50      0.5        5.35           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0          9.40                   2.5         0.00
2                    1.0          5.50                   0.0         0.00
3                    1.0         74.65                   0.0         1.25
4                    1.0         25.30                   2.5         0.00
5                    1.0         32.25                   2.5         0.00

         date hour
0  2023-02-01    0
2  2023-02-01    0
3  2023-02-01    0
4  2023-02-01    0
5  2023-02-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-11-01 00:03:03   2023-11-01 01:04:08              2.0
1         1  2023-11-01 00:03:28   2023-11-01 00:23:59              0.0
2         2  2023-10-31 23:58:05   2023-11-01 00:54:03              4.0
3         2  2023-11-01 00:03:50   2023-11-01 00:04:59              1.0
4         2  2023-11-01 00:06:30   2023-11-01 00:14:25              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0          13.60         1.0                  N           132            26
1           3.50         1.0                  N           140             7
2          18.61         2.0                  N           132           230
3           0.39         1.0                  N           236           236
4           1.20         1.0                  N           236           141

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             2  ...   2.75      0.5        0.00          0.00
1             1  ...   3.50      0.5        5.10          0.00
2             1  ...   0.00      0.5       16.54          6.94
3             1  ...   1.00      0.5        1.88          0.00
4             1  ...   1.00      0.5        3.00          0.00

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         66.05                   0.0         1.75
1                    1.0         30.60                   2.5         0.00
2                    1.0         99.23                   2.5         1.75
3                    1.0         11.28                   2.5         0.00
4                    1.0         18.00                   2.5         0.00

         date hour
0  2023-11-01    0
1  2023-11-01    0
2  2023-10-31   23
3  2023-11-01    0
4  2023-11-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-10-01 00:16:44   2023-10-01 00:16:49              1.0
1         1  2023-10-01 00:23:24   2023-10-01 00:23:47              1.0
2         1  2023-10-01 00:21:18   2023-10-01 00:27:31              1.0
3         1  2023-10-01 00:17:39   2023-10-01 00:17:47              0.0
4         2  2023-10-01 00:16:15   2023-10-01 00:22:57              2.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           0.00         1.0                  N           168           168
1           0.00         1.0                  N           168           168
2           0.90         1.0                  N           161           186
3           0.00         1.0                  N           255           255
4           1.41         1.0                  N           151           239

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             2  ...    1.0      0.5         0.0           0.0
1             2  ...    1.0      0.5         0.0           0.0
2             1  ...    3.5      0.5         2.9           0.0
3             3  ...    1.0      0.5         0.0           0.0
4             1  ...    1.0      0.5         3.0           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0           5.5                   0.0          0.0
1                    1.0           5.5                   0.0          0.0
2                    1.0          14.4                   2.5          0.0
3                    1.0           5.5                   0.0          0.0
4                    1.0          18.0                   2.5          0.0

         date hour
0  2023-10-01    0
1  2023-10-01    0
2  2023-10-01    0
3  2023-10-01    0
4  2023-10-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-08-01 00:26:44   2023-08-01 00:45:25              1.0
1         1  2023-08-01 00:55:42   2023-08-01 01:00:53              1.0
2         2  2023-08-01 00:32:04   2023-08-01 01:09:03              1.0
3         2  2023-08-01 00:13:37   2023-08-01 00:41:15              1.0
4         1  2023-08-01 00:24:46   2023-08-01 00:41:31              2.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           4.30         1.0                  N           263            90
1           0.00         1.0                  N           132           132
2          20.61         2.0                  N           132            13
3          13.37         1.0                  N           138           254
4           3.20         5.0                  N           140           143

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             1  ...   3.50      0.5        5.35          0.00
1             3  ...   2.75      0.5        0.00          0.00
2             1  ...   0.00      0.5       14.80          0.00
3             2  ...   6.00      0.5        0.00          6.55
4             4  ...   0.00      0.0        0.00          0.00

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         32.25                   2.5         0.00
1                    1.0          9.35                   0.0         1.75
2                    1.0         90.55                   2.5         1.75
3                    1.0         69.90                   0.0         1.75
4                    1.0         21.00                   0.0         0.00

         date hour
0  2023-08-01    0
1  2023-08-01    0
2  2023-08-01    0
3  2023-08-01    0
4  2023-08-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2  2023-01-01 00:32:10   2023-01-01 00:40:36              1.0
1         2  2023-01-01 00:55:08   2023-01-01 01:01:27              1.0
2         2  2023-01-01 00:25:04   2023-01-01 00:37:49              1.0
3         1  2023-01-01 00:03:48   2023-01-01 00:13:25              0.0
4         2  2023-01-01 00:10:29   2023-01-01 00:21:19              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           0.97         1.0                  N           161           141
1           1.10         1.0                  N            43           237
2           2.51         1.0                  N            48           238
3           1.90         1.0                  N           138             7
4           1.43         1.0                  N           107            79

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             2  ...   1.00      0.5        0.00           0.0
1             1  ...   1.00      0.5        4.00           0.0
2             1  ...   1.00      0.5       15.00           0.0
3             1  ...   7.25      0.5        0.00           0.0
4             1  ...   1.00      0.5        3.28           0.0

   improvement_surcharge  total_amount  congestion_surcharge  airport_fee  \
0                    1.0         14.30                   2.5         0.00
1                    1.0         16.90                   2.5         0.00
2                    1.0         34.90                   2.5         0.00
3                    1.0         20.85                   0.0         1.25
4                    1.0         19.68                   2.5         0.00

         date hour
0  2023-01-01    0
1  2023-01-01    0
2  2023-01-01    0
3  2023-01-01    0
4  2023-01-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-07-01 00:29:59   2023-07-01 00:40:15              1.0
1         2  2023-07-01 00:03:25   2023-07-01 00:23:44              1.0
2         2  2023-07-01 00:38:29   2023-07-01 00:48:53              1.0
3         2  2023-07-01 00:14:16   2023-07-01 00:29:13              1.0
4         1  2023-07-01 00:11:15   2023-07-01 00:20:47              0.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           1.80         1.0                  N           140           263
1           2.31         1.0                  N           163           163
2           2.36         1.0                  N           142           262
3           4.36         1.0                  N            68            24
4           1.60         1.0                  N           161           107

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             1  ...    3.5      0.5        5.10           0.0
1             2  ...    1.0      0.5        0.00           0.0
2             1  ...    1.0      0.5        3.70           0.0
3             1  ...    1.0      0.5        4.96           0.0
4             1  ...    3.5      0.5        3.25           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         22.20                   2.5          0.0
1                    1.0         24.10                   2.5          0.0
2                    1.0         22.20                   2.5          0.0
3                    1.0         29.76                   2.5          0.0
4                    1.0         19.65                   2.5          0.0

         date hour
0  2023-07-01    0
1  2023-07-01    0
2  2023-07-01    0
3  2023-07-01    0
4  2023-07-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         1  2023-09-01 00:15:37   2023-09-01 00:20:21              1.0
1         2  2023-09-01 00:18:40   2023-09-01 00:30:28              2.0
2         2  2023-09-01 00:35:01   2023-09-01 00:39:04              1.0
3         2  2023-09-01 00:45:45   2023-09-01 00:47:37              1.0
4         2  2023-09-01 00:01:23   2023-09-01 00:38:05              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           0.80         1.0                  N           163           230
1           2.34         1.0                  N           236           233
2           1.62         1.0                  N           162           236
3           0.74         1.0                  N           141           229
4           9.85         1.0                  N           138           230

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             2  ...    3.5      0.5        0.00           0.0
1             1  ...    1.0      0.5        2.00           0.0
2             1  ...    1.0      0.5        2.00           0.0
3             1  ...    1.0      0.5        1.00           0.0
4             1  ...    6.0      0.5       17.02           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         11.50                   2.5         0.00
1                    1.0         21.20                   2.5         0.00
2                    1.0         15.60                   2.5         0.00
3                    1.0         11.10                   2.5         0.00
4                    1.0         73.77                   2.5         1.75

         date hour
0  2023-09-01    0
1  2023-09-01    0
2  2023-09-01    0
3  2023-09-01    0
4  2023-09-01    0

[5 rows x 21 columns]
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2  2023-03-01 00:06:43   2023-03-01 00:16:43              1.0
1         2  2023-03-01 00:08:25   2023-03-01 00:39:30              2.0
2         1  2023-03-01 00:15:04   2023-03-01 00:29:26              0.0
3         1  2023-03-01 00:49:37   2023-03-01 01:01:05              1.0
4         2  2023-03-01 00:08:04   2023-03-01 00:11:06              1.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           0.00         1.0                  N           238            42
1          12.40         1.0                  N           138           231
2           3.30         1.0                  N           140           186
3           2.90         1.0                  N           140            43
4           1.23         1.0                  N            79           137

   payment_type  ...  extra  mta_tax  tip_amount  tolls_amount  \
0             2  ...    1.0      0.5        0.00           0.0
1             1  ...    6.0      0.5       12.54           0.0
2             1  ...    3.5      0.5        4.65           0.0
3             1  ...    3.5      0.5        4.10           0.0
4             1  ...    1.0      0.5        2.44           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \

In [22]:
df.shape

(0, 22)

In [24]:
df

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, Airport_fee, date, hour, airport_fee]
Index: []

[0 rows x 22 columns]

In [ ]:
sampled_data = pd.DataFrame()
hour_data = pd.DataFrame()
sample["date"] = sample["tpep_pickup_datetime"].dt.date
sample["hour"] = sample["tpep_pickup_datetime"].dt.hour
for date in range(1, 32):
    for hour in range(24):
        if (
            date in sample["tpep_pickup_datetime"].dt.date
            and hour in sample["tpep_pickup_datetime"].dt.hour
        ):
            hour_data = sample[sample["date"] == date & sample["hour"] == hour].sample(
                frac=0.05, random_state=42
            )
    sampled_data = pd.concat([sampled_data, hour_data])
df = pd.concat([df, sampled_data])

In [12]:
df

Empty DataFrame
Columns: []
Index: []

In [4]:
df["date"] = df["tpep_pickup_datetime"].dt.day

In [5]:
df["hour"] = df["tpep_pickup_datetime"].dt.hour

In [21]:
def concat_files(df):
    combined_sample = pd.DataFrame()
    df["date"] = df["tpep_pickup_datetime"].dt.day
    df["hour"] = df["tpep_pickup_datetime"].dt.hour
    for date in range(min(df["date"]), max(df["date"]) + 1):
        for hour in range(min(df["hour"]), max(df["hour"]) + 1):

            sample = df[(df["date"] == date) & (df["hour"] == hour)].sample(
                frac=0.05, random_state=42
            )
            combined_sample = pd.concat([combined_sample, sample])
    return combined_sample

Empty DataFrame
Columns: []
Index: []

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame

In [24]:
combined_sample.shape[0] / df.shape[0]

0.05000042739060937

In [12]:
import os

file_list = os.listdir("trip_records/")

In [22]:
temp = pd.read_parquet("trip_records/2023-1.parquet")
temp = concat_files(temp)

In [23]:
temp

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,date,hour
3703,2,2023-01-01 00:31:50,2023-01-01 00:44:17,2.0,2.85,1.0,N,263,41,1,...,1.0,0.5,4.12,0.0,1.0,24.72,2.5,0.0,1,0
4166,2,2023-01-01 00:10:50,2023-01-01 00:24:12,4.0,1.32,1.0,N,90,137,1,...,1.0,0.5,3.56,0.0,1.0,21.36,2.5,0.0,1,0
3847,2,2023-01-01 00:25:37,2023-01-01 00:34:52,1.0,3.17,1.0,N,79,141,1,...,1.0,0.5,3.98,0.0,1.0,23.88,2.5,0.0,1,0
1882,2,2023-01-01 00:27:26,2023-01-01 00:52:20,2.0,3.80,1.0,N,142,107,2,...,1.0,0.5,0.00,0.0,1.0,29.70,2.5,0.0,1,0
2995366,2,2023-01-01 00:59:15,2023-01-01 01:23:15,NaN,7.97,NaN,None,140,17,0,...,0.0,0.5,8.17,0.0,1.0,49.00,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2992696,2,2023-01-31 23:03:26,2023-01-31 23:14:09,2.0,2.56,1.0,N,234,141,1,...,1.0,0.5,3.70,0.0,1.0,22.20,2.5,0.0,31,23
2994830,1,2023-01-31 23:31:07,2023-01-31 23:38:19,1.0,0.90,1.0,N,100,170,1,...,3.5,0.5,2.20,0.0,1.0,14.40,2.5,0.0,31,23
2992162,1,2023-01-31 23:28:10,2023-01-31 23:37:12,1.0,1.90,1.0,N,162,234,1,...,3.5,0.5,3.14,0.0,1.0,18.84,2.5,0.0,31,23
2994599,2,2023-01-31 23:39:53,2023-01-31 23:42:46,1.0,0.56,1.0,N,161,48,1,...,1.0,0.5,1.00,0.0,1.0,11.10,2.5,0.0,31,23
2993734,1,2023-01-31 23:14:12,2023-01-31 23:33:07,1.0,3.80,1.0,N,249,256,1,...,3.5,0.5,4.95,0.0,1.0,29.75,2.5,0.0,31,23

In [27]:
os.chdir("trip_records/")

# sample = pd.read_parquet('trip_records/')

In [28]:
os.getcwd()

'/Users/deven/Desktop/ML_AI/course1/module7_project/trip_records'

In [31]:
for file in os.listdir():
    sample = pd.read_parquet(file)
    df = pd.concat([df, concat_files(sample)])

In [32]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,date,hour,airport_fee
1099,2,2023-12-01 00:13:39,2023-12-01 00:21:26,6.0,1.32,1.0,N,158,246,1,...,0.5,2.86,0.0,1.0,17.16,2.5,0.0,1,0,NaN
1231,2,2023-12-01 00:04:20,2023-12-01 00:17:04,1.0,2.07,1.0,N,142,164,2,...,0.5,0.00,0.0,1.0,18.50,2.5,0.0,1,0,NaN
2779,2,2023-12-01 00:56:00,2023-12-01 01:03:44,2.0,0.92,1.0,N,186,170,1,...,0.5,0.00,0.0,1.0,13.60,2.5,0.0,1,0,NaN
1322,2,2023-12-01 00:17:02,2023-12-01 00:23:44,1.0,0.75,1.0,N,186,230,1,...,0.5,2.58,0.0,1.0,15.48,2.5,0.0,1,0,NaN
3772,2,2023-12-01 00:02:30,2023-12-01 00:21:31,1.0,3.60,1.0,N,79,50,1,...,0.5,5.24,0.0,1.0,31.44,2.5,0.0,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3203004,2,2023-06-30 23:53:10,2023-07-01 00:05:55,1.0,2.63,1.0,N,170,143,1,...,0.5,4.80,0.0,1.0,24.00,2.5,0.0,30,23,NaN
3203122,1,2023-06-30 23:22:42,2023-06-30 23:39:06,1.0,0.00,99.0,N,90,232,1,...,0.5,0.00,0.0,1.0,19.70,0.0,0.0,30,23,NaN
3206515,1,2023-06-30 23:50:42,2023-07-01 00:20:00,2.0,5.40,1.0,N,87,161,1,...,0.5,2.00,0.0,1.0,39.40,2.5,0.0,30,23,NaN
3206491,1,2023-06-30 23:05:31,2023-06-30 23:15:52,1.0,1.00,1.0,N,87,231,2,...,0.5,0.00,0.0,1.0,15.70,2.5,0.0,30,23,NaN
1776,2,2023-05-31 23:53:42,2023-06-01 00:10:46,1.0,3.78,1.0,N,79,52,1,...,0.5,7.65,0.0,1.0,33.15,2.5,0.0,31,23,NaN

In [33]:
df.to_csv("combined.csv")

In [34]:
df.to_parquet("../combined.parquet")

In [35]:
df.shape

(1896420, 22)

In [36]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,date,hour,airport_fee
1099,2,2023-12-01 00:13:39,2023-12-01 00:21:26,6.0,1.32,1.0,N,158,246,1,...,0.5,2.86,0.0,1.0,17.16,2.5,0.0,1,0,NaN
1231,2,2023-12-01 00:04:20,2023-12-01 00:17:04,1.0,2.07,1.0,N,142,164,2,...,0.5,0.00,0.0,1.0,18.50,2.5,0.0,1,0,NaN
2779,2,2023-12-01 00:56:00,2023-12-01 01:03:44,2.0,0.92,1.0,N,186,170,1,...,0.5,0.00,0.0,1.0,13.60,2.5,0.0,1,0,NaN
1322,2,2023-12-01 00:17:02,2023-12-01 00:23:44,1.0,0.75,1.0,N,186,230,1,...,0.5,2.58,0.0,1.0,15.48,2.5,0.0,1,0,NaN
3772,2,2023-12-01 00:02:30,2023-12-01 00:21:31,1.0,3.60,1.0,N,79,50,1,...,0.5,5.24,0.0,1.0,31.44,2.5,0.0,1,0,NaN

In [37]:
df.to_csv("../Nyc_Taxi_Records_2023.csv")