In [1]:
import pandas as pd

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import sklearn
from sklearn.model_selection import train_test_split
from tensorflow import keras

from tensorflow.keras import Sequential

In [2]:
(train_images, train_labels), (test_images, test_labels) = (
    tf.keras.datasets.mnist.load_data()
)

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
train_images = train_images.reshape((60000, 28 * 28))

In [5]:
import pandas as pd

train_labels

array([5, 0, 4, ..., 5, 6, 8], shape=(60000,), dtype=uint8)

In [6]:
model = Sequential()

In [7]:
train_images[0].max()

np.uint8(255)

In [8]:
# from keras import layers
model = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(512, activation="relu"),
        tf.keras.layers.Dense(10, activation="softmax"),
    ]
)

In [9]:
model.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)

In [10]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [11]:
train_images.shape

(60000, 784)

In [12]:
pd.DataFrame(train_images, columns=np.arange(784)).describe()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
count,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,...,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.0,60000.0,60000.0,60000.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000786,0.000348,0.000179,0.000076,0.000059,0.000008,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.023696,0.015514,0.011137,0.006615,0.006582,0.001359,0.0,0.0,0.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.996078,0.996078,0.992157,0.992157,0.996078,0.243137,0.0,0.0,0.0,0.0

In [13]:
train_labels[0]

np.uint8(5)

In [14]:
train_images = train_images.astype("float32") / 255

In [15]:
pd.DataFrame(train_images, columns=np.arange(784)).describe()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
count,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,...,60000.000000,60000.000000,6.000000e+04,6.000000e+04,6.000000e+04,6.000000e+04,60000.0,60000.0,60000.0,60000.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000003,0.000001,7.017813e-07,2.965526e-07,2.324747e-07,3.075740e-08,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000093,0.000061,4.367312e-05,2.594033e-05,2.580982e-05,5.330253e-06,0.0,0.0,0.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.003906,0.003906,3.890811e-03,3.890811e-03,3.906190e-03,9.534794e-04,0.0,0.0,0.0,0.0

In [16]:
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [17]:
test_images[0].max()

np.float32(0.003921569)

In [21]:
import tqdm

history = model.fit(train_images, train_labels, epochs=5, batch_size=128, verbose=1)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9133 - loss: 0.3060
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9161 - loss: 0.2918
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9186 - loss: 0.2800
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9225 - loss: 0.2688
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9255 - loss: 0.2581

In [26]:
max(history.history["accuracy"])

0.9255333542823792

In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         5,130 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,221,152 (4.66 MB)

 Trainable params: 407,050 (1.55 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 814,102 (3.11 MB)

[<Variable path=sequential_5/dense_10/kernel, shape=(784, 512), dtype=float32, value=[[ 0.040343    0.00966348 -0.02696792 ... -0.04857616  0.01419678
   -0.01752263]
  [ 0.04045732  0.06200181 -0.04993426 ... -0.04494643  0.0434191
    0.050436  ]
  [ 0.03130589 -0.05482031  0.01332282 ...  0.00325201  0.06402832
    0.00434627]
  ...
  [ 0.04929228 -0.05947961 -0.02731112 ... -0.06307761  0.04019559
    0.05372354]
  [ 0.02245576 -0.00038285 -0.06174641 ... -0.05671882 -0.03491039
   -0.02259352]
  [ 0.01644815  0.02813689 -0.03189774 ... -0.06721836  0.0336984
    0.01812628]]>,
 <Variable path=sequential_5/dense_10/bias, shape=(512,), dtype=float32, value=[ 2.95401551e-02 -2.22901441e-02  1.86697878e-02 -3.65501596e-03
  -2.13839188e-02  3.02171633e-02  4.03550901e-02 -2.42798403e-02
   1.09509220e-02 -2.23834091e-03  6.28416836e-02 -1.86955612e-02
  -1.06354542e-02  2.95553561e-02 -1.61214415e-02 -5.14308289e-02
   9.32846889e-02 -6.20650947e-02 -7.34084705e-03  3.28883193e-02
   3.99850272e-02 -3.34218554e-02  1.50491076e-03  1.50402440e-02
  -2.64358111e-02  4.02888469e-02  5.42551018e-02  1.84545442e-02
  -2.06794944e-02  3.24804410e-02 -1.50193544e-02  5.99300638e-02
   5.13275228e-02 -2.71849539e-02 -3.48560549e-02  5.38988113e-02
   1.74907092e-02  1.17088286e-02 -1.23382173e-02 -1.86913763e-03
   3.53458058e-03 -2.19786949e-02 -7.20800972e-03 -1.54499253e-02
   1.95689499e-02 -1.77014731e-02  1.95384696e-02 -9.73977894e-03
  -6.90843835e-02  1.27272215e-02 -3.64084635e-03  1.82056874e-02
   4.46274392e-02  1.75755955e-02  1.25982286e-02  2.89600845e-02
   1.61668677e-02  7.49468058e-03  8.64939690e-02  8.04871134e-03
   6.07564710e-02 -1.35924388e-02  2.20780782e-02  8.81663933e-02
   2.67173722e-02  8.00481588e-02 -5.71288820e-03  1.93212274e-02
  -2.99441330e-02 -1.33947497e-02  4.90687378e-02 -4.69467752e-02
   7.99934287e-03 -2.26702690e-02 -5.33261597e-02  2.56231818e-02
   5.54021001e-02 -2.17891838e-02  2.72712647e-03  5.61056621e-02
   5.83528690e-02  5.49802417e-03  1.03210043e-02  5.96500337e-02
   4.89682518e-02 -1.36154499e-02  5.73141538e-02  1.34839481e-02
  -2.81521771e-02  1.92499384e-02  4.07413132e-02 -2.71263923e-02
   7.88638368e-03 -2.44219694e-03  2.07365006e-02  8.99605975e-02
   1.50383804e-02  3.79407518e-02  1.17237028e-03  1.20174084e-02
  -8.71026277e-05  7.82728102e-03 -9.21756588e-03  1.86747629e-02
   1.46703869e-02  1.30702928e-02 -1.31569002e-02  2.89248731e-02
   8.26641265e-03  2.42461935e-02  3.49793471e-02  4.03798036e-02
   5.63830994e-02 -2.24614618e-04  7.42430761e-02 -3.25581804e-02
  -1.74714997e-02 -2.75169462e-02 -1.33978454e-02  3.67487893e-02
  -1.93086069e-03  3.98785248e-02 -1.76691134e-02 -6.64918683e-03
   2.49305423e-02  7.46943103e-03  5.45612983e-02  5.08967564e-02
  -5.86462319e-02  3.34102754e-03 -2.94310283e-02 -9.46076494e-03
   3.11843064e-02  3.99409644e-02 -1.71267930e-02 -4.56827097e-02
  -2.84443609e-02 -1.78470779e-02 -1.91174969e-02 -2.61469856e-02
  -2.53532752e-02 -4.86213230e-02 -1.16680460e-02 -2.63350755e-02
  -2.98552774e-03  4.73725572e-02 -7.27172615e-03  6.27166554e-02
  -9.55897340e-05 -5.46891503e-02  8.88029672e-03 -4.56769019e-03
   4.51811031e-03  4.63443622e-02  1.69431437e-02 -2.57077161e-03
   1.42184505e-02  2.28254963e-02  1.41482884e-02  2.27723289e-02
   2.78202235e-03  6.65975213e-02  5.67522412e-03  2.06374768e-02
   2.21616663e-02 -3.42994579e-03  4.45625186e-03 -5.15872650e-02
   5.31919412e-02 -4.05450724e-02  2.17771879e-03 -5.14071621e-03
   1.58529710e-02  2.96048727e-02  7.97915272e-03  1.86651181e-02
   4.13456261e-02 -1.78588293e-02  3.04975789e-02 -1.63954701e-02
  -1.13246485e-03  1.74781308e-02  9.75047983e-03 -3.26452851e-02
   7.38597009e-04 -4.49409196e-03 -3.99963446e-02  4.82138954e-02
   2.37496272e-02  4.95510250e-02  2.87653296e-03  3.34262513e-02
   1.01548769e-01  7.15126703e-03  2.33984347e-02  2.66656484e-02
  -4.14747670e-02  7.16371760e-02 -2.48595364e-02  1.16356453e-02
  -1.89552102e-02  6.15499681e-04  1.32387411e-02  9.28937644e-03
   1.24785835e-02  3.54179938e-04  2.69793421e-02  3.13633382e-02
   2.28225552e-02  1.39485681e-02 -2.30323859e-02 -1.74593949e-03
  -2.12057196e-02  2.94688977e-02  4.40199524e-02  2.42745224e-02
  -2.96945125e-02 -3.00514325e-02  1.99625939e-02 -1.75066106e-02
   1.04683321e-02  4.33391593e-02  3.78526710e-02 -7.70503236e-03
  -6.57493062e-03  6.44626394e-02  8.15077592e-03  6.46579862e-02
   8.19804966e-02  2.32132375e-02  5.54235652e-02  2.87781898e-02
  -3.01259700e-02  1.07628088e-02  2.85479017e-02 -2.02080868e-02
  -2.60290205e-02  5.76862134e-02  6.95712399e-03  1.30202482e-02
   4.50392365e-02  3.99142951e-02 -7.49705185e-04  5.92808286e-03
  -4.13092971e-02 -7.18171941e-03  6.92570433e-02  4.87078615e-02
   2.16245055e-02 -1.63503215e-02  8.81145615e-03 -1.71962120e-02
   4.74924520e-02  3.27126794e-02  1.12901405e-02 -2.81027239e-02
  -3.77264619e-02  9.96904969e-02 -2.89253350e-02 -4.30755392e-02
   3.96462455e-02 -1.00111635e-02  4.19907197e-02 -8.74386635e-03
  -1.40168229e-02  6.40221918e-03  4.13878672e-02 -5.19151278e-02
  -1.47440378e-03 -2.54927445e-02  5.34277968e-02  9.46573820e-03
   1.37273474e-02  3.14034782e-02  4.85753976e-02 -1.17878616e-02
   5.70004806e-02 -9.53727681e-03  3.35802846e-02  9.74196009e-03
   2.69615166e-02 -8.76535941e-03  1.91986412e-02 -3.00122462e-02
   1.24445790e-02 -7.76610617e-03  7.33323172e-02  6.78099692e-02
   4.64361422e-02  1.08210742e-01  2.59446949e-02  3.18581313e-02
  -1.87122468e-02  9.36013311e-02 -1.72303468e-02  4.46788333e-02
   1.36132920e-02 -1.57713089e-02 -9.18398052e-03  1.56174935e-02
   3.32773253e-02  5.43199806e-03 -2.23643202e-02 -8.44200328e-03
   5.50978875e-04  1.12216445e-02  2.78991777e-02  2.73316931e-02
   1.82940457e-02  5.58456499e-03 -4.74397046e-03 -1.09484689e-02
   7.48735070e-02  1.40127866e-02  3.96528654e-03 -7.55243283e-03
   5.05971573e-02  3.40480544e-02  3.43949832e-02 -2.06954237e-02
   3.13089490e-02  1.44905094e-02  3.82065587e-02  3.97508517e-02
   3.80139835e-02 -6.52533397e-02 -3.04197073e-02  7.84406662e-02
   4.06534486e-02  4.93549816e-02  1.07923336e-02 -5.54363467e-02
   5.63111529e-02 -2.20853202e-02  7.97300413e-03 -1.39187863e-02
   1.34913372e-02  9.07504756e-04  2.94028502e-02  2.73220856e-02
   5.71662746e-03 -1.12760412e-02 -9.23710410e-03  1.92495086e-03
  -4.29013371e-02 -2.12580152e-03  9.73135754e-02  1.11942589e-02
  -2.18725950e-02  2.29950342e-02  5.37704267e-02  6.91826688e-03
  -1.53004201e-02  5.66606075e-02  3.98580730e-03  2.54100561e-02
  -3.35021541e-02  2.04581711e-02  9.06041712e-02 -2.31745616e-02
  -8.04917328e-03  3.60074379e-02 -6.17060903e-03  6.58507049e-02
   2.02491358e-02  8.83009005e-03  2.81562246e-02  2.25046258e-02
  -4.97891381e-02  7.20759854e-05 -1.09451711e-02  6.70479536e-02
  -1.10254884e-02  3.75560261e-02 -5.47885647e-05  4.15605493e-02
   1.00523215e-02 -3.41803655e-02  3.44141796e-02 -6.04661927e-03
  -9.85065568e-03  2.90051475e-02 -3.69649902e-02 -1.14254036e-03
  -6.80963835e-03  5.12966476e-02 -2.94929910e-02  4.75905500e-02
   3.55557143e-03  5.28916419e-02 -1.17110070e-02 -7.44108716e-03
   9.82655585e-03  3.02718543e-02  3.04280594e-02 -2.17129104e-02
   1.91989634e-02  5.55245429e-02  2.18761479e-03  2.54006740e-02
   8.65397453e-02 -1.35116493e-02 -6.17065281e-02  3.42343561e-02
   1.39163276e-02  2.05669142e-02  7.38623738e-02 -3.04375291e-02
  -1.31761720e-02  5.26094437e-03  2.02542897e-02  4.67572212e-02
  -1.04862517e-02 -1.16985955e-03  2.22101789e-02 -4.42567281e-02
  -1.69112980e-02  7.16453476e-04  3.50100473e-02  1.48482388e-02
   4.19704430e-02  7.72956312e-02  1.91196632e-02  7.11420402e-02
   2.15618443e-02  4.19680960e-02 -2.99681164e-02  3.64122465e-02
   5.88708296e-02  1.29076736e-02  3.94525602e-02 -4.73075770e-02
   4.14275937e-02 -1.99204907e-02 -1.82172712e-02  1.69603657e-02
  -2.01961901e-02 -8.94573051e-03  8.30156635e-03  1.51438592e-02
  -4.17041481e-02 -5.56017039e-03 -1.07235042e-02  8.11610743e-02
   2.68897526e-02 -6.09315699e-03 -3.00362017e-02 -7.02824630e-03
  -3.08200195e-02  1.48271993e-02 -9.58663505e-03 -4.33082618e-02
   3.72701362e-02 -1.43079637e-02  3.30166295e-02  7.82685354e-02
   5.21005271e-03 -3.80963460e-03  9.35865287e-03 -2.44492386e-02
   8.12028814e-03  5.42465933e-02  2.63119175e-04 -2.54992712e-02
   1.49166463e-02  6.33393750e-02 -2.15229336e-02  4.51083481e-02
   2.26586056e-03 -1.39086209e-02 -2.41910783e-03  6.37068674e-02
  -3.68198147e-03  7.75166601e-03  1.59606896e-02  2.08483320e-02
   1.60349614e-03 -2.60462184e-02  1.78385973e-02  5.42409606e-02
  -2.30516903e-02 -2.97220424e-02 -3.46337929e-02 -1.52761452e-02
  -4.80092391e-02  2.74307765e-02  6.58019856e-02  6.14325106e-02
   6.20768033e-02 -1.52697163e-02  1.42474577e-03  2.12111268e-02
   5.92564866e-02 -3.30017656e-02 -4.44410462e-03 -3.63269472e-03
  -2.15400141e-04 -5.35678305e-02  2.49885954e-02  1.40997665e-02
  -3.96621414e-02  1.60884243e-02 -1.41842766e-02  5.84393777e-02
   7.22469157e-03 -2.42419094e-02 -3.91942412e-02  1.91727616e-02
  -3.74438688e-02  7.12027475e-02 -3.29927978e-04  7.47512234e-03]>,
 <Variable path=sequential_5/dense_11/kernel, shape=(512, 10), dtype=float32, value=[[-0.09925432  0.10105696 -0.02699577 ... -0.06351505  0.02128766
   -0.13234863]
  [-0.0025479   0.0850591   0.12407852 ... -0.10632681  0.11803807
   -0.02370036]
  [ 0.13953108 -0.02665883 -0.03996712 ... -0.01327715 -0.10930873
   -0.06255252]
  ...
  [-0.1724266   0.06237329  0.10493308 ...  0.06388598  0.20511854
   -0.32626852]
  [ 0.0237214   0.03283779  0.24551482 ...  0.01059318  0.04935768
   -0.30193466]
  [ 0.02143941 -0.13701089 -0.1594298  ...  0.09196877  0.04580736
    0.02025344]]>,
 <Variable path=sequential_5/dense_11/bias, shape=(10,), dtype=float32, value=[-0.03627005 -0.00892812  0.0164442  -0.05007263  0.01730162  0.04258249
   0.00147015 -0.00869689  0.03284276 -0.01353908]>]

In [28]:
predictions_mnist = model.predict(test_images)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 352us/step

In [29]:
predictions_mnist[0].argmax()

np.int64(7)

In [30]:
predictions_mnist[0][7]

np.float32(0.9974024)

In [31]:
test_labels[0]

np.uint8(7)

In [32]:
predictions = model.predict(test_images)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 335us/step

In [33]:
predictions[0].argmax()

np.int64(7)

In [34]:
predictions[0][7]

np.float32(0.9974024)

np.float32(0.11099741)

In [157]:
test_labels[0]

np.uint8(7)

In [245]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.9791 - loss: 0.0629

In [188]:
test_loss

0.2866663336753845

In [189]:
test_acc

0.917900025844574

In [3]:
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras import layers
from tensorflow import keras
import tensorflow as tf

In [4]:
(train_images, train_labels), (test_images, test_labels) = (
    tf.keras.datasets.mnist.load_data()
)

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step

In [5]:
model_cnn = keras.Sequential(
    [
        # Input layer: 28x28 images with 1 color channel (grayscale)
        keras.Input(shape=(28, 28, 1)),
        # Convolutional Block 1
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        # Convolutional Block 2
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        # Flatten and Classify
        layers.Flatten(),
        layers.Dropout(0.5),  # Helps prevent overfitting
        layers.Dense(10, activation="softmax"),
    ]
)

model_cnn.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)

In [ ]:
model_cnn.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5