In [1]:
import numpy as np
import pandas as pd

data = {
    "SubjectName": ["s1", "s2", "s3", "s1", "s4", "s3", "s2", "s1", "s2", "s4", "s1"],
    "Target": [1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
}
df = pd.DataFrame(data)
df

   SubjectName  Target
0           s1       1
1           s2       0
2           s3       1
3           s1       1
4           s4       1
5           s3       0
6           s2       0
7           s1       1
8           s2       1
9           s4       1
10          s1       0

In [2]:
df.groupby("SubjectName")["Target"].count()

SubjectName
s1    4
s2    3
s3    2
s4    2
Name: Target, dtype: int64

In [3]:
df.groupby("SubjectName")["Target"].mean()

SubjectName
s1    0.750000
s2    0.333333
s3    0.500000
s4    1.000000
Name: Target, dtype: float64

In [5]:
mean_encoded_subject = df.groupby("SubjectName")["Target"].mean().to_dict()
df["SubjectName"] = df["SubjectName"].map(mean_encoded_subject)

df

    SubjectName  Target
0      0.750000       1
1      0.333333       0
2      0.500000       1
3      0.750000       1
4      1.000000       1
5      0.500000       0
6      0.333333       0
7      0.750000       1
8      0.333333       1
9      1.000000       1
10     0.750000       0

In [6]:
df = pd.read_clipboard()

In [7]:
df

   target  predictor
0       A        0.4
1       A        0.6
2       A        0.5
3       A        0.2
4       A        0.5
5       B        0.2
6       B        0.3
7       B        0.2
8       B        0.4
9       B        0.6
10      C        0.1

In [8]:
df.groupby("target")["predictor"].mean()

target
A    0.44
B    0.34
C    0.10
Name: predictor, dtype: float64

In [14]:
import numpy as np
from sklearn.preprocessing import TargetEncoder

X = np.array([["dog"] * 20 + ["cat"] * 30 + ["snake"] * 38], dtype=object).T
y = [90.3] * 5 + [80.1] * 15 + [20.4] * 5 + [20.1] * 25 + [21.2] * 8 + [49] * 30
enc_auto = TargetEncoder(smooth="auto")
X_trans = enc_auto.fit_transform(X, y)
X_trans

array([[82.72915511],
       [82.3068919 ],
       [82.19689949],
       [82.30742491],
       [82.19689949],
       [82.72915511],
       [82.30742491],
       [82.3068919 ],
       [83.39607092],
       [83.39607092],
       [82.72915511],
       [82.19689949],
       [83.39607092],
       [82.19689949],
       [83.39607092],
       [82.19689949],
       [82.72915511],
       [82.72915511],
       [83.39607092],
       [82.19689949],
       [20.14617091],
       [20.14287952],
       [20.154571  ],
       [20.14287952],
       [20.14801946],
       [20.14287952],
       [20.154571  ],
       [20.15771448],
       [20.15771448],
       [20.154571  ],
       [20.14287952],
       [20.154571  ],
       [20.14801946],
       [20.14287952],
       [20.14617091],
       [20.154571  ],
       [20.14801946],
       [20.154571  ],
       [20.154571  ],
       [20.14801946],
       [20.14617091],
       [20.14287952],
       [20.14287952],
       [20.15771448],
       [20.154571  ],
       [20.14287952],
       [20.15771448],
       [20.14287952],
       [20.14617091],
       [20.14801946],
       [42.74425554],
       [43.62041368],
       [44.35761121],
       [42.74684989],
       [43.62041368],
       [42.29338811],
       [44.35761121],
       [44.35761121],
       [44.35761121],
       [42.29338811],
       [42.74684989],
       [42.74684989],
       [42.29338811],
       [42.29338811],
       [42.74425554],
       [42.29338811],
       [44.35761121],
       [43.62041368],
       [42.29338811],
       [42.74425554],
       [43.62041368],
       [42.29338811],
       [42.74684989],
       [42.74684989],
       [43.62041368],
       [43.62041368],
       [42.74425554],
       [43.62041368],
       [42.29338811],
       [44.35761121],
       [44.35761121],
       [42.74684989],
       [42.74425554],
       [42.29338811],
       [42.74425554],
       [44.35761121],
       [42.74425554],
       [42.74684989]])

In [13]:
y

[90.3,
 90.3,
 90.3,
 90.3,
 90.3,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 80.1,
 20.4,
 20.4,
 20.4,
 20.4,
 20.4,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 21.2,
 21.2,
 21.2,
 21.2,
 21.2,
 21.2,
 21.2,
 21.2,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49,
 49]

In [11]:
# A high `smooth` parameter puts more weight on global mean on the categorical
# encodings:
enc_high_smooth = TargetEncoder(smooth=5000.0).fit(X, y)
enc_high_smooth.target_mean_, enc_high_smooth.encodings_

(np.float64(44.28522727272727),
 [array([44.1412796 , 44.43807497, 44.27664477])])