In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("nas.csv")

In [3]:
df[:20]

,STUID,State,District,Gender,Age,Category,Same.language,Siblings,Handicap,Father.edu,...,Express.science.views,Watch.TV,Read.magazine,Read.a.book,Play.games,Help.in.household,Maths..,Reading..,Science..,Social..
0,26011001001,Maharashtra,1,Girl,13 years,3.0,2.0,1 sibling,No,Illiterate,...,Agree,Every day,Never,Once a month,Once a week,Every day,NaN,33.33,NaN,NaN
1,26011001002,Maharashtra,1,Girl,15 years,3.0,2.0,3 siblings,No,NaN,...,Agree,Once a week,Never,Never,Once a week,Every day,NaN,62.07,NaN,NaN
2,26011001003,Maharashtra,1,Girl,14 years,3.0,2.0,3 siblings,No,Degree & above,...,Agree,Every day,Once a month,Once a month,Once a week,Every day,NaN,41.38,NaN,NaN
3,26011001004,Maharashtra,1,Boy,13 years,3.0,2.0,3 siblings,No,Secondary,...,Agree,Every day,Every day,Never,Every day,Every day,29.82,NaN,NaN,NaN
4,26011001005,Maharashtra,1,Girl,14 years,3.0,2.0,2 siblings,No,Primary,...,Neither,Never,Never,Once a month,Once a week,Every day,NaN,NaN,27.27,NaN
5,26011001006,Maharashtra,1,Girl,13 years,3.0,2.0,2 siblings,No,Primary,...,Agree,Every day,Once a week,Once a month,Once a week,Every day,NaN,NaN,27.27,NaN
6,26011001007,Maharashtra,1,Girl,14 years,1.0,2.0,1 sibling,No,NaN,...,Agree,Every day,Every day,Never,Every day,Every day,NaN,NaN,NaN,28.57
7,26011001013,Maharashtra,1,Girl,NaN,1.0,2.0,4+ siblings,No,Sr secondary,...,Neither,Every day,Never,Never,Once a week,Every day,NaN,NaN,18.18,NaN
8,26011001014,Maharashtra,1,Girl,NaN,2.0,2.0,2 siblings,No,Primary,...,Agree,Every day,Never,Never,Once a month,Every day,NaN,NaN,23.64,NaN
9,26011001015,Maharashtra,1,Girl,13 years,4.0,2.0,4+ siblings,No,Secondary,...,Neither,Every day,Never,Never,Once a week,Every day,NaN,NaN,NaN,26.53
10,26011001017,Maharashtra,1,Girl,15 years,3.0,1.0,2 siblings,No,Secondary,...,Agree,Every day,Every day,Never,Every day,Every day,NaN,6.67,NaN,NaN
11,26011001018,Maharashtra,1,Girl,13 years,3.0,2.0,4+ siblings,No,Degree & above,...,Agree,Every day,Never,Never,Every day,Every day,NaN,0.00,NaN,NaN
12,26011001019,Maharashtra,1,Boy,15 years,3.0,2.0,3 siblings,No,Illiterate,...,Agree,Every day,Never,Never,Every day,Every day,30.51,NaN,NaN,NaN
13,26011001020,Maharashtra,1,Boy,13 years,3.0,1.0,2 siblings,No,NaN,...,Agree,Every day,Once a month,Once a month,Every day,Every day,21.05,NaN,NaN,NaN
14,26011001021,Maharashtra,1,Boy,15 years,3.0,2.0,3 siblings,No,Sr secondary,...,Neither,Every day,Once a month,Once a month,Every day,Every day,NaN,NaN,30.91,NaN
15,26011001022,Maharashtra,1,Boy,15 years,3.0,2.0,2 siblings,No,NaN,...,Agree,Every day,Never,Never,Every day,Every day,NaN,NaN,25.45,NaN
16,26011001024,Maharashtra,1,Boy,13 years,4.0,2.0,2 siblings,No,Sr secondary,...,Neither,Every day,Never,Once a month,Every day,Every day,NaN,NaN,NaN,24.49
17,26011001025,Maharashtra,1,Boy,15 years,4.0,2.0,4+ siblings,No,Secondary,...,Neither,Every day,Once a month,Once a week,Every day,Every day,NaN,20.00,NaN,NaN
18,26011001028,Maharashtra,1,Girl,13 years,3.0,2.0,3 siblings,No,Illiterate,...,Agree,Every day,Never,Never,Every day,Every day,19.30,NaN,NaN,NaN
19,26011001032,Maharashtra,1,Boy,15 years,4.0,2.0,1 sibling,No,Secondary,...,Neither,Every day,Never,Once a month,Every day,Every day,NaN,NaN,NaN,26.53

In [4]:
df.isna().sum()

STUID                   0
State                   0
District                0
Gender                  2
Age                   232
                     ...
Help.in.household      44
Maths..              4611
Reading..            4574
Science..            4657
Social..             4682
Length: 64, dtype: int64

In [5]:
df.describe()

,STUID,District,Category,Same.language,Maths..,Reading..,Science..,Social..
count,8.801000e+03,8801.000000,8232.000000,8572.000000,4190.000000,4227.000000,4144.000000,4119.000000
mean,2.608389e+10,8.255766,2.787293,1.102776,31.601532,55.404436,36.313272,40.502527
std,4.069188e+07,4.065476,1.146670,0.303684,14.734404,23.279043,13.199105,14.479584
min,2.601100e+10,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2.604207e+10,4.000000,2.000000,1.000000,22.030000,35.575000,27.270000,30.610000
50%,2.609115e+10,9.000000,3.000000,1.000000,28.070000,56.670000,34.550000,38.780000
75%,2.612121e+10,12.000000,4.000000,1.000000,36.840000,73.330000,43.640000,51.020000
max,2.614127e+10,14.000000,4.000000,2.000000,94.740000,100.000000,85.450000,89.800000

In [6]:
cricket = pd.read_csv("odi-batting.csv")

In [7]:
cricket.describe()

               Runs         Balls
count  50284.000000  50284.000000
mean      24.725141     34.019052
std       25.783347     30.773306
min        1.000000      1.000000
25%        6.000000     11.000000
50%       16.000000     24.000000
75%       35.000000     48.000000
max      200.000000    210.000000

In [8]:
cricket.head()

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls
0,Afghanistan,Mohammad Shahzad,118,16-02-2010,Tue,Sharjah CA Stadium,Canada,121
1,Afghanistan,Mohammad Shahzad,110,01-09-2009,Tue,VRA Ground,Netherlands,111
2,Afghanistan,Mohammad Shahzad,100,16-08-2010,Mon,Cambusdoon New Ground,Scotland,72
3,Afghanistan,Mohammad Shahzad,82,10-07-2010,Sat,Hazelaarweg,Netherlands,108
4,Afghanistan,Mohammad Shahzad,57,01-07-2010,Thu,Sportpark Westvliet,Canada,57

In [9]:
cricket["Centuries"] = cricket["Runs"].apply(lambda x: 1 if x >= 100 else 0)

In [10]:
cricket

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls,Centuries
0,Afghanistan,Mohammad Shahzad,118,16-02-2010,Tue,Sharjah CA Stadium,Canada,121,1
1,Afghanistan,Mohammad Shahzad,110,01-09-2009,Tue,VRA Ground,Netherlands,111,1
2,Afghanistan,Mohammad Shahzad,100,16-08-2010,Mon,Cambusdoon New Ground,Scotland,72,1
3,Afghanistan,Mohammad Shahzad,82,10-07-2010,Sat,Hazelaarweg,Netherlands,108,0
4,Afghanistan,Mohammad Shahzad,57,01-07-2010,Thu,Sportpark Westvliet,Canada,57,0
...,...,...,...,...,...,...,...,...,...
50279,Zimbabwe,Kevin G Duers,5,10-03-1992,Tue,Manuka Oval,South Africa,10,0
50280,Zimbabwe,Kevin G Duers,2,14-03-1992,Sat,Bellerive Oval,Australia,10,0
50281,Zimbabwe,Ujesh Ranchod,3,03-02-1993,Wed,Sharjah CA Stadium,Sri Lanka,6,0
50282,Zimbabwe,Brian V Vitori,3,14-09-2011,Wed,Harare Sports Club,Pakistan,3,0
50283,Zimbabwe,Waddington Mwayenga,1,29-05-2004,Sat,Harare Sports Club,Australia,2,0

In [11]:
cricket[cricket["Player"] == "Ricky T Ponting"]["Centuries"].sum()

np.int64(30)

In [12]:
cricket[cricket["Player"] == "Sachin R Tendulkar"]["Centuries"].sum()

np.int64(48)

In [13]:
sr = cricket[cricket["Centuries"] == 1]

In [14]:
sr

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls,Centuries
0,Afghanistan,Mohammad Shahzad,118,16-02-2010,Tue,Sharjah CA Stadium,Canada,121,1
1,Afghanistan,Mohammad Shahzad,110,01-09-2009,Tue,VRA Ground,Netherlands,111,1
2,Afghanistan,Mohammad Shahzad,100,16-08-2010,Mon,Cambusdoon New Ground,Scotland,72,1
62,Afghanistan,Noor Ali Zadran,114,16-02-2010,Tue,Sharjah CA Stadium,Canada,127,1
87,Afghanistan,Karim Sadiq,114,16-08-2010,Mon,Cambusdoon New Ground,Scotland,108,1
...,...,...,...,...,...,...,...,...,...
48682,Zimbabwe,David L Houghton,142,10-10-1987,Sat,Lal Bahadur Shastri Stadium,New Zealand,137,1
48737,Zimbabwe,Dion D Ebrahim,121,25-11-2001,Sun,Bangabandhu National Stadium,Bangladesh,140,1
49101,Zimbabwe,Charles K Coventry,194,16-08-2009,Sun,Queens Sports Club,Bangladesh,156,1
49208,Zimbabwe,Sean M Ervine,100,24-01-2004,Sat,Adelaide Oval,India,100,1
49237,Zimbabwe,Douglas A Marillier,100,05-04-2003,Sat,Sharjah CA Stadium,Kenya,147,1

In [15]:
sr["Strike_Rate"] = sr["Runs"] / sr["Balls"]

/var/folders/1x/76pr210s0kg21gzfc9vtn0x40000gn/T/ipykernel_28227/2210205377.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sr['Strike_Rate']=sr['Runs']/sr['Balls']

In [16]:
sr

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls,Centuries,Strike_Rate
0,Afghanistan,Mohammad Shahzad,118,16-02-2010,Tue,Sharjah CA Stadium,Canada,121,1,0.975207
1,Afghanistan,Mohammad Shahzad,110,01-09-2009,Tue,VRA Ground,Netherlands,111,1,0.990991
2,Afghanistan,Mohammad Shahzad,100,16-08-2010,Mon,Cambusdoon New Ground,Scotland,72,1,1.388889
62,Afghanistan,Noor Ali Zadran,114,16-02-2010,Tue,Sharjah CA Stadium,Canada,127,1,0.897638
87,Afghanistan,Karim Sadiq,114,16-08-2010,Mon,Cambusdoon New Ground,Scotland,108,1,1.055556
...,...,...,...,...,...,...,...,...,...,...
48682,Zimbabwe,David L Houghton,142,10-10-1987,Sat,Lal Bahadur Shastri Stadium,New Zealand,137,1,1.036496
48737,Zimbabwe,Dion D Ebrahim,121,25-11-2001,Sun,Bangabandhu National Stadium,Bangladesh,140,1,0.864286
49101,Zimbabwe,Charles K Coventry,194,16-08-2009,Sun,Queens Sports Club,Bangladesh,156,1,1.243590
49208,Zimbabwe,Sean M Ervine,100,24-01-2004,Sat,Adelaide Oval,India,100,1,1.000000
49237,Zimbabwe,Douglas A Marillier,100,05-04-2003,Sat,Sharjah CA Stadium,Kenya,147,1,0.680272

In [17]:
sr[sr["Player"] == "Shayne R Watson"]

Empty DataFrame
Columns: [Country, Player, Runs, MatchDate, Weekday, Ground, Versus, Balls, Centuries, Strike_Rate]
Index: []

In [18]:
sr[sr["Player"] == "Shahid Afridi"]["Strike_Rate"]

28153    2.066667
28154    1.159574
28155    1.434211
28156    1.173913
28157    2.550000
28158    2.217391
Name: Strike_Rate, dtype: float64

In [19]:
sr.to_csv("centuries.csv")