In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../../data/HR-Employee-Attrition.csv")

In [4]:
df.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [6]:
df.isna().sum().sum()

np.int64(0)

## Dependent Variable -> Attrition
## Independent Variables -> 33

In [7]:
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

In [8]:
## Splitting into categorical and numeric
df_cat = X.select_dtypes(include=["object"])
df_num = X.select_dtypes(include=["int64"])

In [9]:
df_cat.shape, df_num.shape

((1470, 8), (1470, 26))

In [10]:
df_cat.head(10)

,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,Travel_Rarely,Sales,Life Sciences,Female,Sales Executive,Single,Y,Yes
1,Travel_Frequently,Research & Development,Life Sciences,Male,Research Scientist,Married,Y,No
2,Travel_Rarely,Research & Development,Other,Male,Laboratory Technician,Single,Y,Yes
3,Travel_Frequently,Research & Development,Life Sciences,Female,Research Scientist,Married,Y,Yes
4,Travel_Rarely,Research & Development,Medical,Male,Laboratory Technician,Married,Y,No
5,Travel_Frequently,Research & Development,Life Sciences,Male,Laboratory Technician,Single,Y,No
6,Travel_Rarely,Research & Development,Medical,Female,Laboratory Technician,Married,Y,Yes
7,Travel_Rarely,Research & Development,Life Sciences,Male,Laboratory Technician,Divorced,Y,No
8,Travel_Frequently,Research & Development,Life Sciences,Male,Manufacturing Director,Single,Y,No
9,Travel_Rarely,Research & Development,Medical,Male,Healthcare Representative,Married,Y,No

In [11]:
df_cat["BusinessTravel"].value_counts()

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

In [12]:
from utilties.utils import unique_values_percentage

unique_values_percentage(df_cat, df_cat.columns)

{'BusinessTravel':                            column  Count  Percentage (%)
 BusinessTravel
 Travel_Rarely      BusinessTravel   1043       70.952381
 Travel_Frequently  BusinessTravel    277       18.843537
 Non-Travel         BusinessTravel    150       10.204082,
 'Department':                             column  Count  Percentage (%)
 Department
 Research & Development  Department    961       65.374150
 Sales                   Department    446       30.340136
 Human Resources         Department     63        4.285714,
 'EducationField':                           column  Count  Percentage (%)
 EducationField
 Life Sciences     EducationField    606       41.224490
 Medical           EducationField    464       31.564626
 Marketing         EducationField    159       10.816327
 Technical Degree  EducationField    132        8.979592
 Other             EducationField     82        5.578231
 Human Resources   EducationField     27        1.836735,
 'Gender':         column  Count  Percentage (%)
 Gender
 Male    Gender    882            60.0
 Female  Gender    588            40.0,
 'JobRole':                             column  Count  Percentage (%)
 JobRole
 Sales Executive            JobRole    326       22.176871
 Research Scientist         JobRole    292       19.863946
 Laboratory Technician      JobRole    259       17.619048
 Manufacturing Director     JobRole    145        9.863946
 Healthcare Representative  JobRole    131        8.911565
 Manager                    JobRole    102        6.938776
 Sales Representative       JobRole     83        5.646259
 Research Director          JobRole     80        5.442177
 Human Resources            JobRole     52        3.537415,
 'MaritalStatus':                       column  Count  Percentage (%)
 MaritalStatus
 Married        MaritalStatus    673       45.782313
 Single         MaritalStatus    470       31.972789
 Divorced       MaritalStatus    327       22.244898,
 'Over18':         column  Count  Percentage (%)
 Over18
 Y       Over18   1470           100.0,
 'OverTime':             column  Count  Percentage (%)
 OverTime
 No        OverTime   1054        71.70068
 Yes       OverTime    416        28.29932}

In [13]:
df_cat = pd.get_dummies(df_cat, dtype=int, drop_first=True)

In [14]:
df_cat.head(10)

,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Research & Development,Department_Sales,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,Gender_Male,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,0,1,0,1,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
1,1,0,1,0,1,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,0
2,0,1,1,0,0,0,0,1,0,1,...,1,0,0,0,0,0,0,0,1,1
3,1,0,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,1
4,0,1,1,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,1,0,0
5,1,0,1,0,1,0,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
6,0,1,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,1
7,0,1,1,0,1,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
8,1,0,1,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,0,1,0
9,0,1,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0

In [15]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()
df_num_scaled = scaler.fit_transform(df_num)

In [17]:
df_num_scaled = pd.DataFrame(df_num_scaled, columns=df_num.columns, index=df_num.index)

In [18]:
df_num_scaled

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0.446350,0.742527,-1.010909,-0.891688,0.0,-1.701283,-0.660531,1.383138,0.379672,-0.057788,...,-1.584178,0.0,-0.932014,-0.421642,-2.171982,-2.493820,-0.164613,-0.063296,-0.679146,0.245834
1,1.322365,-1.297775,-0.147150,-1.868426,0.0,-1.699621,0.254625,-0.240677,-1.026167,-0.057788,...,1.191438,0.0,0.241988,-0.164511,0.155707,0.338096,0.488508,0.764998,-0.368715,0.806541
2,0.008343,1.414363,-0.887515,-0.891688,0.0,-1.696298,1.169781,1.284725,-1.026167,-0.961486,...,-0.658973,0.0,-0.932014,-0.550208,0.155707,0.338096,-1.144294,-1.167687,-0.679146,-1.155935
3,-0.429664,1.461466,-0.764121,1.061787,0.0,-1.694636,1.169781,-0.486709,0.379672,-0.961486,...,0.266233,0.0,-0.932014,-0.421642,0.155707,0.338096,0.161947,0.764998,0.252146,-1.155935
4,-1.086676,-0.524295,-0.887515,-1.868426,0.0,-1.691313,-1.575686,-1.274014,0.379672,-0.961486,...,1.191438,0.0,0.241988,-0.678774,0.155707,0.338096,-0.817734,-0.615492,-0.058285,-0.595227
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,-0.101159,0.202082,1.703764,-0.891688,0.0,1.721670,0.254625,-1.224807,1.785511,-0.057788,...,0.266233,0.0,0.241988,0.735447,0.155707,0.338096,-0.327893,-0.615492,-0.679146,-0.314873
1466,0.227347,-0.469754,-0.393938,-1.868426,0.0,1.723332,1.169781,-1.175601,-1.026167,0.845911,...,-1.584178,0.0,0.241988,-0.293077,1.707500,0.338096,-0.001333,0.764998,-0.368715,0.806541
1467,-1.086676,-1.605183,-0.640727,0.085049,0.0,1.726655,-0.660531,1.038693,1.785511,-0.057788,...,-0.658973,0.0,0.241988,-0.678774,-2.171982,0.338096,-0.164613,-0.615492,-0.679146,-0.314873
1468,1.322365,0.546677,-0.887515,0.085049,0.0,1.728317,1.169781,-0.142264,-1.026167,-0.057788,...,1.191438,0.0,-0.932014,0.735447,0.155707,-1.077862,0.325228,0.488900,-0.679146,1.086895
1469,-0.320163,-0.432568,-0.147150,0.085049,0.0,1.733302,-0.660531,0.792660,1.785511,-0.057788,...,-1.584178,0.0,-0.932014,-0.678774,0.155707,1.754054,-0.491174,-0.339394,-0.368715,-0.595227

In [19]:
y_mapped = y.apply(lambda x: 1 if x == "Yes" else 0)

In [20]:
y_mapped

0       1
1       0
2       1
3       0
4       0
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: Attrition, Length: 1470, dtype: int64

In [21]:
help(AdaBoostClassifier)

Help on class AdaBoostClassifier in module sklearn.ensemble._weight_boosting:

class AdaBoostClassifier(sklearn.utils._metadata_requests._RoutingNotSupportedMixin, sklearn.base.ClassifierMixin, BaseWeightBoosting)
 |  AdaBoostClassifier(estimator=None, *, n_estimators=50, learning_rate=1.0, algorithm='deprecated', random_state=None)
 |
 |  An AdaBoost classifier.
 |
 |  An AdaBoost [1]_ classifier is a meta-estimator that begins by fitting a
 |  classifier on the original dataset and then fits additional copies of the
 |  classifier on the same dataset but where the weights of incorrectly
 |  classified instances are adjusted such that subsequent classifiers focus
 |  more on difficult cases.
 |
 |  This class implements the algorithm based on [2]_.
 |
 |  Read more in the :ref:`User Guide <adaboost>`.
 |
 |  .. versionadded:: 0.14
 |
 |  Parameters
 |  ----------
 |  estimator : object, default=None
 |      The base estimator from which the boosted ensemble is built.
 |      Support for sample weighting is required, as well as proper
 |      ``classes_`` and ``n_classes_`` attributes. If ``None``, then
 |      the base estimator is :class:`~sklearn.tree.DecisionTreeClassifier`
 |      initialized with `max_depth=1`.
 |
 |      .. versionadded:: 1.2
 |         `base_estimator` was renamed to `estimator`.
 |
 |  n_estimators : int, default=50
 |      The maximum number of estimators at which boosting is terminated.
 |      In case of perfect fit, the learning procedure is stopped early.
 |      Values must be in the range `[1, inf)`.
 |
 |  learning_rate : float, default=1.0
 |      Weight applied to each classifier at each boosting iteration. A higher
 |      learning rate increases the contribution of each classifier. There is
 |      a trade-off between the `learning_rate` and `n_estimators` parameters.
 |      Values must be in the range `(0.0, inf)`.
 |
 |  algorithm : {'SAMME'}, default='SAMME'
 |      Use the SAMME discrete boosting algorithm.
 |
 |      .. deprecated:: 1.6
 |          `algorithm` is deprecated and will be removed in version 1.8. This
 |          estimator only implements the 'SAMME' algorithm.
 |
 |  random_state : int, RandomState instance or None, default=None
 |      Controls the random seed given at each `estimator` at each
 |      boosting iteration.
 |      Thus, it is only used when `estimator` exposes a `random_state`.
 |      Pass an int for reproducible output across multiple function calls.
 |      See :term:`Glossary <random_state>`.
 |
 |  Attributes
 |  ----------
 |  estimator_ : estimator
 |      The base estimator from which the ensemble is grown.
 |
 |      .. versionadded:: 1.2
 |         `base_estimator_` was renamed to `estimator_`.
 |
 |  estimators_ : list of classifiers
 |      The collection of fitted sub-estimators.
 |
 |  classes_ : ndarray of shape (n_classes,)
 |      The classes labels.
 |
 |  n_classes_ : int
 |      The number of classes.
 |
 |  estimator_weights_ : ndarray of floats
 |      Weights for each estimator in the boosted ensemble.
 |
 |  estimator_errors_ : ndarray of floats
 |      Classification error for each estimator in the boosted
 |      ensemble.
 |
 |  feature_importances_ : ndarray of shape (n_features,)
 |      The impurity-based feature importances if supported by the
 |      ``estimator`` (when based on decision trees).
 |
 |      Warning: impurity-based feature importances can be misleading for
 |      high cardinality features (many unique values). See
 |      :func:`sklearn.inspection.permutation_importance` as an alternative.
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  See Also
 |  --------
 |  AdaBoostRegressor : An AdaBoost regressor that begins by fitting a
 |      regressor on the original dataset and then fits additional copies of
 |      the regressor on the same dataset but where the weights of instances
 |      are adjusted according to the error of the current prediction.
 |
 |  GradientBoostingClassifier : GB builds an additive model in a forward
 |      stage-wise fashion. Regression trees are fit on the negative gradient
 |      of the binomial or multinomial deviance loss function. Binary
 |      classification is a special case where only a single regression tree is
 |      induced.
 |
 |  sklearn.tree.DecisionTreeClassifier : A non-parametric supervised learning
 |      method used for classification.
 |      Creates a model that predicts the value of a target variable by
 |      learning simple decision rules inferred from the data features.
 |
 |  References
 |  ----------
 |  .. [1] Y. Freund, R. Schapire, "A Decision-Theoretic Generalization of
 |         on-Line Learning and an Application to Boosting", 1995.
 |
 |  .. [2] :doi:`J. Zhu, H. Zou, S. Rosset, T. Hastie, "Multi-class adaboost."
 |         Statistics and its Interface 2.3 (2009): 349-360.
 |         <10.4310/SII.2009.v2.n3.a8>`
 |
 |  Examples
 |  --------
 |  >>> from sklearn.ensemble import AdaBoostClassifier
 |  >>> from sklearn.datasets import make_classification
 |  >>> X, y = make_classification(n_samples=1000, n_features=4,
 |  ...                            n_informative=2, n_redundant=0,
 |  ...                            random_state=0, shuffle=False)
 |  >>> clf = AdaBoostClassifier(n_estimators=100, random_state=0)
 |  >>> clf.fit(X, y)
 |  AdaBoostClassifier(n_estimators=100, random_state=0)
 |  >>> clf.predict([[0, 0, 0, 0]])
 |  array([1])
 |  >>> clf.score(X, y)
 |  0.96...
 |
 |  For a detailed example of using AdaBoost to fit a sequence of DecisionTrees
 |  as weaklearners, please refer to
 |  :ref:`sphx_glr_auto_examples_ensemble_plot_adaboost_multiclass.py`.
 |
 |  For a detailed example of using AdaBoost to fit a non-linearly seperable
 |  classification dataset composed of two Gaussian quantiles clusters, please
 |  refer to :ref:`sphx_glr_auto_examples_ensemble_plot_adaboost_twoclass.py`.
 |
 |  Method resolution order:
 |      AdaBoostClassifier
 |      sklearn.utils._metadata_requests._RoutingNotSupportedMixin
 |      sklearn.base.ClassifierMixin
 |      BaseWeightBoosting
 |      sklearn.ensemble._base.BaseEnsemble
 |      sklearn.base.MetaEstimatorMixin
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._estimator_html_repr._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, estimator=None, *, n_estimators=50, learning_rate=1.0, algorithm='deprecated', random_state=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  decision_function(self, X)
 |      Compute the decision function of ``X``.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The training input samples. Sparse matrix can be CSC, CSR, COO,
 |          DOK, or LIL. COO, DOK, and LIL are converted to CSR.
 |
 |      Returns
 |      -------
 |      score : ndarray of shape of (n_samples, k)
 |          The decision function of the input samples. The order of
 |          outputs is the same as that of the :term:`classes_` attribute.
 |          Binary classification is a special cases with ``k == 1``,
 |          otherwise ``k==n_classes``. For binary classification,
 |          values closer to -1 or 1 mean more like the first or second
 |          class in ``classes_``, respectively.
 |
 |  predict(self, X)
 |      Predict classes for X.
 |
 |      The predicted class of an input sample is computed as the weighted mean
 |      prediction of the classifiers in the ensemble.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The training input samples. Sparse matrix can be CSC, CSR, COO,
 |          DOK, or LIL. COO, DOK, and LIL are converted to CSR.
 |
 |      Returns
 |      -------
 |      y : ndarray of shape (n_samples,)
 |          The predicted classes.
 |
 |  predict_log_proba(self, X)
 |      Predict class log-probabilities for X.
 |
 |      The predicted class log-probabilities of an input sample is computed as
 |      the weighted mean predicted class log-probabilities of the classifiers
 |      in the ensemble.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The training input samples. Sparse matrix can be CSC, CSR, COO,
 |          DOK, or LIL. COO, DOK, and LIL are converted to CSR.
 |
 |      Returns
 |      -------
 |      p : ndarray of shape (n_samples, n_classes)
 |          The class probabilities of the input samples. The order of
 |          outputs is the same of that of the :term:`classes_` attribute.
 |
 |  predict_proba(self, X)
 |      Predict class probabilities for X.
 |
 |      The predicted class probabilities of an input sample is computed as
 |      the weighted mean predicted class probabilities of the classifiers
 |      in the ensemble.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The training input samples. Sparse matrix can be CSC, CSR, COO,
 |          DOK, or LIL. COO, DOK, and LIL are converted to CSR.
 |
 |      Returns
 |      -------
 |      p : ndarray of shape (n_samples, n_classes)
 |          The class probabilities of the input samples. The order of
 |          outputs is the same of that of the :term:`classes_` attribute.
 |
 |  set_fit_request(self: sklearn.ensemble._weight_boosting.AdaBoostClassifier, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.ensemble._weight_boosting.AdaBoostClassifier from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Request metadata passed to the ``fit`` method.
 |
 |      Note that this method is only relevant if
 |      ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please see :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``fit`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``fit``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      .. note::
 |          This method is only relevant if this estimator is used as a
 |          sub-estimator of a meta-estimator, e.g. used inside a
 |          :class:`~sklearn.pipeline.Pipeline`. Otherwise it has no effect.
 |
 |      Parameters
 |      ----------
 |      sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``sample_weight`` parameter in ``fit``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |
 |  set_score_request(self: sklearn.ensemble._weight_boosting.AdaBoostClassifier, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.ensemble._weight_boosting.AdaBoostClassifier from sklearn.utils._metadata_requests.RequestMethod.__get__.<locals>
 |      Request metadata passed to the ``score`` method.
 |
 |      Note that this method is only relevant if
 |      ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please see :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``score`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``score``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      .. note::
 |          This method is only relevant if this estimator is used as a
 |          sub-estimator of a meta-estimator, e.g. used inside a
 |          :class:`~sklearn.pipeline.Pipeline`. Otherwise it has no effect.
 |
 |      Parameters
 |      ----------
 |      sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``sample_weight`` parameter in ``score``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |
 |  staged_decision_function(self, X)
 |      Compute decision function of ``X`` for each boosting iteration.
 |
 |      This method allows monitoring (i.e. determine error on testing set)
 |      after each boosting iteration.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The training input samples. Sparse matrix can be CSC, CSR, COO,
 |          DOK, or LIL. COO, DOK, and LIL are converted to CSR.
 |
 |      Yields
 |      ------
 |      score : generator of ndarray of shape (n_samples, k)
 |          The decision function of the input samples. The order of
 |          outputs is the same of that of the :term:`classes_` attribute.
 |          Binary classification is a special cases with ``k == 1``,
 |          otherwise ``k==n_classes``. For binary classification,
 |          values closer to -1 or 1 mean more like the first or second
 |          class in ``classes_``, respectively.
 |
 |  staged_predict(self, X)
 |      Return staged predictions for X.
 |
 |      The predicted class of an input sample is computed as the weighted mean
 |      prediction of the classifiers in the ensemble.
 |
 |      This generator method yields the ensemble prediction after each
 |      iteration of boosting and therefore allows monitoring, such as to
 |      determine the prediction on a test set after each boost.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          The input samples. Sparse matrix can be CSC, CSR, COO,
 |          DOK, or LIL. COO, DOK, and LIL are converted to CSR.
 |
 |      Yields
 |      ------
 |      y : generator of ndarray of shape (n_samples,)
 |          The predicted classes.
 |
 |  staged_predict_proba(self, X)
 |      Predict class probabilities for X.
 |
 |      The predicted class probabilities of an input sample is computed as
 |      the weighted mean predicted class probabilities of the classifiers
 |      in the ensemble.
 |
 |      This generator method yields the ensemble predicted class probabilities
 |      after each iteration of boosting and therefore allows monitoring, such
 |      as to determine the predicted class probabilities on a test set after
 |      each boost.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The training input samples. Sparse matrix can be CSC, CSR, COO,
 |          DOK, or LIL. COO, DOK, and LIL are converted to CSR.
 |
 |      Yields
 |      ------
 |      p : generator of ndarray of shape (n_samples,)
 |          The class probabilities of the input samples. The order of
 |          outputs is the same of that of the :term:`classes_` attribute.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'_parameter_constraints': <class 'dict'>}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.utils._metadata_requests._RoutingNotSupportedMixin:
 |
 |  get_metadata_routing(self)
 |      Raise `NotImplementedError`.
 |
 |      This estimator does not support metadata routing yet.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.utils._metadata_requests._RoutingNotSupportedMixin:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.ClassifierMixin:
 |
 |  __sklearn_tags__(self)
 |
 |  score(self, X, y, sample_weight=None)
 |      Return the mean accuracy on the given test data and labels.
 |
 |      In multi-label classification, this is the subset accuracy
 |      which is a harsh metric since you require for each sample that
 |      each label set be correctly predicted.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Test samples.
 |
 |      y : array-like of shape (n_samples,) or (n_samples, n_outputs)
 |          True labels for `X`.
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights.
 |
 |      Returns
 |      -------
 |      score : float
 |          Mean accuracy of ``self.predict(X)`` w.r.t. `y`.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from BaseWeightBoosting:
 |
 |  fit(self, X, y, sample_weight=None)
 |      Build a boosted classifier/regressor from the training set (X, y).
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The training input samples. Sparse matrix can be CSC, CSR, COO,
 |          DOK, or LIL. COO, DOK, and LIL are converted to CSR.
 |
 |      y : array-like of shape (n_samples,)
 |          The target values.
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights. If None, the sample weights are initialized to
 |          1 / n_samples.
 |
 |      Returns
 |      -------
 |      self : object
 |          Fitted estimator.
 |
 |  staged_score(self, X, y, sample_weight=None)
 |      Return staged scores for X, y.
 |
 |      This generator method yields the ensemble score after each iteration of
 |      boosting and therefore allows monitoring, such as to determine the
 |      score on a test set after each boost.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          The training input samples. Sparse matrix can be CSC, CSR, COO,
 |          DOK, or LIL. COO, DOK, and LIL are converted to CSR.
 |
 |      y : array-like of shape (n_samples,)
 |          Labels for X.
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights.
 |
 |      Yields
 |      ------
 |      z : float
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from BaseWeightBoosting:
 |
 |  feature_importances_
 |      The impurity-based feature importances.
 |
 |      The higher, the more important the feature.
 |      The importance of a feature is computed as the (normalized)

In [22]:
X_adaboost = pd.concat([df_num_scaled, df_cat], axis=1)

In [23]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)

In [24]:
clf.fit(X_adaboost, y_mapped)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [25]:
clf.score(X_adaboost, y_mapped)

0.8918367346938776

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_adaboost.shape

(1470, 47)

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    X_adaboost, y_mapped, train_size=0.7, random_state=0, stratify=y_mapped
)

In [29]:
X_train.shape

(1029, 47)

In [30]:
y_train.shape

(1029,)

In [31]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)

In [32]:
clf.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [33]:
y_test_pred = clf.predict(X_test)

In [34]:
clf.score(X_train, y_train)

0.891156462585034

In [35]:
clf.score(X_test, y_test)

0.8616780045351474

In [36]:
from sklearn import metrics

In [37]:
metrics.accuracy_score(y_test, y_test_pred)

0.8616780045351474

In [38]:
cm = metrics.confusion_matrix(y_test, y_test_pred)
cm

array([[362,   8],
       [ 53,  18]])