In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    "name": ["Jack", "Mason", "Tanya", "Jim", "Amelia"],
    "tenure": [42, 52, 36, 24, 73],
    "employees": [4, 24, 31, 2, 3],
    "inventory": [25, 94, 57, 62, 70],
}

In [4]:
df = pd.DataFrame(data, columns=list(data.keys()))

In [5]:
df

     name  tenure  employees  inventory
0    Jack      42          4         25
1   Mason      52         24         94
2   Tanya      36         31         57
3     Jim      24          2         62
4  Amelia      73          3         70

In [7]:
df.corr(method="pearson", numeric_only=True)

             tenure  employees  inventory
tenure     1.000000  -0.105651   0.328852
employees -0.105651   1.000000   0.378039
inventory  0.328852   0.378039   1.000000

In [8]:
df.corr(method="spearman", numeric_only=True)

           tenure  employees  inventory
tenure        1.0        0.1        0.5
employees     0.1        1.0       -0.1
inventory     0.5       -0.1        1.0

In [9]:
df.corr(method="kendall", numeric_only=True)

           tenure  employees  inventory
tenure        1.0        0.0        0.2
employees     0.0        1.0        0.0
inventory     0.2        0.0        1.0