In [1]:
import numpy as np
import pandas as pd

In [6]:
census = pd.read_excel("census data.xlsx", header=None)

In [7]:
census.head()

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,NaN,NaN,NaN,NaN,NaN,C-8 EDUCATIONAL LEVEL BY AGE AND SEX FOR POPU...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Table,State,Distt.,Area Name,Total/,Age-group,Total,NaN,NaN,Illiterate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Name,Code,Code,NaN,Rural/,NaN,NaN,NaN,NaN,NaN,...,NaN,Technical diploma or certificate,NaN,NaN,Graduate & above,NaN,NaN,Unclassified,NaN,NaN
3,NaN,NaN,NaN,NaN,Urban/,NaN,NaN,NaN,NaN,NaN,...,NaN,not equal to degree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,Persons,Males,Females,Persons,...,Females,Persons,Males,Females,Persons,Males,Females,Persons,Males,Females

In [5]:
census

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,C-8 EDUCATIONAL LEVEL BY AGE AND SEX FOR POPULATION AGE 7 AND ABOVE - 2011,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44
0,Table,State,Distt.,Area Name,Total/,Age-group,Total,NaN,NaN,Illiterate,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Name,Code,Code,NaN,Rural/,NaN,NaN,NaN,NaN,NaN,...,NaN,Technical diploma or certificate,NaN,NaN,Graduate & above,NaN,NaN,Unclassified,NaN,NaN
2,NaN,NaN,NaN,NaN,Urban/,NaN,NaN,NaN,NaN,NaN,...,NaN,not equal to degree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,Persons,Males,Females,Persons,...,Females,Persons,Males,Females,Persons,Males,Females,Persons,Males,Females
4,NaN,NaN,NaN,NaN,NaN,1,2,3,4,5,...,31,32,33,34,35,36,37,38,39,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3133,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,65-69,1757,953,804,586,...,0,21,14,7,82,72,10,4,1,3
3134,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,70-74,1193,691,502,419,...,4,14,9,5,56,41,15,7,4,3
3135,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,75-79,645,343,302,234,...,0,6,3,3,22,16,6,7,4,3
3136,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,80+,616,287,329,264,...,0,2,1,1,23,14,9,6,1,5
3137,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,Age not stated,188,94,94,36,...,0,4,2,2,14,7,7,3,1,2

In [8]:
def func(a, b):
    return a - b if a > b else b - a

In [9]:
vfunc = np.vectorize(func)

In [11]:
out = vfunc([1, 2, 3, 4], 2)

In [12]:
out[0]

np.int64(1)

In [24]:
# @np.vectorize(excluded={'0','p'})
def mypolyval(p, x):
    _p = list(p)
    res = _p.pop(0)
    while _p:
        res = res * x + _p.pop(0)
    return res

In [26]:
# mypolyval([1, 2, 3], x=[0, 1])

In [21]:
vpolyval = np.vectorize(mypolyval, excluded={0, "p"})  # excluded={0, 'p'}
vpolyval([1, 2, 3], x=[0, 1])

array([3, 6])

In [23]:
vpolyval(p=[1, 2, 3], x=[1, 2])

array([ 6, 11])

In [27]:
import scipy.stats

pearsonr = np.vectorize(scipy.stats.pearsonr, signature="(n),(n)->(),()")
pearsonr([[0, 1, 2, 3]], [[1, 2, 3, 4], [4, 3, 2, 1]])

(array([ 1., -1.]), array([0., 0.]))