# Predicting ad positioning using Q-Learning
Placement of ads on website is the primary problem for companies that operate on ad revenue. The position where the ad is placed plays pivotal role on whether or not the ad will be clicked. Here we have the following choices:
1. Place them randomly, or
2. Place the ad on the same position

The problem with placing the ad on the same position is the user, after a certain time, will start ignoring the space since he's used to seeing ad at the place, he will end up ignoring that particular position hereafter. Hence, this will reduce the number of clicks on ads. The problem with the former option, placing them randomly, is it wouldn't take optimal positions into consideration. For instance, text beside images are viewed higher number of times than those text which are placed at a distance. It is infeasible to go through every website and repeat the procedure.

Solution: Reinforcement Learning

Using Reinforcement Learning we can approximate the human behavior.

### Why Reinforcement Learning?
We cannot use traditional Machine Learning here, since it requires:
1. Huge data
2. Features
3. Tuning of many hyperparameters

And we neither have huge data, nor features. The only data we have is the position of the banner/ad and whether or not it was clicked. We will use this dataset from Kaggle: https://www.kaggle.com/akram24/ads-ctr-optimisation. We will solve this problem using both model-based (Policy iteration) and model-free methods(Q-Learning & Monte-Carlo). We'll simplify some assumptions for model-based technique.

### Notebook Layout
1. MDP environment - Understanding the dataset
2. Random Policy - placing the ads randomly on different webpages
3. Max policy - placing the ad where it is clicked maximum number of times
4. Model-based Method - Policy Iteration
5. Model-free Method - Q-learning & Monte Carlo

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

In [2]:
df = pd.read_csv("Ads_CTR_Optimisation.csv")

In [3]:
df

      Ad 1  Ad 2  Ad 3  Ad 4  Ad 5  Ad 6  Ad 7  Ad 8  Ad 9  Ad 10
0        1     0     0     0     1     0     0     0     1      0
1        0     0     0     0     0     0     0     0     1      0
2        0     0     0     0     0     0     0     0     0      0
3        0     1     0     0     0     0     0     1     0      0
4        0     0     0     0     0     0     0     0     0      0
...    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
9995     0     0     1     0     0     0     0     1     0      0
9996     0     0     0     0     0     0     0     0     0      0
9997     0     0     0     0     0     0     0     0     0      0
9998     1     0     0     0     0     0     0     1     0      0
9999     0     1     0     0     0     0     0     0     0      0

[10000 rows x 10 columns]

## Dataset

Our environment will be the dataset. It contains 10 ads position per row having values either 1, when the ad is clicked, or 0 when it is not. Every row can be considered as a state in the space, considering it kind of a navigation across multiple pages (on website, for instance) Lets load the dataset and visualize the first few rows.

state = webpage

action = placing the ad at any of the 10 positions on a webpage

reward = +1 if the ad was clicked at the position; else 0

Transition Probability: next webpage that user will end up in is random; therefore, it is 1/(total_webpages -1)

In [4]:
env = df

In [5]:
env.head()

   Ad 1  Ad 2  Ad 3  Ad 4  Ad 5  Ad 6  Ad 7  Ad 8  Ad 9  Ad 10
0     1     0     0     0     1     0     0     0     1      0
1     0     0     0     0     0     0     0     0     1      0
2     0     0     0     0     0     0     0     0     0      0
3     0     1     0     0     0     0     0     1     0      0
4     0     0     0     0     0     0     0     0     0      0

In [6]:
env["Ad 1"].describe()

count    10000.000000
mean         0.170300
std          0.375915
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Ad 1, dtype: float64

In [7]:
(env.iloc[0] == 1).any()

np.True_

In [8]:
urls_clicked = dict()
for i in range(len(env)):
    urls_clicked[i] = 1 if (env.iloc[i] == 1).any() else 0

In [11]:
sum(list(urls_clicked.values())) / len(env)

0.7424

In [12]:
urls_clicked.items()

dict_items([(0, 1), (1, 1), (2, 0), (3, 1), (4, 0), (5, 1), (6, 1), (7, 1), (8, 0), (9, 1), (10, 0), (11, 0), (12, 1), (13, 1), (14, 1), (15, 1), (16, 0), (17, 0), (18, 1), (19, 1), (20, 1), (21, 1), (22, 0), (23, 1), (24, 1), (25, 0), (26, 1), (27, 1), (28, 0), (29, 1), (30, 1), (31, 0), (32, 1), (33, 1), (34, 1), (35, 0), (36, 0), (37, 0), (38, 1), (39, 1), (40, 1), (41, 1), (42, 1), (43, 1), (44, 1), (45, 1), (46, 0), (47, 0), (48, 1), (49, 1), (50, 1), (51, 0), (52, 1), (53, 1), (54, 1), (55, 1), (56, 1), (57, 1), (58, 0), (59, 1), (60, 1), (61, 1), (62, 1), (63, 1), (64, 1), (65, 1), (66, 1), (67, 1), (68, 0), (69, 0), (70, 0), (71, 1), (72, 1), (73, 0), (74, 1), (75, 0), (76, 0), (77, 1), (78, 1), (79, 0), (80, 1), (81, 1), (82, 1), (83, 1), (84, 1), (85, 1), (86, 0), (87, 1), (88, 1), (89, 1), (90, 1), (91, 1), (92, 0), (93, 0), (94, 1), (95, 0), (96, 1), (97, 1), (98, 1), (99, 1), (100, 1), (101, 0), (102, 1), (103, 1), (104, 1), (105, 1), (106, 0), (107, 1), (108, 1), (109, 1), (110, 1), (111, 1), (112, 1), (113, 1), (114, 0), (115, 0), (116, 1), (117, 1), (118, 1), (119, 1), (120, 1), (121, 1), (122, 1), (123, 1), (124, 1), (125, 1), (126, 0), (127, 1), (128, 1), (129, 1), (130, 1), (131, 1), (132, 0), (133, 1), (134, 1), (135, 1), (136, 1), (137, 0), (138, 1), (139, 0), (140, 1), (141, 1), (142, 1), (143, 1), (144, 1), (145, 1), (146, 0), (147, 1), (148, 0), (149, 1), (150, 1), (151, 1), (152, 1), (153, 0), (154, 1), (155, 1), (156, 1), (157, 0), (158, 1), (159, 1), (160, 1), (161, 0), (162, 1), (163, 1), (164, 0), (165, 1), (166, 0), (167, 0), (168, 0), (169, 1), (170, 1), (171, 1), (172, 0), (173, 1), (174, 1), (175, 1), (176, 1), (177, 1), (178, 1), (179, 0), (180, 1), (181, 0), (182, 1), (183, 0), (184, 0), (185, 1), (186, 0), (187, 1), (188, 1), (189, 1), (190, 0), (191, 0), (192, 1), (193, 1), (194, 1), (195, 0), (196, 1), (197, 1), (198, 0), (199, 1), (200, 1), (201, 1), (202, 0), (203, 0), (204, 0), (205, 1), (206, 1), (207, 1), (208, 1), (209, 1), (210, 0), (211, 1), (212, 1), (213, 1), (214, 1), (215, 1), (216, 1), (217, 0), (218, 1), (219, 1), (220, 1), (221, 1), (222, 1), (223, 1), (224, 1), (225, 0), (226, 1), (227, 1), (228, 0), (229, 1), (230, 1), (231, 1), (232, 1), (233, 1), (234, 1), (235, 1), (236, 1), (237, 1), (238, 1), (239, 0), (240, 1), (241, 0), (242, 0), (243, 1), (244, 1), (245, 0), (246, 0), (247, 1), (248, 0), (249, 1), (250, 1), (251, 1), (252, 1), (253, 0), (254, 1), (255, 1), (256, 0), (257, 1), (258, 1), (259, 1), (260, 1), (261, 0), (262, 0), (263, 1), (264, 1), (265, 1), (266, 1), (267, 1), (268, 1), (269, 1), (270, 0), (271, 1), (272, 0), (273, 1), (274, 0), (275, 1), (276, 1), (277, 1), (278, 1), (279, 1), (280, 0), (281, 0), (282, 0), (283, 1), (284, 1), (285, 1), (286, 1), (287, 1), (288, 0), (289, 1), (290, 0), (291, 1), (292, 1), (293, 0), (294, 1), (295, 1), (296, 0), (297, 1), (298, 1), (299, 1), (300, 0), (301, 1), (302, 1), (303, 1), (304, 1), (305, 1), (306, 0), (307, 1), (308, 1), (309, 1), (310, 1), (311, 1), (312, 1), (313, 1), (314, 1), (315, 1), (316, 1), (317, 1), (318, 0), (319, 1), (320, 1), (321, 1), (322, 0), (323, 0), (324, 1), (325, 1), (326, 1), (327, 1), (328, 1), (329, 1), (330, 1), (331, 1), (332, 0), (333, 1), (334, 1), (335, 0), (336, 1), (337, 1), (338, 0), (339, 0), (340, 1), (341, 1), (342, 0), (343, 0), (344, 1), (345, 1), (346, 0), (347, 1), (348, 1), (349, 1), (350, 1), (351, 1), (352, 1), (353, 1), (354, 1), (355, 1), (356, 1), (357, 1), (358, 1), (359, 1), (360, 1), (361, 1), (362, 1), (363, 0), (364, 1), (365, 0), (366, 1), (367, 1), (368, 0), (369, 0), (370, 0), (371, 1), (372, 1), (373, 0), (374, 0), (375, 1), (376, 1), (377, 0), (378, 1), (379, 1), (380, 1), (381, 0), (382, 1), (383, 0), (384, 1), (385, 1), (386, 1), (387, 1), (388, 1), (389, 1), (390, 1), (391, 1), (392, 1), (393, 1), (394, 1), (395, 1), (396, 1), (397, 1), (398, 1), (399, 1), (400, 1), (401, 1), (402, 1), (403, 1), (404, 1), (405, 1), (406, 1), (407, 1), (408, 1), (409, 1), (410, 1), (411, 1), (412, 1), (413, 1), (414, 1), (415, 1), (416, 1), (417, 1), (418, 1), (419, 1), (420, 1), (421, 0), (422, 1), (423, 1), (424, 1), (425, 1), (426, 0), (427, 0), (428, 1), (429, 1), (430, 1), (431, 1), (432, 0), (433, 0), (434, 1), (435, 1), (436, 1), (437, 1), (438, 0), (439, 1), (440, 1), (441, 1), (442, 1), (443, 1), (444, 1), (445, 0), (446, 1), (447, 1), (448, 1), (449, 1), (450, 1), (451, 0), (452, 1), (453, 1), (454, 1), (455, 0), (456, 0), (457, 1), (458, 1), (459, 1), (460, 0), (461, 1), (462, 1), (463, 1), (464, 0), (465, 1), (466, 1), (467, 1), (468, 1), (469, 1), (470, 1), (471, 1), (472, 1), (473, 1), (474, 1), (475, 1), (476, 1), (477, 1), (478, 1), (479, 1), (480, 1), (481, 1), (482, 1), (483, 1), (484, 0), (485, 0), (486, 1), (487, 0), (488, 0), (489, 1), (490, 0), (491, 1), (492, 0), (493, 0), (494, 1), (495, 1), (496, 1), (497, 1), (498, 1), (499, 0), (500, 0), (501, 1), (502, 1), (503, 1), (504, 1), (505, 1), (506, 1), (507, 0), (508, 1), (509, 1), (510, 1), (511, 0), (512, 0), (513, 1), (514, 1), (515, 1), (516, 1), (517, 1), (518, 1), (519, 1), (520, 1), (521, 0), (522, 0), (523, 1), (524, 1), (525, 0), (526, 0), (527, 1), (528, 0), (529, 1), (530, 1), (531, 1), (532, 0), (533, 1), (534, 0), (535, 1), (536, 1), (537, 1), (538, 1), (539, 1), (540, 1), (541, 0), (542, 1), (543, 1), (544, 1), (545, 1), (546, 1), (547, 1), (548, 1), (549, 1), (550, 1), (551, 1), (552, 1), (553, 1), (554, 1), (555, 0), (556, 0), (557, 1), (558, 0), (559, 1), (560, 1), (561, 0), (562, 0), (563, 1), (564, 1), (565, 1), (566, 0), (567, 1), (568, 1), (569, 1), (570, 1), (571, 1), (572, 1), (573, 1), (574, 0), (575, 0), (576, 0), (577, 0), (578, 0), (579, 0), (580, 1), (581, 1), (582, 1), (583, 1), (584, 0), (585, 0), (586, 1), (587, 1), (588, 1), (589, 1), (590, 1), (591, 1), (592, 0), (593, 1), (594, 1), (595, 1), (596, 0), (597, 1), (598, 0), (599, 1), (600, 1), (601, 1), (602, 1), (603, 1), (604, 1), (605, 1), (606, 1), (607, 0), (608, 1), (609, 1), (610, 0), (611, 1), (612, 1), (613, 1), (614, 1), (615, 0), (616, 0), (617, 1), (618, 1), (619, 0), (620, 0), (621, 1), (622, 1), (623, 0), (624, 1), (625, 1), (626, 1), (627, 1), (628, 0), (629, 1), (630, 1), (631, 0), (632, 1), (633, 1), (634, 1), (635, 1), (636, 1), (637, 0), (638, 1), (639, 1), (640, 1), (641, 0), (642, 0), (643, 1), (644, 0), (645, 1), (646, 1), (647, 1), (648, 1), (649, 1), (650, 1), (651, 0), (652, 0), (653, 1), (654, 1), (655, 1), (656, 1), (657, 1), (658, 1), (659, 1), (660, 1), (661, 1), (662, 1), (663, 1), (664, 0), (665, 0), (666, 0), (667, 0), (668, 1), (669, 1), (670, 1), (671, 1), (672, 1), (673, 1), (674, 0), (675, 1), (676, 1), (677, 1), (678, 1), (679, 0), (680, 0), (681, 1), (682, 0), (683, 1), (684, 1), (685, 0), (686, 1), (687, 1), (688, 1), (689, 1), (690, 0), (691, 1), (692, 1), (693, 1), (694, 0), (695, 1), (696, 0), (697, 1), (698, 1), (699, 1), (700, 1), (701, 1), (702, 0), (703, 1), (704, 1), (705, 1), (706, 1), (707, 0), (708, 1), (709, 1), (710, 0), (711, 1), (712, 0), (713, 1), (714, 1), (715, 1), (716, 0), (717, 0), (718, 1), (719, 0), (720, 1), (721, 1), (722, 1), (723, 1), (724, 1), (725, 1), (726, 0), (727, 1), (728, 1), (729, 1), (730, 0), (731, 0), (732, 1), (733, 1), (734, 0), (735, 1), (736, 1), (737, 0), (738, 1), (739, 0), (740, 1), (741, 1), (742, 1), (743, 1), (744, 1), (745, 1), (746, 1), (747, 1), (748, 1), (749, 1), (750, 1), (751, 0), (752, 0), (753, 1), (754, 0), (755, 1), (756, 1), (757, 1), (758, 1), (759, 1), (760, 1), (761, 1), (762, 0), (763, 1), (764, 1), (765, 1), (766, 1), (767, 1), (768, 1), (769, 1), (770, 1), (771, 1), (772, 0), (773, 1), (774, 1), (775, 0), (776, 1), (777, 1), (778, 1), (779, 1), (780, 1), (781, 1), (782, 0), (783, 1), (784, 0), (785, 1), (786, 0), (787, 1), (788, 0), (789, 0), (790, 0), (791, 1), (792, 1), (793, 1), (794, 0), (795, 1), (796, 1), (797, 0), (798, 1), (799, 0), (800, 1), (801, 1), (802, 1), (803, 1), (804, 1), (805, 1), (806, 1), (807, 1), (808, 0), (809, 1), (810, 0), (811, 1), (812, 0), (813, 1), (814, 1), (815, 0), (816, 1), (817, 1), (818, 1), (819, 0), (820, 0), (821, 1), (822, 1), (823, 0), (824, 1), (825, 1), (826, 1), (827, 1), (828, 1), (829, 1), (830, 1), (831, 1), (832, 1), (833, 1), (834, 1), (835, 1), (836, 1), (837, 1), (838, 1), (839, 1), (840, 1), (841, 1), (842, 1), (843, 0), (844, 0), (845, 1), (846, 1), (847, 1), (848, 0), (849, 1), (850, 1), (851, 1), (852, 0), (853, 1), (854, 1), (855, 1), (856, 1), (857, 1), (858, 1), (859, 1), (860, 0), (861, 1), (862, 1), (863, 1), (864, 1), (865, 0), (866, 1), (867, 1), (868, 1), (869, 0), (870, 1), (871, 1), (872, 0), (873, 0), (874, 1), (875, 0), (876, 1), (877, 1), (878, 0), (879, 1), (880, 0), (881, 0), (882, 1), (883, 0), (884, 0), (885, 0), (886, 1), (887, 1), (888, 0), (889, 1), (890, 1), (891, 1), (892, 1), (893, 1), (894, 1), (895, 1), (896, 0), (897, 1), (898, 1), (899, 0), (900, 1), (901, 1), (902, 1), (903, 1), (904, 1), (905, 0), (906, 1), (907, 0), (908, 0), (909, 1), (910, 1), (911, 1), (912, 1), (913, 1), (914, 1), (915, 1), (916, 0), (917, 1), (918, 1), (919, 0), (920, 0), (921, 1), (922, 1), (923, 1), (924, 1), (925, 1), (926, 1), (927, 1), (928, 1), (929, 1), (930, 1), (931, 1), (932, 1), (933, 1), (934, 0), (935, 0), (936, 1), (937, 1), (938, 1), (939, 0), (940, 1), (941, 1), (942, 0), (943, 1), (944, 1), (945, 1), (946, 1), (947, 0), (948, 0), (949, 1), (950, 1), (951, 1), (952, 1), (953, 1), (954, 1), (955, 0), (956, 1), (957, 1), (958, 1), (959, 1), (960, 1), (961, 1), (962, 1), (963, 1), (964, 1), (965, 0), (966, 1), (967, 1), (968, 1), (969, 1), (970, 1), (971, 1), (972, 0), (973, 1), (974, 1), (975, 0), (976, 1), (977, 1), (978, 1), (979, 1), (980, 1), (981, 1), (982, 0), (983, 1), (984, 1), (985, 1), (986, 0), (987, 1), (988, 1), (989, 1), (990, 1), (991, 0), (992, 1), (993, 0), (994, 0), (995, 0), (996, 0), (997, 1), (998, 0), (999, 0), (1000, 1), (1001, 1), (1002, 1), (1003, 0), (1004, 1), (1005, 0), (1006, 1), (1007, 0), (1008, 1), (1009, 1), (1010, 0), (1011, 1), (1012, 1), (1013, 1), (1014, 0), (1015, 1), (1016, 1), (1017, 0), (1018, 1), (1019, 1), (1020, 0), (1021, 1), (1022, 0), (1023, 1), (1024, 1), (1025, 1), (1026, 1), (1027, 0), (1028, 0), (1029, 1), (1030, 1), (1031, 1), (1032, 0), (1033, 0), (1034, 1), (1035, 1), (1036, 1), (1037, 0), (1038, 0), (1039, 1), (1040, 1), (1041, 1), (1042, 1), (1043, 1), (1044, 1), (1045, 0), (1046, 1), (1047, 1), (1048, 0), (1049, 0), (1050, 1), (1051, 1), (1052, 1), (1053, 1), (1054, 1), (1055, 1), (1056, 1), (1057, 1), (1058, 1), (1059, 1), (1060, 1), (1061, 1), (1062, 0), (1063, 1), (1064, 1), (1065, 0), (1066, 1), (1067, 0), (1068, 0), (1069, 0), (1070, 1), (1071, 1), (1072, 1), (1073, 0), (1074, 1), (1075, 1), (1076, 1), (1077, 0), (1078, 1), (1079, 1), (1080, 1), (1081, 1), (1082, 1), (1083, 1), (1084, 1), (1085, 0), (1086, 1), (1087, 1), (1088, 1), (1089, 1), (1090, 0), (1091, 0), (1092, 1), (1093, 1), (1094, 1), (1095, 1), (1096, 0), (1097, 1), (1098, 1), (1099, 1), (1100, 1), (1101, 0), (1102, 1), (1103, 1), (1104, 1), (1105, 0), (1106, 1), (1107, 1), (1108, 0), (1109, 1), (1110, 1), (1111, 1), (1112, 1), (1113, 1), (1114, 1), (1115, 1), (1116, 1), (1117, 1), (1118, 0), (1119, 0), (1120, 1), (1121, 0), (1122, 1), (1123, 1), (1124, 1), (1125, 1), (1126, 1), (1127, 1), (1128, 1), (1129, 0), (1130, 1), (1131, 1), (1132, 0), (1133, 1), (1134, 1), (1135, 1), (1136, 1), (1137, 1), (1138, 1), (1139, 1), (1140, 1), (1141, 1), (1142, 1), (1143, 1), (1144, 1), (1145, 1), (1146, 1), (1147, 0), (1148, 1), (1149, 0), (1150, 0), (1151, 1), (1152, 1), (1153, 1), (1154, 1), (1155, 1), (1156, 1), (1157, 0), (1158, 1), (1159, 1), (1160, 1), (1161, 1), (1162, 0), (1163, 0), (1164, 1), (1165, 1), (1166, 0), (1167, 0), (1168, 1), (1169, 1), (1170, 1), (1171, 1), (1172, 1), (1173, 1), (1174, 1), (1175, 0), (1176, 0), (1177, 1), (1178, 1), (1179, 1), (1180, 1), (1181, 1), (1182, 1), (1183, 0), (1184, 1), (1185, 0), (1186, 1), (1187, 1), (1188, 1), (1189, 1), (1190, 0), (1191, 1), (1192, 0), (1193, 1), (1194, 1), (1195, 1), (1196, 1), (1197, 1), (1198, 0), (1199, 1), (1200, 1), (1201, 0), (1202, 1), (1203, 0), (1204, 1), (1205, 0), (1206, 1), (1207, 0), (1208, 1), (1209, 1), (1210, 1), (1211, 1), (1212, 1), (1213, 1), (1214, 1), (1215, 1), (1216, 1), (1217, 1), (1218, 1), (1219, 1), (1220, 1), (1221, 1), (1222, 1), (1223, 1), (1224, 1), (1225, 0), (1226, 0), (1227, 1), (1228, 1), (1229, 1), (1230, 1), (1231, 1), (1232, 1), (1233, 1), (1234, 0), (1235, 1), (1236, 1), (1237, 1), (1238, 1), (1239, 1), (1240, 1), (1241, 1), (1242, 1), (1243, 1), (1244, 1), (1245, 1), (1246, 0), (1247, 1), (1248, 1), (1249, 1), (1250, 1), (1251, 1), (1252, 1), (1253, 1), (1254, 1), (1255, 0), (1256, 1), (1257, 1), (1258, 1), (1259, 1), (1260, 1), (1261, 0), (1262, 1), (1263, 1), (1264, 1), (1265, 1), (1266, 0), (1267, 1), (1268, 1), (1269, 1), (1270, 0), (1271, 1), (1272, 0), (1273, 1), (1274, 1), (1275, 0), (1276, 1), (1277, 1), (1278, 0), (1279, 1), (1280, 1), (1281, 0), (1282, 1), (1283, 0), (1284, 1), (1285, 1), (1286, 1), (1287, 1), (1288, 1), (1289, 1), (1290, 0), (1291, 0), (1292, 1), (1293, 0), (1294, 1), (1295, 0), (1296, 1), (1297, 1), (1298, 0), (1299, 1), (1300, 1), (1301, 1), (1302, 1), (1303, 1), (1304, 1), (1305, 1), (1306, 1), (1307, 0), (1308, 1), (1309, 1), (1310, 0), (1311, 1), (1312, 0), (1313, 1), (1314, 1), (1315, 1), (1316, 0), (1317, 1), (1318, 1), (1319, 1), (1320, 1), (1321, 1), (1322, 1), (1323, 1), (1324, 1), (1325, 1), (1326, 1), (1327, 1), (1328, 1), (1329, 1), (1330, 1), (1331, 0), (1332, 1), (1333, 1), (1334, 1), (1335, 1), (1336, 1), (1337, 1), (1338, 1), (1339, 1), (1340, 0), (1341, 1), (1342, 1), (1343, 1), (1344, 1), (1345, 1), (1346, 1), (1347, 1), (1348, 0), (1349, 0), (1350, 1), (1351, 1), (1352, 1), (1353, 1), (1354, 0), (1355, 0), (1356, 1), (1357, 1), (1358, 1), (1359, 1), (1360, 1), (1361, 0), (1362, 1), (1363, 1), (1364, 1), (1365, 1), (1366, 1), (1367, 1), (1368, 1), (1369, 1), (1370, 1), (1371, 1), (1372, 1), (1373, 0), (1374, 1), (1375, 1), (1376, 0), (1377, 0), (1378, 1), (1379, 1), (1380, 1), (1381, 0), (1382, 1), (1383, 1), (1384, 1), (1385, 1), (1386, 1), (1387, 0), (1388, 0), (1389, 0), (1390, 0), (1391, 1), (1392, 0), (1393, 1), (1394, 0), (1395, 0), (1396, 1), (1397, 1), (1398, 1), (1399, 1), (1400, 1), (1401, 1), (1402, 1), (1403, 1), (1404, 1), (1405, 0), (1406, 1), (1407, 0), (1408, 1), (1409, 1), (1410, 1), (1411, 1), (1412, 0), (1413, 1), (1414, 1), (1415, 1), (1416, 0), (1417, 1), (1418, 1), (1419, 0), (1420, 0), (1421, 1), (1422, 1), (1423, 1), (1424, 1), (1425, 1), (1426, 1), (1427, 1), (1428, 0), (1429, 0), (1430, 0), (1431, 1), (1432, 1), (1433, 1), (1434, 1), (1435, 0), (1436, 1), (1437, 1), (1438, 1), (1439, 1), (1440, 0), (1441, 1), (1442, 1), (1443, 1), (1444, 1), (1445, 1), (1446, 1), (1447, 1), (1448, 1), (1449, 1), (1450, 1), (1451, 1), (1452, 1), (1453, 0), (1454, 1), (1455, 0), (1456, 0), (1457, 0), (1458, 1), (1459, 0), (1460, 1), (1461, 1), (1462, 1), (1463, 1), (1464, 1), (1465, 1), (1466, 1), (1467, 1), (1468, 1), (1469, 1), (1470, 1), (1471, 0), (1472, 1), (1473, 1), (1474, 1), (1475, 1), (1476, 1), (1477, 1), (1478, 1), (1479, 0), (1480, 1), (1481, 0), (1482, 1), (1483, 1), (1484, 1), (1485, 1), (1486, 1), (1487, 1), (1488, 1), (1489, 1), (1490, 0), (1491, 1), (1492, 1), (1493, 0), (1494, 0), (1495, 1), (1496, 1), (1497, 0), (1498, 1), (1499, 1), (1500, 0), (1501, 1), (1502, 0), (1503, 0), (1504, 0), (1505, 1), (1506, 0), (1507, 1), (1508, 0), (1509, 1), (1510, 0), (1511, 1), (1512, 0), (1513, 1), (1514, 0), (1515, 0), (1516, 1), (1517, 0), (1518, 1), (1519, 1), (1520, 1), (1521, 1), (1522, 0), (1523, 1), (1524, 1), (1525, 1), (1526, 0), (1527, 0), (1528, 1), (1529, 0), (1530, 1), (1531, 1), (1532, 1), (1533, 1), (1534, 1), (1535, 1), (1536, 0), (1537, 0), (1538, 1), (1539, 0), (1540, 1), (1541, 0), (1542, 1), (1543, 0), (1544, 1), (1545, 1), (1546, 1), (1547, 1), (1548, 1), (1549, 0), (1550, 1), (1551, 1), (1552, 1), (1553, 1), (1554, 1), (1555, 1), (1556, 0), (1557, 1), (1558, 1), (1559, 0), (1560, 1), (1561, 1), (1562, 1), (1563, 0), (1564, 1), (1565, 1), (1566, 1), (1567, 0), (1568, 1), (1569, 0), (1570, 1), (1571, 0), (1572, 1), (1573, 1), (1574, 1), (1575, 1), (1576, 1), (1577, 0), (1578, 0), (1579, 0), (1580, 1), (1581, 1), (1582, 1), (1583, 1), (1584, 1), (1585, 1), (1586, 1), (1587, 0), (1588, 1), (1589, 1), (1590, 1), (1591, 1), (1592, 1), (1593, 1), (1594, 1), (1595, 1), (1596, 1), (1597, 1), (1598, 0), (1599, 0), (1600, 1), (1601, 1), (1602, 1), (1603, 0), (1604, 1), (1605, 1), (1606, 1), (1607, 1), (1608, 1), (1609, 1), (1610, 1), (1611, 1), (1612, 1), (1613, 0), (1614, 1), (1615, 0), (1616, 0), (1617, 1), (1618, 1), (1619, 0), (1620, 1), (1621, 0), (1622, 1), (1623, 0), (1624, 1), (1625, 1), (1626, 1), (1627, 0), (1628, 1), (1629, 1), (1630, 1), (1631, 1), (1632, 0), (1633, 1), (1634, 1), (1635, 1), (1636, 1), (1637, 1), (1638, 0), (1639, 1), (1640, 1), (1641, 1), (1642, 0), (1643, 0), (1644, 0), (1645, 0), (1646, 0), (1647, 1), (1648, 1), (1649, 1), (1650, 1), (1651, 0), (1652, 1), (1653, 0), (1654, 0), (1655, 1), (1656, 1), (1657, 1), (1658, 1), (1659, 0), (1660, 1), (1661, 1), (1662, 0), (1663, 1), (1664, 1), (1665, 1), (1666, 0), (1667, 1), (1668, 1), (1669, 1), (1670, 1), (1671, 1), (1672, 1), (1673, 1), (1674, 1), (1675, 1), (1676, 0), (1677, 1), (1678, 1), (1679, 1), (1680, 1), (1681, 1), (1682, 0), (1683, 1), (1684, 0), (1685, 0), (1686, 0), (1687, 0), (1688, 1), (1689, 0), (1690, 1), (1691, 1), (1692, 1), (1693, 1), (1694, 1), (1695, 1), (1696, 1), (1697, 0), (1698, 1), (1699, 0), (1700, 1), (1701, 0), (1702, 1), (1703, 0), (1704, 1), (1705, 0), (1706, 1), (1707, 1), (1708, 1), (1709, 0), (1710, 1), (1711, 0), (1712, 1), (1713, 0), (1714, 1), (1715, 1), (1716, 1), (1717, 0), (1718, 1), (1719, 1), (1720, 1), (1721, 1), (1722, 0), (1723, 1), (1724, 1), (1725, 0), (1726, 0), (1727, 1), (1728, 1), (1729, 0), (1730, 1), (1731, 0), (1732, 0), (1733, 1), (1734, 1), (1735, 0), (1736, 1), (1737, 1), (1738, 1), (1739, 1), (1740, 1), (1741, 1), (1742, 1), (1743, 1), (1744, 1), (1745, 1), (1746, 1), (1747, 1), (1748, 1), (1749, 0), (1750, 1), (1751, 1), (1752, 1), (1753, 1), (1754, 1), (1755, 1), (1756, 1), (1757, 1), (1758, 1), (1759, 1), (1760, 0), (1761, 1), (1762, 1), (1763, 1), (1764, 1), (1765, 0), (1766, 1), (1767, 1), (1768, 1), (1769, 1), (1770, 1), (1771, 1), (1772, 1), (1773, 1), (1774, 0), (1775, 1), (1776, 1), (1777, 1), (1778, 1), (1779, 0), (1780, 0), (1781, 1), (1782, 1), (1783, 0), (1784, 1), (1785, 0), (1786, 1), (1787, 1), (1788, 1), (1789, 1), (1790, 0), (1791, 0), (1792, 0), (1793, 1), (1794, 0), (1795, 1), (1796, 1), (1797, 1), (1798, 1), (1799, 0), (1800, 1), (1801, 0), (1802, 1), (1803, 1), (1804, 1), (1805, 1), (1806, 0), (1807, 1), (1808, 1), (1809, 1), (1810, 0), (1811, 0), (1812, 1), (1813, 1), (1814, 0), (1815, 0), (1816, 1), (1817, 1), (1818, 0), (1819, 1), (1820, 1), (1821, 0), (1822, 1), (1823, 1), (1824, 0), (1825, 1), (1826, 1), (1827, 1), (1828, 1), (1829, 1), (1830, 1), (1831, 1), (1832, 0), (1833, 1), (1834, 1), (1835, 0), (1836, 1), (1837, 1), (1838, 1), (1839, 1), (1840, 1), (1841, 1), (1842, 1), (1843, 0), (1844, 0), (1845, 1), (1846, 1), (1847, 1), (1848, 1), (1849, 0), (1850, 0), (1851, 1), (1852, 1), (1853, 0), (1854, 0), (1855, 1), (1856, 1), (1857, 0), (1858, 1), (1859, 0), (1860, 0), (1861, 1), (1862, 0), (1863, 1), (1864, 1), (1865, 1), (1866, 1), (1867, 0), (1868, 1), (1869, 1), (1870, 0), (1871, 0), (1872, 1), (1873, 1), (1874, 1), (1875, 1), (1876, 0), (1877, 1), (1878, 1), (1879, 1), (1880, 1), (1881, 1), (1882, 1), (1883, 1), (1884, 0), (1885, 1), (1886, 1), (1887, 1), (1888, 1), (1889, 0), (1890, 1), (1891, 0), (1892, 0), (1893, 0), (1894, 1), (1895, 1), (1896, 1), (1897, 0), (1898, 1), (1899, 0), (1900, 1), (1901, 0), (1902, 0), (1903, 1), (1904, 1), (1905, 1), (1906, 0), (1907, 1), (1908, 1), (1909, 1), (1910, 1), (1911, 0), (1912, 1), (1913, 1), (1914, 0), (1915, 1), (1916, 0), (1917, 1), 