In [105]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [95]:
df = pd.read_csv("Housing.csv")

In [96]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [97]:
# yes/no variables
variable_names = [
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea",
]
df[variable_names].head()
df[variable_names] = df[variable_names].map(lambda x: 1 if x == "yes" else 0)

In [98]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished

In [99]:
furnishing = pd.get_dummies(df["furnishingstatus"], dtype=int, drop_first=True)

In [100]:
df_analysis = pd.concat([df, furnishing], axis=1)

In [101]:
df_analysis.drop(["furnishingstatus"], axis=1, inplace=True)

In [108]:
df_analysis.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,semi-furnished,unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0,0

In [109]:
df_train, df_test = train_test_split(df_analysis, test_size=0.7, random_state=42)

In [110]:
y_train = df_train.pop("price")
X_train = df_train

In [111]:
#

In [112]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
X_train_model = scaler.fit_transform(X_train)

In [58]:
# X = df.copy()
# # Remove target
# Y = X.pop("price")
# X = df[['area','bedrooms']]
# # perform a scaler transform of the input data
# scaler = StandardScaler()
# X = scaler.fit_transform(X)
#
# # perform log transformation of target variable (For Sandeep: Is this needed?)
#

In [59]:
# X

array([[ 1.04672629,  1.40341936],
       [ 1.75700953,  1.40341936],
       [ 2.21823241,  0.04727831],
       ...,
       [-0.70592066, -1.30886273],
       [-1.03338891,  0.04727831],
       [-0.5998394 ,  0.04727831]])

In [ ]:
# #sigmoid returns between 0 to 1

In [55]:
# X

array([[ 1.04672629,  1.40341936],
       [ 1.75700953,  1.40341936],
       [ 2.21823241,  0.04727831],
       ...,
       [-0.70592066, -1.30886273],
       [-1.03338891,  0.04727831],
       [-0.5998394 ,  0.04727831]])

In [116]:
y_train = np.log(y_train)

In [118]:
print(np.min(y_train))
print(np.max(y_train))

14.375126345899696
16.32103649495501

In [45]:
# Y.dtype

dtype('float64')

In [113]:
from tensorflow import keras

#

$$f(W^1\times X^T + B^1_0)= f(Z^1) = f(\begin{bmatrix}
z^1_{1}\\
z^1_{2}\\
\end{bmatrix}) =
\begin{bmatrix}
f(z^1_{1})\\
f(z^1_{2})\\
\end{bmatrix}
=
\begin{bmatrix}
h^1_1\\
h^1_2\\
\end{bmatrix}
= H^1
$$

## Part 4: Forward pass matrix multiplication
![](multiple_neurons.png)

![](Matrix.gif)

This network can be described as follows:

- Input vector = $X = (x1,x2)$
- Weight Matrix (hidden layer) = $$W^1 = \begin{bmatrix}
w^1_{11}&&w^1_{12}\\
w^1_{21}&&w^1_{22}\\
\end{bmatrix}
$$
*note the subscripts are being mapped to weights in the figure

- Bias/offset Matrix (hidden layer) = $$
B^1_0 = \begin{bmatrix}
b^1_{1}\\
b^1_{2}\\
\end{bmatrix}
$$

Now the forward pass for the hidden layer can be described as

$$W^1 \times X^T + B^1_0= Z^1 = \begin{bmatrix}
z^1_{1}\\
z^1_{2}\\
\end{bmatrix}
$$

Applying the activation function $f$ over the matrix $Z$ will complete the forward pass.

$$f(W^1 \times X^T + B^1_0)= f(Z^1) = f(\begin{bmatrix}
z^1_{1}\\
z^1_{2}\\
\end{bmatrix}) =
\begin{bmatrix}
f(z^1_{1})\\
f(z^1_{2})\\
\end{bmatrix}
=
\begin{bmatrix}
h^1_1\\
h^1_2\\
\end{bmatrix}
= H^1
$$

For the output layer:

- The weight matrix is $$W^2 = \begin{bmatrix}
w^2_{11}&&w^2_{12}\\
\end{bmatrix}
$$

- The bias/offset matrix is $$B^2_0 = \begin{bmatrix}
b^2_{1}\\
\end{bmatrix}
$$

Now the forward pass can be written as:


$$ B_0^2+W^2 \times H^1$$

$$z^1_{1}$$

$$w^1{11} w^1{21}$$

 $$W^1 = \begin{bmatrix}w^1_{11}&&w^1_{12}\\
 w^1_{21}&&w^1_{22}\\
\end{bmatrix}
$$

In [ ]:
# X.shape[-1]

In [129]:
model = keras.Sequential()
model.add(keras.layers.Input(shape=(X_train_model.shape[-1],)))
model.add(keras.layers.Dense(2, activation="sigmoid"))
model.add(keras.layers.Dense(1, activation="linear"))
model.summary()
#
#
#
#
# # def sigmoid(x):
# #     1/(1+np.exp(-x))

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │            28 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [156]:
model.compile(
    optimizer=keras.optimizers.SGD(),
    loss="mean_squared_error",
    metrics=[keras.metrics.Accuracy],
)  # Stochastic Gradient Descent

In [157]:
history = model.fit(X_train_model, y_train.values, epochs=10, batch_size=32)
#

Epoch 1/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 0.0826
Epoch 2/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 0.0825
Epoch 3/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 0.0823
Epoch 4/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 0.0821
Epoch 5/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 0.0820
Epoch 6/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 0.0819
Epoch 7/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 0.0816
Epoch 8/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 0.0814
Epoch 9/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 0.0813
Epoch 10/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 0.0812

In [159]:
history.history.items()

dict_items([('accuracy', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), ('loss', [0.08262612670660019, 0.08245979249477386, 0.08226321637630463, 0.08205582946538925, 0.08201480656862259, 0.08188917487859726, 0.08164655417203903, 0.08144240081310272, 0.0812612771987915, 0.08120736479759216])])

In [160]:
model.metrics

In [161]:
model.predict(X_train_model)  # todo #confusion

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[15.395807 ],
       [15.492931 ],
       [15.409754 ],
       [15.437281 ],
       [15.150348 ],
       [15.264104 ],
       [15.550767 ],
       [15.659894 ],
       [14.6089325],
       [15.427903 ],
       [15.244976 ],
       [15.236151 ],
       [15.641794 ],
       [15.374689 ],
       [15.290306 ],
       [15.35816  ],
       [15.224806 ],
       [15.484254 ],
       [15.158455 ],
       [15.645525 ],
       [15.305744 ],
       [15.329928 ],
       [15.307798 ],
       [15.540105 ],
       [15.138095 ],
       [15.426242 ],
       [14.714977 ],
       [15.48968  ],
       [15.310558 ],
       [14.908003 ],
       [15.293671 ],
       [15.47375  ],
       [15.211888 ],
       [15.452753 ],
       [15.335159 ],
       [15.413643 ],
       [15.163096 ],
       [15.508856 ],
       [14.403796 ],
       [15.423258 ],
       [14.88279  ],
       [15.439425 ],
       [15.333749 ],
       [15.440072 ],
       [15.370612 ],
       [15.287586 ],
       [15.66823  ],
       [15.415618 ],
       [14.64028  ],
       [15.503151 ],
       [15.385259 ],
       [15.381224 ],
       [15.607813 ],
       [14.372749 ],
       [15.637368 ],
       [14.721408 ],
       [15.269688 ],
       [15.477974 ],
       [15.43445  ],
       [15.476899 ],
       [15.650243 ],
       [15.445451 ],
       [15.1918745],
       [15.5034485],
       [15.227412 ],
       [15.436634 ],
       [15.155139 ],
       [15.202398 ],
       [15.196554 ],
       [14.719155 ],
       [15.22916  ],
       [15.633837 ],
       [15.488483 ],
       [15.512093 ],
       [14.777752 ],
       [15.236805 ],
       [15.445027 ],
       [14.755527 ],
       [15.272947 ],
       [15.11817  ],
       [15.268386 ],
       [15.35329  ],
       [15.225816 ],
       [15.086033 ],
       [15.465753 ],
       [15.660616 ],
       [15.539833 ],
       [15.387377 ],
       [15.355384 ],
       [15.427819 ],
       [15.470736 ],
       [15.392786 ],
       [15.377817 ],
       [15.537404 ],
       [15.409261 ],
       [15.45977  ],
       [14.457306 ],
       [15.168904 ],
       [15.656645 ],
       [15.054872 ],
       [15.449977 ],
       [15.4597225],
       [15.643274 ],
       [14.6500225],
       [14.839785 ],
       [15.353683 ],
       [15.285887 ],
       [14.604602 ],
       [15.213766 ],
       [15.591338 ],
       [15.273454 ],
       [15.118687 ],
       [15.6285   ],
       [15.459861 ],
       [15.421624 ],
       [15.355623 ],
       [15.289785 ],
       [15.409708 ],
       [15.558353 ],
       [15.45193  ],
       [15.316789 ],
       [15.355614 ],
       [15.181799 ],
       [14.484088 ],
       [15.506235 ],
       [15.412301 ],
       [14.409868 ],
       [14.425299 ],
       [15.187149 ],
       [15.54948  ],
       [15.300914 ],
       [15.215245 ],
       [15.328087 ],
       [14.477341 ],
       [15.693461 ],
       [14.786136 ],
       [15.416342 ],
       [15.5645485],
       [15.379574 ],
       [15.115063 ],
       [15.63893  ],
       [15.3146305],
       [15.676962 ],
       [15.118687 ],
       [15.264822 ],
       [14.41389  ],
       [15.274782 ],
       [15.4542885],
       [15.5189705],
       [15.598898 ],
       [14.913661 ],
       [15.419385 ],
       [15.224708 ],
       [15.542292 ],
       [15.222015 ],
       [14.807026 ],
       [15.681285 ],
       [15.466237 ],
       [15.388291 ],
       [15.486841 ],
       [15.335249 ],
       [15.128956 ],
       [15.676274 ]], dtype=float32)

In [162]:
model.metrics

In [ ]:
df_train, df_test = train_test_split(df_analysis, train_size=0.7, random_state=100)

In [71]:
# model.save("housing.keras")
#

In [135]:
y_test = df_test["price"]
X_test = df_test.drop("price", axis=1)

In [147]:
X_test_predict = model.predict(X_test)

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step

In [148]:
X_test_predict

array([[15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028],
       [15.845028]], dtype=float32)

In [149]:
# accuracy?

In [150]:
def random_init_params():
    w1 = tf.Variable(tf.random.uniform((2, 2)))
    b1 = tf.Variable(tf.random.uniform((1, 2)))
    w2 = tf.Variable(tf.random.uniform((2, 1)))
    b2 = tf.Variable(tf.random.uniform((1, 1)))
    return w1, b1, w2, b2

In [153]:
random_init_params()[:2]  # todo

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
 array([[0.3884616 , 0.4822452 ],
        [0.6646795 , 0.73153746]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0.9074862, 0.563818 ]], dtype=float32)>)